package com.nts.teststruts.model;
// Generated 2016-10-23 20:27:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdCarinfo generated by hbm2java
 */
@Entity
@Table(name = "AD_CARINFO", schema = "NC58")
public class AdCarinfo implements java.io.Serializable {

	private String uuid;
	private String carid;
	private String cartype;
	private String carcolor;
	private String carowner;
	private String ownerdept;
	private String ownerjob;
	private String ownertelephone;
	private String note;
	private Date createTime;

	public AdCarinfo() {
	}

	public AdCarinfo(String uuid, Date createTime) {
		this.uuid = uuid;
		this.createTime = createTime;
	}

	public AdCarinfo(String uuid, String carid, String cartype, String carcolor, String carowner, String ownerdept,
			String ownerjob, String ownertelephone, String note, Date createTime) {
		this.uuid = uuid;
		this.carid = carid;
		this.cartype = cartype;
		this.carcolor = carcolor;
		this.carowner = carowner;
		this.ownerdept = ownerdept;
		this.ownerjob = ownerjob;
		this.ownertelephone = ownertelephone;
		this.note = note;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")	
	@Column(name = "UUID", unique = true, nullable = false, length = 32)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "CARID", length = 15)
	public String getCarid() {
		return this.carid;
	}

	public void setCarid(String carid) {
		this.carid = carid;
	}

	@Column(name = "CARTYPE", length = 30)
	public String getCartype() {
		return this.cartype;
	}

	public void setCartype(String cartype) {
		this.cartype = cartype;
	}

	@Column(name = "CARCOLOR", length = 30)
	public String getCarcolor() {
		return this.carcolor;
	}

	public void setCarcolor(String carcolor) {
		this.carcolor = carcolor;
	}

	@Column(name = "CAROWNER", length = 30)
	public String getCarowner() {
		return this.carowner;
	}

	public void setCarowner(String carowner) {
		this.carowner = carowner;
	}

	@Column(name = "OWNERDEPT", length = 30)
	public String getOwnerdept() {
		return this.ownerdept;
	}

	public void setOwnerdept(String ownerdept) {
		this.ownerdept = ownerdept;
	}

	@Column(name = "OWNERJOB", length = 30)
	public String getOwnerjob() {
		return this.ownerjob;
	}

	public void setOwnerjob(String ownerjob) {
		this.ownerjob = ownerjob;
	}

	@Column(name = "OWNERTELEPHONE", length = 50)
	public String getOwnertelephone() {
		return this.ownertelephone;
	}

	public void setOwnertelephone(String ownertelephone) {
		this.ownertelephone = ownertelephone;
	}

	@Column(name = "NOTE", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "车牌号码=" + carid + ", 车型=" + cartype + ", 车身颜色=" + carcolor
				+ ", 车主=" + carowner + ", 部门=" + ownerdept + ", 车主岗位=" + ownerjob + ", 车主电话="
				+ ownertelephone;
	}

	
	
}
