package com.nts.teststruts.model;
// Generated 2015-10-30 9:37:46 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdEquipreck generated by hbm2java
 */
@Entity
@Table(name = "AD_EQUIPRECK", schema = "NC58")
public class AdEquipreck implements java.io.Serializable {

	private Long pkEquipreck;
	private String pkEquip;
	private Long pkEquipck;
	private String pkReckdept;
	private String pkReckuser;
	private Date reckdatetime;
	private String reckstatus;
	private String recknote;
	private String reckcpstatus;

	public AdEquipreck() {
	}

	public AdEquipreck(Long pkEquipreck, String pkEquip) {
		this.pkEquipreck = pkEquipreck;
		this.pkEquip = pkEquip;
	}

	public AdEquipreck(Long pkEquipreck, String pkEquip, Long pkEquipck, String pkReckdept,
			String pkReckuser, Date reckdatetime, String reckstatus, String recknote, String reckcpstatus) {
		this.pkEquipreck = pkEquipreck;
		this.pkEquip = pkEquip;
		this.pkEquipck = pkEquipck;
		this.pkReckdept = pkReckdept;
		this.pkReckuser = pkReckuser;
		this.reckdatetime = reckdatetime;
		this.reckstatus = reckstatus;
		this.recknote = recknote;
		this.reckcpstatus = reckcpstatus;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "PK_EQUIPRECK", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getPkEquipreck() {
		return this.pkEquipreck;
	}

	public void setPkEquipreck(Long pkEquipreck) {
		this.pkEquipreck = pkEquipreck;
	}

	@Column(name = "PK_EQUIP", nullable = false, length = 20)
	public String getPkEquip() {
		return this.pkEquip;
	}

	public void setPkEquip(String pkEquip) {
		this.pkEquip = pkEquip;
	}

	@Column(name = "PK_EQUIPCK", precision = 20, scale = 0)
	public Long getPkEquipck() {
		return this.pkEquipck;
	}

	public void setPkEquipck(Long pkEquipck) {
		this.pkEquipck = pkEquipck;
	}

	@Column(name = "PK_RECKDEPT", length = 20)
	public String getPkReckdept() {
		return this.pkReckdept;
	}

	public void setPkReckdept(String pkReckdept) {
		this.pkReckdept = pkReckdept;
	}

	@Column(name = "PK_RECKUSER", length = 20)
	public String getPkReckuser() {
		return this.pkReckuser;
	}

	public void setPkReckuser(String pkReckuser) {
		this.pkReckuser = pkReckuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECKDATETIME", length = 7)
	public Date getReckdatetime() {
		return this.reckdatetime;
	}

	public void setReckdatetime(Date reckdatetime) {
		this.reckdatetime = reckdatetime;
	}

	@Column(name = "RECKSTATUS", length = 100)
	public String getReckstatus() {
		return this.reckstatus;
	}

	public void setReckstatus(String reckstatus) {
		this.reckstatus = reckstatus;
	}

	@Column(name = "RECKNOTE", length = 200)
	public String getRecknote() {
		return this.recknote;
	}

	public void setRecknote(String recknote) {
		this.recknote = recknote;
	}

	@Column(name = "RECKCPSTATUS", length = 100)
	public String getReckcpstatus() {
		return this.reckcpstatus;
	}

	public void setReckcpstatus(String reckcpstatus) {
		this.reckcpstatus = reckcpstatus;
	}

}
