package com.nts.teststruts.model;
// Generated 2015-9-8 9:14:51 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdEquipck generated by hbm2java
 */
@Entity
@Table(name = "AD_EQUIPCK", schema = "NC58")
public class AdEquipck implements java.io.Serializable {

	private Long pkEquipck;
	private String pkEquip;
	private String pkCkuser;
	private String pkCkdept;
	private Date ckdatetime;
	private String ckstatus;
	private String ckcpstatus;
	private String cknote;
	private String pkEquipckcode;

	public AdEquipck() {
	}

	public AdEquipck(Long pkEquipck, String pkEquip) {
		this.pkEquipck = pkEquipck;
		this.pkEquip = pkEquip;
	}

	public AdEquipck(Long pkEquipck, String pkEquip, String pkCkuser, String pkCkdept, Date ckdatetime,
			String ckstatus,String ckcpstatus, String cknote,String pkEquipckcode) {
		this.pkEquipck = pkEquipck;
		this.pkEquip = pkEquip;
		this.pkCkuser = pkCkuser;
		this.pkCkdept = pkCkdept;
		this.ckdatetime = ckdatetime;
		this.ckstatus = ckstatus;
		this.cknote = cknote;
		this.ckcpstatus = ckcpstatus;
		this.pkEquipckcode = pkEquipckcode;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "PK_EQUIPCK", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getPkEquipck() {
		return this.pkEquipck;
	}

	public void setPkEquipck(Long pkEquipck) {
		this.pkEquipck = pkEquipck;
	}

	@Column(name = "PK_EQUIP", nullable = false, length = 20)
	public String getPkEquip() {
		return this.pkEquip;
	}

	public void setPkEquip(String pkEquip) {
		this.pkEquip = pkEquip;
	}

	@Column(name = "PK_CKUSER", length = 20)
	public String getPkCkuser() {
		return this.pkCkuser;
	}

	public void setPkCkuser(String pkCkuser) {
		this.pkCkuser = pkCkuser;
	}

	@Column(name = "PK_CKDEPT", length = 20)
	public String getPkCkdept() {
		return this.pkCkdept;
	}

	public void setPkCkdept(String pkCkdept) {
		this.pkCkdept = pkCkdept;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CKDATETIME", length = 7)
	public Date getCkdatetime() {
		return this.ckdatetime;
	}

	public void setCkdatetime(Date ckdatetime) {
		this.ckdatetime = ckdatetime;
	}

	@Column(name = "CKSTATUS", length = 100)
	public String getCkstatus() {
		return this.ckstatus;
	}

	public void setCkstatus(String ckstatus) {
		this.ckstatus = ckstatus;
	}

	@Column(name = "CKNOTE", length = 200)
	public String getCknote() {
		return this.cknote;
	}

	public void setCknote(String cknote) {
		this.cknote = cknote;
	}

	@Column(name = "CKCPSTATUS", length = 100)
	public String getCkcpstatus() {
		return ckcpstatus;
	}

	public void setCkcpstatus(String ckcpstatus) {
		this.ckcpstatus = ckcpstatus;
	}


	@Column(name = "PK_EQUIPCKCODE", length = 36)
	public String getPkEquipckcode() {
		return this.pkEquipckcode;
	}

	public void setPkEquipckcode(String pkEquipckcode) {
		this.pkEquipckcode = pkEquipckcode;
	}
	
}
