package com.nts.teststruts.model;
// Generated 2016-9-21 0:02:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdLog generated by hbm2java
 */
@Entity
@Table(name = "AD_LOG", schema = "NC58")
public class AdLog implements java.io.Serializable {

	private String uuidLog;
	private String uuid;
	private String tablename;
	private String operater;
	private String action;
	private String modifycontent;
	private Date createTime;
	private String cknote;

	public AdLog() {
	}

	public AdLog(String uuidLog, String operater, Date createTime) {
		this.uuidLog = uuidLog;
		this.operater = operater;
		this.createTime = createTime;
	}

	public AdLog(String uuidLog, String uuid, String tablename, String operater, String action, String modifycontent,
			Date createTime, String cknote) {
		this.uuidLog = uuidLog;
		this.uuid = uuid;
		this.tablename = tablename;
		this.operater = operater;
		this.action = action;
		this.modifycontent = modifycontent;
		this.createTime = createTime;
		this.cknote = cknote;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")  
	@Column(name = "UUID_LOG", unique = true, nullable = false, length = 32)
	public String getUuidLog() {
		return this.uuidLog;
	}

	public void setUuidLog(String uuidLog) {
		this.uuidLog = uuidLog;
	}

	@Column(name = "UUID", length = 32)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "TABLENAME", length = 30)
	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	@Column(name = "OPERATER", nullable = false, length = 20)
	public String getOperater() {
		return this.operater;
	}

	public void setOperater(String operater) {
		this.operater = operater;
	}

	@Column(name = "ACTION", length = 80)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "MODIFYCONTENT", length = 200)
	public String getModifycontent() {
		return this.modifycontent;
	}

	public void setModifycontent(String modifycontent) {
		this.modifycontent = modifycontent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CKNOTE", length = 100)
	public String getCknote() {
		return this.cknote;
	}

	public void setCknote(String cknote) {
		this.cknote = cknote;
	}

}
