package com.nts.teststruts.model;
// Generated 2016-10-5 8:59:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdPsndocRp2 generated by hbm2java
 */
@Entity
@Table(name = "AD_PSNDOC_RP2", schema = "NC58")
public class AdPsndocRp2 implements java.io.Serializable {

	private String uuid;
	private String bonus;
	private String cknote;
	private Date createTime;
	private String image;
	private String operate;
	private String pkPsndoc;
	private String empdept;
	private String empuserdept;
	private String project;
	private String empleader;
	private String status;
	private int solvestatus;
	private int paystatus;
	private int right;
	private int type;
	private int dr;

	public AdPsndocRp2() {
	}

	public AdPsndocRp2(String uuid, Date createTime, String pkPsndoc) {
		this.uuid = uuid;
		this.createTime = createTime;
		this.pkPsndoc = pkPsndoc;
	}

	public AdPsndocRp2(String uuid, String bonus, String cknote, Date createTime, String image, String operate,
			String pkPsndoc, String empdept, String empuserdept, String project, String empleader, String status,
			int solvestatus, int paystatus, int right, int dr ,int type) {
		this.uuid = uuid;
		this.bonus = bonus;
		this.cknote = cknote;
		this.createTime = createTime;
		this.image = image;
		this.operate = operate;
		this.pkPsndoc = pkPsndoc;
		this.empdept = empdept;
		this.empuserdept = empuserdept;
		this.project = project;
		this.empleader = empleader;
		this.status = status;
		this.solvestatus = solvestatus;
		this.paystatus = paystatus;
		this.right = right;
		this.dr = dr;
		this.type = type;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "UUID", unique = true, nullable = false, length = 32)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "BONUS", length = 32)
	public String getBonus() {
		return this.bonus;
	}

	public void setBonus(String bonus) {
		this.bonus = bonus;
	}

	@Column(name = "CKNOTE", length = 100)
	public String getCknote() {
		return this.cknote;
	}

	public void setCknote(String cknote) {
		this.cknote = cknote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "IMAGE", length = 20)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "OPERATE", length = 20)
	public String getOperate() {
		return this.operate;
	}

	public void setOperate(String operate) {
		this.operate = operate;
	}

	@Column(name = "PK_PSNDOC", nullable = false, length = 20)
	public String getPkPsndoc() {
		return this.pkPsndoc;
	}

	public void setPkPsndoc(String pkPsndoc) {
		this.pkPsndoc = pkPsndoc;
	}

	@Column(name = "EMPDEPT", length = 20)
	public String getEmpdept() {
		return this.empdept;
	}

	public void setEmpdept(String empdept) {
		this.empdept = empdept;
	}

	@Column(name = "EMPUSERDEPT", length = 20)
	public String getEmpuserdept() {
		return this.empuserdept;
	}

	public void setEmpuserdept(String empuserdept) {
		this.empuserdept = empuserdept;
	}

	@Column(name = "PROJECT", length = 20)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "EMPLEADER", length = 32)
	public String getEmpleader() {
		return this.empleader;
	}

	public void setEmpleader(String empleader) {
		this.empleader = empleader;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "SOLVESTATUS", precision = 22, scale = 0)
	public int getSolvestatus() {
		return this.solvestatus;
	}

	public void setSolvestatus(int solvestatus) {
		this.solvestatus = solvestatus;
	}

	@Column(name = "PAYSTATUS", precision = 22, scale = 0)
	public int getPaystatus() {
		return this.paystatus;
	}

	public void setPaystatus(int paystatus) {
		this.paystatus = paystatus;
	}

	@Column(name = "RIGHT", precision = 22, scale = 0)
	public int getRight() {
		return this.right;
	}

	public void setRight(int right) {
		this.right = right;
	}

	@Column(name = "DR", precision = 22, scale = 0)
	public int getDr() {
		return this.dr;
	}

	public void setDr(int dr) {
		this.dr = dr;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}
}
