package com.nts.teststruts.model;
// Generated 2016-4-30 7:42:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdPsndocRp generated by hbm2java
 */
@Entity
@Table(name = "AD_PSNDOC_RP", schema = "NC58")
public class AdPsndocRp  {

	private String uuidRp;
	private String pkPsndoc;
	private String status;
	private Date createTime;
	private String bonus;
	private String image;
	private String cknote;
	private String operate;
	private String dept;
	private int type;
	private String empdept;
	private String empuserdept;
	private String project;
	private String empleader;
	private int right;
	private int dr;

	public AdPsndocRp() {
	}

	public AdPsndocRp(String uuidRp, String pkPsndoc, Date createTime) {
		this.uuidRp = uuidRp;
		this.pkPsndoc = pkPsndoc;
		this.createTime = createTime;
	}

	public AdPsndocRp(String uuidRp, String pkPsndoc, String status, Date createTime, String bonus, String image,
			String cknote ,String operate , String dept ,int type,String empdept,String empuserdept,String project,String empleader,int right,int dr) {
		this.uuidRp = uuidRp;
		this.pkPsndoc = pkPsndoc;
		this.status = status;
		this.createTime = createTime;
		this.bonus = bonus;
		this.image = image;
		this.cknote = cknote;
		this.operate = operate;
		this.dept = dept;
		this.type = type;
		this.empdept = empdept;
		this.empuserdept = empuserdept;
		this.project = project;
		this.empleader = empleader;
		this.right = right;
		this.dr = dr;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")  
	@Column(name = "UUID_RP", unique = true, nullable = false, length = 32)
	public String getUuidRp() {
		return this.uuidRp;
	}

	public void setUuidRp(String uuidRp) {
		this.uuidRp = uuidRp;
	}

	@Column(name = "PK_PSNDOC", nullable = false, length = 20)
	public String getPkPsndoc() {
		return this.pkPsndoc;
	}

	public void setPkPsndoc(String pkPsndoc) {
		this.pkPsndoc = pkPsndoc;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "BONUS", length = 200)
	public String getBonus() {
		return this.bonus;
	}

	public void setBonus(String bonus) {
		this.bonus = bonus;
	}

	@Column(name = "IMAGE", length = 20)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "CKNOTE", length = 100)
	public String getCknote() {
		return this.cknote;
	}

	public void setCknote(String cknote) {
		this.cknote = cknote;
	}

	@Column(name = "OPERATE", length = 20)
	public String getOperate() {
		return operate;
	}

	public void setOperate(String operate) {
		this.operate = operate;
	}

	@Column(name = "DEPT", length = 20)
	public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@Column(name = "TYPE", length = 1)
	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "EMPDEPT", length = 20)
	public String getEmpdept() {
		return empdept;
	}

	public void setEmpdept(String empdept) {
		this.empdept = empdept;
	}

	@Column(name = "EMPUSERDEPT", length = 20)
	public String getEmpuserdept() {
		return empuserdept;
	}

	public void setEmpuserdept(String empuserdept) {
		this.empuserdept = empuserdept;
	}

	@Column(name = "PROJECT", length = 20)
	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "EMPLEADER", length = 20)
	public String getEmpleader() {
		return empleader;
	}

	public void setEmpleader(String empleader) {
		this.empleader = empleader;
	}

	@Column(name = "RIGHT", length = 1)
	public int getRight() {
		return right;
	}

	public void setRight(int right) {
		this.right = right;
	}

	@Column(name = "DR", length = 1)
	public int getDr() {
		return dr;
	}

	public void setDr(int dr) {
		this.dr = dr;
	}

	
}
