package com.nts.teststruts.model;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Adqualitybill generated by hbm2java
 */
@Entity
@Table(name = "ADQUALITYBILL", schema = "NC58")
public class Adqualitybill implements java.io.Serializable {

	private String uuid;
	private String billcode;
	private String billhead;
	private String project;
	private String projectobj;
	private String dept;
	private String wbdept;
	private String createdate;
	private String panding;
	private String yiju;
	private String miaoshu;
	private String diaocha;
	private String fenxi;
	private String fangfa;
	private String image1;
	private String image2;
	private String operator;
	private Date ts;
	private String dr;
	private String type;
	private String appstatus;
	private String appoperator;
	private Date appts;
	private String scanfilename;
	private Integer totalmulct;
	private Integer totalreward;

	public Adqualitybill() {
	}

	public Adqualitybill(String uuid, Date ts) {
		this.uuid = uuid;
		this.ts = ts;
	}

	public Adqualitybill(String uuid, String billcode, String billhead, String project, String projectobj, String dept,String type,
			String wbdept, String createdate, String panding, String yiju, String miaoshu, String diaocha, String fenxi,Integer totalmulct,Integer totalreward,
			String fangfa, String image1, String image2, String operator, Date ts, String dr ,String appstatus,String appoperator,Date appts,String scanfilename) {
		this.uuid = uuid;
		this.billcode = billcode;
		this.billhead = billhead;
		this.project = project;
		this.projectobj = projectobj;
		this.dept = dept;
		this.wbdept = wbdept;
		this.createdate = createdate;
		this.panding = panding;
		this.yiju = yiju;
		this.miaoshu = miaoshu;
		this.diaocha = diaocha;
		this.fenxi = fenxi;
		this.fangfa = fangfa;
		this.image1 = image1;
		this.image2 = image2;
		this.operator = operator;
		this.ts = ts;
		this.dr = dr;
		this.type = type;
		this.totalmulct = totalmulct;
		this.totalreward = totalreward;
		this.appstatus =appstatus;
		this.appoperator = appoperator;
		this.appts =appts;
		this.scanfilename = scanfilename;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")  	
	@Column(name = "UUID", unique = true, nullable = false, length = 32)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "BILLCODE", length = 20)
	public String getBillcode() {
		return this.billcode;
	}

	public void setBillcode(String billcode) {
		this.billcode = billcode.trim();
	}

	@Column(name = "BILLHEAD", length = 50)
	public String getBillhead() {
		return this.billhead;
	}

	public void setBillhead(String billhead) {
		this.billhead = billhead;
	}

	@Column(name = "PROJECT", length = 20)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "PROJECTOBJ", length = 20)
	public String getProjectobj() {
		return this.projectobj;
	}

	public void setProjectobj(String projectobj) {
		this.projectobj = projectobj;
	}

	@Column(name = "DEPT", length = 20)
	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@Column(name = "WBDEPT", length = 20)
	public String getWbdept() {
		return this.wbdept;
	}

	public void setWbdept(String wbdept) {
		this.wbdept = wbdept;
	}

	@Column(name = "CREATEDATE", length = 10)
	public String getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	@Column(name = "PANDING", length = 250)
	public String getPanding() {
		return this.panding;
	}

	public void setPanding(String panding) {
		this.panding = panding;
	}

	@Column(name = "YIJU", length = 1000)
	public String getYiju() {
		return this.yiju;
	}

	public void setYiju(String yiju) {
		this.yiju = yiju;
	}

	@Column(name = "MIAOSHU", length = 1000)
	public String getMiaoshu() {
		return this.miaoshu;
	}

	public void setMiaoshu(String miaoshu) {
		this.miaoshu = miaoshu;
	}

	@Column(name = "DIAOCHA", length = 1000)
	public String getDiaocha() {
		return this.diaocha;
	}

	public void setDiaocha(String diaocha) {
		this.diaocha = diaocha;
	}

	@Column(name = "FENXI", length = 1000)
	public String getFenxi() {
		return this.fenxi;
	}

	public void setFenxi(String fenxi) {
		this.fenxi = fenxi;
	}

	@Column(name = "FANGFA", length = 1000)
	public String getFangfa() {
		return this.fangfa;
	}

	public void setFangfa(String fangfa) {
		this.fangfa = fangfa;
	}

	@Column(name = "IMAGE1", length = 50)
	public String getImage1() {
		return this.image1;
	}

	public void setImage1(String image1) {
		this.image1 = image1;
	}

	@Column(name = "IMAGE2", length = 50)
	public String getImage2() {
		return this.image2;
	}

	public void setImage2(String image2) {
		this.image2 = image2;
	}

	@Column(name = "OPERATOR", length = 50)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TS", nullable = false, length = 7)
	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	@Column(name = "DR", length = 1)
	public String getDr() {
		return this.dr;
	}

	public void setDr(String dr) {
		this.dr = dr;
	}
	
	
	@Column(name = "TYPE", length = 1)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "TOTALMULCT", precision = 22, scale = 0)
	public Integer getTotalmulct() {
		return totalmulct;
	}

	public void setTotalmulct(Integer totalmulct) {
		this.totalmulct = totalmulct;
	}

	@Column(name = "TOTALREWARD", precision = 22, scale = 0)
	public Integer getTotalreward() {
		return totalreward;
	}

	public void setTotalreward(Integer totalreward) {
		this.totalreward = totalreward;
	}

	@Column(name = "APPSTATUS", length = 1)
	public String getAppstatus() {
		return appstatus;
	}

	public void setAppstatus(String appstatus) {
		this.appstatus = appstatus;
	}

	@Column(name = "APPOPERATOR", length = 20)
	public String getAppoperator() {
		return appoperator;
	}

	public void setAppoperator(String appoperator) {
		this.appoperator = appoperator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPTS", nullable = false, length = 7)
	public Date getAppts() {
		return appts;
	}

	public void setAppts(Date appts) {
		this.appts = appts;
	}

	@Column(name = "SCANFILENAME", length = 20)
	public String getScanfilename() {
		return scanfilename;
	}

	public void setScanfilename(String scanfilename) {
		this.scanfilename = scanfilename;
	}
}
