package com.nts.teststruts.model;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdqualitybillSub generated by hbm2java
 */
@Entity
@Table(name = "ADQUALITYBILL_SUB", schema = "NC58")
public class AdqualitybillSub implements java.io.Serializable {

	private String uuid;
	private String huuid;
	private String psnname;
	private String dept;
	private String joblevel;
	private int mulct;
	private String note;
	private String operator;
	private String  dr;
	private Date ts;
	private int reward;

	public AdqualitybillSub() {
	}

	public AdqualitybillSub(String uuid, String huuid, Date ts) {
		this.uuid = uuid;
		this.huuid = huuid;
		this.ts = ts;
	}

	public AdqualitybillSub(String uuid, String huuid, String psnname, String dept, String joblevel, int mulct, int reward ,
			String note, String operator, String dr, Date ts) {
		this.uuid = uuid;
		this.huuid = huuid;
		this.psnname = psnname;
		this.dept = dept;
		this.joblevel = joblevel;
		this.mulct = mulct;
		this.reward = reward;
		this.note = note;
		this.operator = operator;
		this.dr = dr;
		this.ts = ts;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")  
	@Column(name = "UUID", unique = true, nullable = false, length = 32)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "HUUID", nullable = false, length = 32)
	public String getHuuid() {
		return this.huuid;
	}

	public void setHuuid(String huuid) {
		this.huuid = huuid;
	}

	@Column(name = "PSNNAME", length = 20)
	public String getPsnname() {
		return this.psnname;
	}

	public void setPsnname(String psnname) {
		this.psnname = psnname;
	}

	@Column(name = "DEPT", length = 20)
	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@Column(name = "JOBLEVEL", length = 20)
	public String getJoblevel() {
		return this.joblevel;
	}

	public void setJoblevel(String joblevel) {
		this.joblevel = joblevel;
	}

	@Column(name = "MULCT", precision = 22, scale = 0)
	public int getMulct() {
		return this.mulct;
	}

	public void setMulct(int mulct) {
		this.mulct = mulct;
	}
	
	
	@Column(name = "REWARD", precision = 22, scale = 0)
	public int getReward() {
		return reward;
	}

	public void setReward(int reward) {
		this.reward = reward;
	}

	@Column(name = "NOTE", length = 50)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "OPERATOR", length = 20)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "DR", length = 1)
	public String getDr() {
		return this.dr;
	}

	public void setDr(String dr) {
		this.dr = dr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TS", nullable = false, length = 7)
	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

}
