package com.nts.teststruts.model;
// Generated 2015-10-14 16:30:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdRole generated by hbm2java
 */
@Entity
@Table(name = "AD_ROLE", schema = "NC58")
public class AdRole implements java.io.Serializable {

	private String uuidRole;
	private String rolename;
	private String createTime;
	private String roledesc;

	public AdRole() {
	}

	public AdRole(String uuidRole, String createTime) {
		this.uuidRole = uuidRole;
		this.createTime = createTime;
	}

	public AdRole(String uuidRole, String rolename, String createTime, String roledesc) {
		this.uuidRole = uuidRole;
		this.rolename = rolename;
		this.createTime = createTime;
		this.roledesc = roledesc;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")	
	@Column(name = "UUID_ROLE", unique = true, nullable = false, length = 32)
	public String getUuidRole() {
		return this.uuidRole;
	}

	public void setUuidRole(String uuidRole) {
		this.uuidRole = uuidRole;
	}

	@Column(name = "ROLENAME", length = 30)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "CREATE_TIME", nullable = false, length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "ROLEDESC", length = 100)
	public String getRoledesc() {
		return this.roledesc;
	}

	public void setRoledesc(String roledesc) {
		this.roledesc = roledesc;
	}

}
