package com.nts.teststruts.model;
// Generated 2015-10-14 16:30:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdRolemenu generated by hbm2java
 */
@Entity
@Table(name = "AD_ROLEMENU", schema = "NC58")
public class AdRolemenu implements java.io.Serializable {

	private String uuidRolemenu;
	private String uuidRole;
	private String createTime;
	private String uuidMenu;

	public AdRolemenu() {
	}

	public AdRolemenu(String uuidRolemenu, String createTime) {
		this.uuidRolemenu = uuidRolemenu;
		this.createTime = createTime;
	}

	public AdRolemenu(String uuidRolemenu, String uuidRole, String createTime, String uuidMenu) {
		this.uuidRolemenu = uuidRolemenu;
		this.uuidRole = uuidRole;
		this.createTime = createTime;
		this.uuidMenu = uuidMenu;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "UUID_ROLEMENU", unique = true, nullable = false, length = 36)
	public String getUuidRolemenu() {
		return this.uuidRolemenu;
	}

	public void setUuidRolemenu(String uuidRolemenu) {
		this.uuidRolemenu = uuidRolemenu;
	}

	@Column(name = "UUID_ROLE", length = 32)
	public String getUuidRole() {
		return this.uuidRole;
	}

	public void setUuidRole(String uuidRole) {
		this.uuidRole = uuidRole;
	}

	@Column(name = "CREATE_TIME", nullable = false, length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UUID_MENU", length = 36)
	public String getUuidMenu() {
		return this.uuidMenu;
	}

	public void setUuidMenu(String uuidMenu) {
		this.uuidMenu = uuidMenu;
	}

}
