package com.nts.teststruts.model;
// Generated 2015-10-14 16:30:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdUserrole generated by hbm2java
 */
@Entity
@Table(name = "AD_USERROLE", schema = "NC58")
public class AdUserrole implements java.io.Serializable {

	private String uuidUserrole;
	private String cuserid;
	private String uuidRole;
	private String createTime;

	public AdUserrole() {
	}

	public AdUserrole(String uuidUserrole, String cuserid, String uuidRole, String createTime) {
		this.uuidUserrole = uuidUserrole;
		this.cuserid = cuserid;
		this.uuidRole = uuidRole;
		this.createTime = createTime;
	}

	@Id
	@Column(name = "UUID_USERROLE", unique = true, nullable = false, length = 36)
	public String getUuidUserrole() {
		return this.uuidUserrole;
	}

	public void setUuidUserrole(String uuidUserrole) {
		this.uuidUserrole = uuidUserrole;
	}

	@Column(name = "CUSERID", nullable = false, length = 20)
	public String getCuserid() {
		return this.cuserid;
	}

	public void setCuserid(String cuserid) {
		this.cuserid = cuserid;
	}

	@Column(name = "UUID_ROLE", nullable = false, length = 36)
	public String getUuidRole() {
		return this.uuidRole;
	}

	public void setUuidRole(String uuidRole) {
		this.uuidRole = uuidRole;
	}

	@Column(name = "CREATE_TIME", nullable = false, length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
