package com.nts.teststruts.model;
// Generated 2016-9-26 8:44:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * AdWzlist generated by hbm2java
 */
@Entity
@Table(name = "AD_WZLIST", schema = "NC58")
public class AdWzlist implements java.io.Serializable {

	private String uuid;
	private String wzlistcode;
	private String wzlistname;
	private String wztype;
	private String wzlisttype;
	private int wzlistscore;
	private String note;
	private Date createTime;
	private int dr;

	public AdWzlist() {
	}

	public AdWzlist(String uuid, String wzlistcode, String wzlistname, String wztype, Date createTime) {
		this.uuid = uuid;
		this.wzlistcode = wzlistcode;
		this.wzlistname = wzlistname;
		this.wztype = wztype;
		this.createTime = createTime;
	}

	public AdWzlist(String uuid, String wzlistcode, String wzlistname, String wztype, String wzlisttype,
			int wzlistscore, String note, Date createTime, int dr) {
		this.uuid = uuid;
		this.wzlistcode = wzlistcode;
		this.wzlistname = wzlistname;
		this.wztype = wztype;
		this.wzlisttype = wzlisttype;
		this.wzlistscore = wzlistscore;
		this.note = note;
		this.createTime = createTime;
		this.dr = dr;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid") 
	@Column(name = "UUID", unique = true, nullable = false, length = 32)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "WZLISTCODE", nullable = false, length = 10)
	public String getWzlistcode() {
		return this.wzlistcode;
	}

	public void setWzlistcode(String wzlistcode) {
		this.wzlistcode = wzlistcode;
	}

	@Column(name = "WZLISTNAME", nullable = false, length = 300)
	public String getWzlistname() {
		return this.wzlistname;
	}

	public void setWzlistname(String wzlistname) {
		this.wzlistname = wzlistname;
	}

	@Column(name = "WZTYPE", nullable = false, length = 32)
	public String getWztype() {
		return this.wztype;
	}

	public void setWztype(String wztype) {
		this.wztype = wztype;
	}

	@Column(name = "WZLISTTYPE", length = 10)
	public String getWzlisttype() {
		return this.wzlisttype;
	}

	public void setWzlisttype(String wzlisttype) {
		this.wzlisttype = wzlisttype;
	}

	@Column(name = "WZLISTSCORE", precision = 22, scale = 0)
	public int getWzlistscore() {
		return this.wzlistscore;
	}

	public void setWzlistscore(int wzlistscore) {
		this.wzlistscore = wzlistscore;
	}

	@Column(name = "NOTE", length = 50)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "DR", precision = 22, scale = 0)
	public int getDr() {
		return this.dr;
	}

	public void setDr(int dr) {
		this.dr = dr;
	}

}
