package com.nts.teststruts.model;
// Generated 2015-7-24 10:07:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BdCorp generated by hbm2java
 */
@Entity
@Table(name = "BD_CORP", schema = "NC58", uniqueConstraints = { @UniqueConstraint(columnNames = "UNITCODE"),
		@UniqueConstraint(columnNames = "UNITNAME") })
public class BdCorp implements java.io.Serializable {

	private String pkCorp;
	private String begindate;
	private String briefintro;
	private String busibegindate;
	private String busienddate;
	private String chargedeptcode;
	private String chargedeptname;
	private String citycounty;
	private String corptype;
	private String countryarea;
	private String createdate;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private Long dr;
	private String ecotype;
	private String email1;
	private String email2;
	private String email3;
	private String enddate;
	private String fathercorp;
	private String fax1;
	private String fax2;
	private String foreignname;
	private Character holdflag;
	private String idnumber;
	private String industry;
	private String innercode;
	private Character ishasaccount;
	private Character isseal;
	private char isuseretail;
	private Character isworkingunit;
	private String legalbodycode;
	private String linkman1;
	private String linkman2;
	private String linkman3;
	private String maxinnercode;
	private String memo;
	private BigDecimal ownersharerate;
	private String phone1;
	private String phone2;
	private String phone3;
	private String pkCorpkind;
	private String pkCurrency;
	private String postaddr;
	private String province;
	private BigDecimal regcapital;
	private String region;
	private String saleaddr;
	private String sealeddate;
	private BigDecimal showorder;
	private String taxcode;
	private BigDecimal taxpayertype;
	private String ts;
	private String unitcode;
	private String unitdistinction;
	private String unitname;
	private String unitshortname;
	private String url;
	private String zipcode;

	public BdCorp() {
	}

	public BdCorp(String pkCorp, char isuseretail, String unitcode, String unitname, String unitshortname) {
		this.pkCorp = pkCorp;
		this.isuseretail = isuseretail;
		this.unitcode = unitcode;
		this.unitname = unitname;
		this.unitshortname = unitshortname;
	}

	public BdCorp(String pkCorp, String begindate, String briefintro, String busibegindate, String busienddate,
			String chargedeptcode, String chargedeptname, String citycounty, String corptype, String countryarea,
			String createdate, String def1, String def10, String def11, String def12, String def13, String def14,
			String def15, String def16, String def17, String def18, String def19, String def2, String def20,
			String def3, String def4, String def5, String def6, String def7, String def8, String def9, Long dr,
			String ecotype, String email1, String email2, String email3, String enddate, String fathercorp, String fax1,
			String fax2, String foreignname, Character holdflag, String idnumber, String industry, String innercode,
			Character ishasaccount, Character isseal, char isuseretail, Character isworkingunit, String legalbodycode,
			String linkman1, String linkman2, String linkman3, String maxinnercode, String memo,
			BigDecimal ownersharerate, String phone1, String phone2, String phone3, String pkCorpkind,
			String pkCurrency, String postaddr, String province, BigDecimal regcapital, String region, String saleaddr,
			String sealeddate, BigDecimal showorder, String taxcode, BigDecimal taxpayertype, String ts,
			String unitcode, String unitdistinction, String unitname, String unitshortname, String url,
			String zipcode) {
		this.pkCorp = pkCorp;
		this.begindate = begindate;
		this.briefintro = briefintro;
		this.busibegindate = busibegindate;
		this.busienddate = busienddate;
		this.chargedeptcode = chargedeptcode;
		this.chargedeptname = chargedeptname;
		this.citycounty = citycounty;
		this.corptype = corptype;
		this.countryarea = countryarea;
		this.createdate = createdate;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def3 = def3;
		this.def4 = def4;
		this.def5 = def5;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.dr = dr;
		this.ecotype = ecotype;
		this.email1 = email1;
		this.email2 = email2;
		this.email3 = email3;
		this.enddate = enddate;
		this.fathercorp = fathercorp;
		this.fax1 = fax1;
		this.fax2 = fax2;
		this.foreignname = foreignname;
		this.holdflag = holdflag;
		this.idnumber = idnumber;
		this.industry = industry;
		this.innercode = innercode;
		this.ishasaccount = ishasaccount;
		this.isseal = isseal;
		this.isuseretail = isuseretail;
		this.isworkingunit = isworkingunit;
		this.legalbodycode = legalbodycode;
		this.linkman1 = linkman1;
		this.linkman2 = linkman2;
		this.linkman3 = linkman3;
		this.maxinnercode = maxinnercode;
		this.memo = memo;
		this.ownersharerate = ownersharerate;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.phone3 = phone3;
		this.pkCorpkind = pkCorpkind;
		this.pkCurrency = pkCurrency;
		this.postaddr = postaddr;
		this.province = province;
		this.regcapital = regcapital;
		this.region = region;
		this.saleaddr = saleaddr;
		this.sealeddate = sealeddate;
		this.showorder = showorder;
		this.taxcode = taxcode;
		this.taxpayertype = taxpayertype;
		this.ts = ts;
		this.unitcode = unitcode;
		this.unitdistinction = unitdistinction;
		this.unitname = unitname;
		this.unitshortname = unitshortname;
		this.url = url;
		this.zipcode = zipcode;
	}

	@Id

	@Column(name = "PK_CORP", unique = true, nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "BEGINDATE", length = 10)
	public String getBegindate() {
		return this.begindate;
	}

	public void setBegindate(String begindate) {
		this.begindate = begindate;
	}

	@Column(name = "BRIEFINTRO", length = 1000)
	public String getBriefintro() {
		return this.briefintro;
	}

	public void setBriefintro(String briefintro) {
		this.briefintro = briefintro;
	}

	@Column(name = "BUSIBEGINDATE", length = 10)
	public String getBusibegindate() {
		return this.busibegindate;
	}

	public void setBusibegindate(String busibegindate) {
		this.busibegindate = busibegindate;
	}

	@Column(name = "BUSIENDDATE", length = 10)
	public String getBusienddate() {
		return this.busienddate;
	}

	public void setBusienddate(String busienddate) {
		this.busienddate = busienddate;
	}

	@Column(name = "CHARGEDEPTCODE", length = 60)
	public String getChargedeptcode() {
		return this.chargedeptcode;
	}

	public void setChargedeptcode(String chargedeptcode) {
		this.chargedeptcode = chargedeptcode;
	}

	@Column(name = "CHARGEDEPTNAME", length = 60)
	public String getChargedeptname() {
		return this.chargedeptname;
	}

	public void setChargedeptname(String chargedeptname) {
		this.chargedeptname = chargedeptname;
	}

	@Column(name = "CITYCOUNTY", length = 100)
	public String getCitycounty() {
		return this.citycounty;
	}

	public void setCitycounty(String citycounty) {
		this.citycounty = citycounty;
	}

	@Column(name = "CORPTYPE", length = 20)
	public String getCorptype() {
		return this.corptype;
	}

	public void setCorptype(String corptype) {
		this.corptype = corptype;
	}

	@Column(name = "COUNTRYAREA", length = 100)
	public String getCountryarea() {
		return this.countryarea;
	}

	public void setCountryarea(String countryarea) {
		this.countryarea = countryarea;
	}

	@Column(name = "CREATEDATE", length = 10)
	public String getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	@Column(name = "DEF1", length = 100)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 100)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 100)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 100)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 100)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 100)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 100)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 100)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 100)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 100)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 100)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 100)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 100)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF3", length = 100)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF4", length = 100)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF5", length = 100)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF6", length = 100)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 100)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 100)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 100)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "ECOTYPE", length = 20)
	public String getEcotype() {
		return this.ecotype;
	}

	public void setEcotype(String ecotype) {
		this.ecotype = ecotype;
	}

	@Column(name = "EMAIL1", length = 50)
	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	@Column(name = "EMAIL2", length = 50)
	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	@Column(name = "EMAIL3", length = 50)
	public String getEmail3() {
		return this.email3;
	}

	public void setEmail3(String email3) {
		this.email3 = email3;
	}

	@Column(name = "ENDDATE", length = 10)
	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	@Column(name = "FATHERCORP", length = 4)
	public String getFathercorp() {
		return this.fathercorp;
	}

	public void setFathercorp(String fathercorp) {
		this.fathercorp = fathercorp;
	}

	@Column(name = "FAX1", length = 30)
	public String getFax1() {
		return this.fax1;
	}

	public void setFax1(String fax1) {
		this.fax1 = fax1;
	}

	@Column(name = "FAX2", length = 30)
	public String getFax2() {
		return this.fax2;
	}

	public void setFax2(String fax2) {
		this.fax2 = fax2;
	}

	@Column(name = "FOREIGNNAME", length = 60)
	public String getForeignname() {
		return this.foreignname;
	}

	public void setForeignname(String foreignname) {
		this.foreignname = foreignname;
	}

	@Column(name = "HOLDFLAG", length = 1)
	public Character getHoldflag() {
		return this.holdflag;
	}

	public void setHoldflag(Character holdflag) {
		this.holdflag = holdflag;
	}

	@Column(name = "IDNUMBER", length = 60)
	public String getIdnumber() {
		return this.idnumber;
	}

	public void setIdnumber(String idnumber) {
		this.idnumber = idnumber;
	}

	@Column(name = "INDUSTRY", length = 20)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "INNERCODE", length = 60)
	public String getInnercode() {
		return this.innercode;
	}

	public void setInnercode(String innercode) {
		this.innercode = innercode;
	}

	@Column(name = "ISHASACCOUNT", length = 1)
	public Character getIshasaccount() {
		return this.ishasaccount;
	}

	public void setIshasaccount(Character ishasaccount) {
		this.ishasaccount = ishasaccount;
	}

	@Column(name = "ISSEAL", length = 1)
	public Character getIsseal() {
		return this.isseal;
	}

	public void setIsseal(Character isseal) {
		this.isseal = isseal;
	}

	@Column(name = "ISUSERETAIL", nullable = false, length = 1)
	public char getIsuseretail() {
		return this.isuseretail;
	}

	public void setIsuseretail(char isuseretail) {
		this.isuseretail = isuseretail;
	}

	@Column(name = "ISWORKINGUNIT", length = 1)
	public Character getIsworkingunit() {
		return this.isworkingunit;
	}

	public void setIsworkingunit(Character isworkingunit) {
		this.isworkingunit = isworkingunit;
	}

	@Column(name = "LEGALBODYCODE", length = 25)
	public String getLegalbodycode() {
		return this.legalbodycode;
	}

	public void setLegalbodycode(String legalbodycode) {
		this.legalbodycode = legalbodycode;
	}

	@Column(name = "LINKMAN1", length = 25)
	public String getLinkman1() {
		return this.linkman1;
	}

	public void setLinkman1(String linkman1) {
		this.linkman1 = linkman1;
	}

	@Column(name = "LINKMAN2", length = 25)
	public String getLinkman2() {
		return this.linkman2;
	}

	public void setLinkman2(String linkman2) {
		this.linkman2 = linkman2;
	}

	@Column(name = "LINKMAN3", length = 25)
	public String getLinkman3() {
		return this.linkman3;
	}

	public void setLinkman3(String linkman3) {
		this.linkman3 = linkman3;
	}

	@Column(name = "MAXINNERCODE", length = 60)
	public String getMaxinnercode() {
		return this.maxinnercode;
	}

	public void setMaxinnercode(String maxinnercode) {
		this.maxinnercode = maxinnercode;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "OWNERSHARERATE", precision = 9, scale = 6)
	public BigDecimal getOwnersharerate() {
		return this.ownersharerate;
	}

	public void setOwnersharerate(BigDecimal ownersharerate) {
		this.ownersharerate = ownersharerate;
	}

	@Column(name = "PHONE1", length = 30)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "PHONE2", length = 30)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "PHONE3", length = 30)
	public String getPhone3() {
		return this.phone3;
	}

	public void setPhone3(String phone3) {
		this.phone3 = phone3;
	}

	@Column(name = "PK_CORPKIND", length = 20)
	public String getPkCorpkind() {
		return this.pkCorpkind;
	}

	public void setPkCorpkind(String pkCorpkind) {
		this.pkCorpkind = pkCorpkind;
	}

	@Column(name = "PK_CURRENCY", length = 20)
	public String getPkCurrency() {
		return this.pkCurrency;
	}

	public void setPkCurrency(String pkCurrency) {
		this.pkCurrency = pkCurrency;
	}

	@Column(name = "POSTADDR", length = 400)
	public String getPostaddr() {
		return this.postaddr;
	}

	public void setPostaddr(String postaddr) {
		this.postaddr = postaddr;
	}

	@Column(name = "PROVINCE", length = 50)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "REGCAPITAL", precision = 20)
	public BigDecimal getRegcapital() {
		return this.regcapital;
	}

	public void setRegcapital(BigDecimal regcapital) {
		this.regcapital = regcapital;
	}

	@Column(name = "REGION", length = 20)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "SALEADDR", length = 400)
	public String getSaleaddr() {
		return this.saleaddr;
	}

	public void setSaleaddr(String saleaddr) {
		this.saleaddr = saleaddr;
	}

	@Column(name = "SEALEDDATE", length = 10)
	public String getSealeddate() {
		return this.sealeddate;
	}

	public void setSealeddate(String sealeddate) {
		this.sealeddate = sealeddate;
	}

	@Column(name = "SHOWORDER", precision = 38, scale = 0)
	public BigDecimal getShoworder() {
		return this.showorder;
	}

	public void setShoworder(BigDecimal showorder) {
		this.showorder = showorder;
	}

	@Column(name = "TAXCODE", length = 20)
	public String getTaxcode() {
		return this.taxcode;
	}

	public void setTaxcode(String taxcode) {
		this.taxcode = taxcode;
	}

	@Column(name = "TAXPAYERTYPE", precision = 38, scale = 0)
	public BigDecimal getTaxpayertype() {
		return this.taxpayertype;
	}

	public void setTaxpayertype(BigDecimal taxpayertype) {
		this.taxpayertype = taxpayertype;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "UNITCODE", unique = true, nullable = false, length = 40)
	public String getUnitcode() {
		return this.unitcode;
	}

	public void setUnitcode(String unitcode) {
		this.unitcode = unitcode;
	}

	@Column(name = "UNITDISTINCTION", length = 20)
	public String getUnitdistinction() {
		return this.unitdistinction;
	}

	public void setUnitdistinction(String unitdistinction) {
		this.unitdistinction = unitdistinction;
	}

	@Column(name = "UNITNAME", unique = true, nullable = false, length = 200)
	public String getUnitname() {
		return this.unitname;
	}

	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	@Column(name = "UNITSHORTNAME", nullable = false, length = 40)
	public String getUnitshortname() {
		return this.unitshortname;
	}

	public void setUnitshortname(String unitshortname) {
		this.unitshortname = unitshortname;
	}

	@Column(name = "URL", length = 60)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ZIPCODE", length = 6)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}
