package com.nts.teststruts.model;
// Generated 2015-8-21 13:50:37 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BdDeptdoc generated by hbm2java
 */
@Entity
@Table(name = "BD_DEPTDOC", schema = "NC58", uniqueConstraints = @UniqueConstraint(columnNames = { "PK_CORP",
		"DEPTCODE" }) )
public class BdDeptdoc implements java.io.Serializable {

	private String pkDeptdoc;
	private String addr;
	private String canceldate;
	private char canceled;
	private String createdate;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private String deptattr;
	private String deptcode;
	private String deptduty;
	private String deptlevel;
	private String deptname;
	private String deptshortname;
	private BigDecimal depttype;
	private Long dr;
	private char hrcanceled;
	private String innercode;
	private char isuseretail;
	private String maxinnercode;
	private String memo;
	private BigDecimal orgtype;
	private String phone;
	private String pkCalbody;
	private String pkCorp;
	private String pkFathedept;
	private String pkPsndoc;
	private String pkPsndoc2;
	private String pkPsndoc3;
	private String remcode;
	private String resposition;
	private BigDecimal showorder;
	private String ts;
	private BigDecimal xtersysflag;

	public BdDeptdoc() {
	}

	public BdDeptdoc(String pkDeptdoc, char canceled, String deptattr, String deptcode, String deptname,
			char hrcanceled, char isuseretail, String pkCorp) {
		this.pkDeptdoc = pkDeptdoc;
		this.canceled = canceled;
		this.deptattr = deptattr;
		this.deptcode = deptcode;
		this.deptname = deptname;
		this.hrcanceled = hrcanceled;
		this.isuseretail = isuseretail;
		this.pkCorp = pkCorp;
	}

	public BdDeptdoc(String pkDeptdoc, String addr, String canceldate, char canceled, String createdate, String def1,
			String def10, String def11, String def12, String def13, String def14, String def15, String def16,
			String def17, String def18, String def19, String def2, String def20, String def3, String def4, String def5,
			String def6, String def7, String def8, String def9, String deptattr, String deptcode, String deptduty,
			String deptlevel, String deptname, String deptshortname, BigDecimal depttype, Long dr, char hrcanceled,
			String innercode, char isuseretail, String maxinnercode, String memo, BigDecimal orgtype, String phone,
			String pkCalbody, String pkCorp, String pkFathedept, String pkPsndoc, String pkPsndoc2, String pkPsndoc3,
			String remcode, String resposition, BigDecimal showorder, String ts, BigDecimal xtersysflag) {
		this.pkDeptdoc = pkDeptdoc;
		this.addr = addr;
		this.canceldate = canceldate;
		this.canceled = canceled;
		this.createdate = createdate;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def3 = def3;
		this.def4 = def4;
		this.def5 = def5;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.deptattr = deptattr;
		this.deptcode = deptcode;
		this.deptduty = deptduty;
		this.deptlevel = deptlevel;
		this.deptname = deptname;
		this.deptshortname = deptshortname;
		this.depttype = depttype;
		this.dr = dr;
		this.hrcanceled = hrcanceled;
		this.innercode = innercode;
		this.isuseretail = isuseretail;
		this.maxinnercode = maxinnercode;
		this.memo = memo;
		this.orgtype = orgtype;
		this.phone = phone;
		this.pkCalbody = pkCalbody;
		this.pkCorp = pkCorp;
		this.pkFathedept = pkFathedept;
		this.pkPsndoc = pkPsndoc;
		this.pkPsndoc2 = pkPsndoc2;
		this.pkPsndoc3 = pkPsndoc3;
		this.remcode = remcode;
		this.resposition = resposition;
		this.showorder = showorder;
		this.ts = ts;
		this.xtersysflag = xtersysflag;
	}

	@Id

	@Column(name = "PK_DEPTDOC", unique = true, nullable = false, length = 20)
	public String getPkDeptdoc() {
		return this.pkDeptdoc;
	}

	public void setPkDeptdoc(String pkDeptdoc) {
		this.pkDeptdoc = pkDeptdoc;
	}

	@Column(name = "ADDR", length = 60)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "CANCELDATE", length = 10)
	public String getCanceldate() {
		return this.canceldate;
	}

	public void setCanceldate(String canceldate) {
		this.canceldate = canceldate;
	}

	@Column(name = "CANCELED", nullable = false, length = 1)
	public char getCanceled() {
		return this.canceled;
	}

	public void setCanceled(char canceled) {
		this.canceled = canceled;
	}

	@Column(name = "CREATEDATE", length = 10)
	public String getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	@Column(name = "DEF1", length = 100)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 100)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 100)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 100)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 100)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 100)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 100)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 100)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 100)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 100)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 100)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 100)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 100)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF3", length = 100)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF4", length = 100)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF5", length = 100)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF6", length = 100)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 100)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 100)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 100)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DEPTATTR", nullable = false, length = 8)
	public String getDeptattr() {
		return this.deptattr;
	}

	public void setDeptattr(String deptattr) {
		this.deptattr = deptattr;
	}

	@Column(name = "DEPTCODE", nullable = false, length = 40)
	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Column(name = "DEPTDUTY", length = 1000)
	public String getDeptduty() {
		return this.deptduty;
	}

	public void setDeptduty(String deptduty) {
		this.deptduty = deptduty;
	}

	@Column(name = "DEPTLEVEL", length = 20)
	public String getDeptlevel() {
		return this.deptlevel;
	}

	public void setDeptlevel(String deptlevel) {
		this.deptlevel = deptlevel;
	}

	@Column(name = "DEPTNAME", nullable = false, length = 200)
	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	@Column(name = "DEPTSHORTNAME", length = 200)
	public String getDeptshortname() {
		return this.deptshortname;
	}

	public void setDeptshortname(String deptshortname) {
		this.deptshortname = deptshortname;
	}

	@Column(name = "DEPTTYPE", precision = 38, scale = 0)
	public BigDecimal getDepttype() {
		return this.depttype;
	}

	public void setDepttype(BigDecimal depttype) {
		this.depttype = depttype;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "HRCANCELED", nullable = false, length = 1)
	public char getHrcanceled() {
		return this.hrcanceled;
	}

	public void setHrcanceled(char hrcanceled) {
		this.hrcanceled = hrcanceled;
	}

	@Column(name = "INNERCODE", length = 60)
	public String getInnercode() {
		return this.innercode;
	}

	public void setInnercode(String innercode) {
		this.innercode = innercode;
	}

	@Column(name = "ISUSERETAIL", nullable = false, length = 1)
	public char getIsuseretail() {
		return this.isuseretail;
	}

	public void setIsuseretail(char isuseretail) {
		this.isuseretail = isuseretail;
	}

	@Column(name = "MAXINNERCODE", length = 60)
	public String getMaxinnercode() {
		return this.maxinnercode;
	}

	public void setMaxinnercode(String maxinnercode) {
		this.maxinnercode = maxinnercode;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "ORGTYPE", precision = 38, scale = 0)
	public BigDecimal getOrgtype() {
		return this.orgtype;
	}

	public void setOrgtype(BigDecimal orgtype) {
		this.orgtype = orgtype;
	}

	@Column(name = "PHONE", length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "PK_CALBODY", length = 20)
	public String getPkCalbody() {
		return this.pkCalbody;
	}

	public void setPkCalbody(String pkCalbody) {
		this.pkCalbody = pkCalbody;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_FATHEDEPT", length = 20)
	public String getPkFathedept() {
		return this.pkFathedept;
	}

	public void setPkFathedept(String pkFathedept) {
		this.pkFathedept = pkFathedept;
	}

	@Column(name = "PK_PSNDOC", length = 20)
	public String getPkPsndoc() {
		return this.pkPsndoc;
	}

	public void setPkPsndoc(String pkPsndoc) {
		this.pkPsndoc = pkPsndoc;
	}

	@Column(name = "PK_PSNDOC2", length = 20)
	public String getPkPsndoc2() {
		return this.pkPsndoc2;
	}

	public void setPkPsndoc2(String pkPsndoc2) {
		this.pkPsndoc2 = pkPsndoc2;
	}

	@Column(name = "PK_PSNDOC3", length = 20)
	public String getPkPsndoc3() {
		return this.pkPsndoc3;
	}

	public void setPkPsndoc3(String pkPsndoc3) {
		this.pkPsndoc3 = pkPsndoc3;
	}

	@Column(name = "REMCODE", length = 50)
	public String getRemcode() {
		return this.remcode;
	}

	public void setRemcode(String remcode) {
		this.remcode = remcode;
	}

	@Column(name = "RESPOSITION", length = 20)
	public String getResposition() {
		return this.resposition;
	}

	public void setResposition(String resposition) {
		this.resposition = resposition;
	}

	@Column(name = "SHOWORDER", precision = 38, scale = 0)
	public BigDecimal getShoworder() {
		return this.showorder;
	}

	public void setShoworder(BigDecimal showorder) {
		this.showorder = showorder;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "XTERSYSFLAG", precision = 38, scale = 0)
	public BigDecimal getXtersysflag() {
		return this.xtersysflag;
	}

	public void setXtersysflag(BigDecimal xtersysflag) {
		this.xtersysflag = xtersysflag;
	}

}
