package com.nts.teststruts.model;
// Generated 2015-8-21 13:50:37 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BdDefdoclist generated by hbm2java
 */
@Entity
@Table(name = "BD_DEFDOCLIST", schema = "NC58", uniqueConstraints = @UniqueConstraint(columnNames = "DOCLISTCODE") )
public class BdDefdoclist implements java.io.Serializable {

	private String pkDefdoclist;
	private char docislevflag;
	private String doclistcode;
	private String doclistname;
	private BigDecimal doclistsystype;
	private Long dr;
	private Character iscorpcanchg;
	private String ts;

	public BdDefdoclist() {
	}

	public BdDefdoclist(String pkDefdoclist, char docislevflag, String doclistcode, String doclistname,
			BigDecimal doclistsystype) {
		this.pkDefdoclist = pkDefdoclist;
		this.docislevflag = docislevflag;
		this.doclistcode = doclistcode;
		this.doclistname = doclistname;
		this.doclistsystype = doclistsystype;
	}

	public BdDefdoclist(String pkDefdoclist, char docislevflag, String doclistcode, String doclistname,
			BigDecimal doclistsystype, Long dr, Character iscorpcanchg, String ts) {
		this.pkDefdoclist = pkDefdoclist;
		this.docislevflag = docislevflag;
		this.doclistcode = doclistcode;
		this.doclistname = doclistname;
		this.doclistsystype = doclistsystype;
		this.dr = dr;
		this.iscorpcanchg = iscorpcanchg;
		this.ts = ts;
	}

	@Id

	@Column(name = "PK_DEFDOCLIST", unique = true, nullable = false, length = 20)
	public String getPkDefdoclist() {
		return this.pkDefdoclist;
	}

	public void setPkDefdoclist(String pkDefdoclist) {
		this.pkDefdoclist = pkDefdoclist;
	}

	@Column(name = "DOCISLEVFLAG", nullable = false, length = 1)
	public char getDocislevflag() {
		return this.docislevflag;
	}

	public void setDocislevflag(char docislevflag) {
		this.docislevflag = docislevflag;
	}

	@Column(name = "DOCLISTCODE", unique = true, nullable = false, length = 40)
	public String getDoclistcode() {
		return this.doclistcode;
	}

	public void setDoclistcode(String doclistcode) {
		this.doclistcode = doclistcode;
	}

	@Column(name = "DOCLISTNAME", nullable = false, length = 200)
	public String getDoclistname() {
		return this.doclistname;
	}

	public void setDoclistname(String doclistname) {
		this.doclistname = doclistname;
	}

	@Column(name = "DOCLISTSYSTYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getDoclistsystype() {
		return this.doclistsystype;
	}

	public void setDoclistsystype(BigDecimal doclistsystype) {
		this.doclistsystype = doclistsystype;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "ISCORPCANCHG", length = 1)
	public Character getIscorpcanchg() {
		return this.iscorpcanchg;
	}

	public void setIscorpcanchg(Character iscorpcanchg) {
		this.iscorpcanchg = iscorpcanchg;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

}
