package com.nts.teststruts.model;
// Generated 2015-8-21 13:50:37 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BdDefdoc generated by hbm2java
 */
@Entity
@Table(name = "BD_DEFDOC", schema = "NC58", uniqueConstraints = @UniqueConstraint(columnNames = { "DOCCODE",
		"PK_DEFDOCLIST", "PK_CORP" }) )
public class BdDefdoc implements java.io.Serializable {

	private String pkDefdoc;
	private String doccode;
	private String docname;
	private BigDecimal docsystype;
	private Long dr;
	private String memo;
	private String pkCorp;
	private String pkDefdoc1;
	private String pkDefdoclist;
	private Character sealflag;
	private String shortname;
	private String ts;

	public BdDefdoc() {
	}

	public BdDefdoc(String pkDefdoc) {
		this.pkDefdoc = pkDefdoc;
	}

	public BdDefdoc(String pkDefdoc, String doccode, String docname, BigDecimal docsystype, Long dr, String memo,
			String pkCorp, String pkDefdoc1, String pkDefdoclist, Character sealflag, String shortname, String ts) {
		this.pkDefdoc = pkDefdoc;
		this.doccode = doccode;
		this.docname = docname;
		this.docsystype = docsystype;
		this.dr = dr;
		this.memo = memo;
		this.pkCorp = pkCorp;
		this.pkDefdoc1 = pkDefdoc1;
		this.pkDefdoclist = pkDefdoclist;
		this.sealflag = sealflag;
		this.shortname = shortname;
		this.ts = ts;
	}

	@Id

	@Column(name = "PK_DEFDOC", unique = true, nullable = false, length = 20)
	public String getPkDefdoc() {
		return this.pkDefdoc;
	}

	public void setPkDefdoc(String pkDefdoc) {
		this.pkDefdoc = pkDefdoc;
	}

	@Column(name = "DOCCODE", length = 50)
	public String getDoccode() {
		return this.doccode;
	}

	public void setDoccode(String doccode) {
		this.doccode = doccode;
	}

	@Column(name = "DOCNAME", length = 200)
	public String getDocname() {
		return this.docname;
	}

	public void setDocname(String docname) {
		this.docname = docname;
	}

	@Column(name = "DOCSYSTYPE", precision = 38, scale = 0)
	public BigDecimal getDocsystype() {
		return this.docsystype;
	}

	public void setDocsystype(BigDecimal docsystype) {
		this.docsystype = docsystype;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "MEMO", length = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_DEFDOC1", length = 20)
	public String getPkDefdoc1() {
		return this.pkDefdoc1;
	}

	public void setPkDefdoc1(String pkDefdoc1) {
		this.pkDefdoc1 = pkDefdoc1;
	}

	@Column(name = "PK_DEFDOCLIST", length = 20)
	public String getPkDefdoclist() {
		return this.pkDefdoclist;
	}

	public void setPkDefdoclist(String pkDefdoclist) {
		this.pkDefdoclist = pkDefdoclist;
	}

	@Column(name = "SEALFLAG", length = 1)
	public Character getSealflag() {
		return this.sealflag;
	}

	public void setSealflag(Character sealflag) {
		this.sealflag = sealflag;
	}

	@Column(name = "SHORTNAME", length = 200)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

}
