package com.nts.teststruts.model;
// Generated 2015-7-24 10:07:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BdInvcl generated by hbm2java
 */
@Entity
@Table(name = "BD_INVCL", schema = "NC58", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "INVCLASSCODE", "PK_CORP" }),
		@UniqueConstraint(columnNames = { "INVCLASSNAME", "PK_CORP" }) })
public class BdInvcl implements java.io.Serializable {

	private String pkInvcl;
	private BigDecimal averagecost;
	private BigDecimal averagemmahead;
	private BigDecimal averagepurahead;
	private BigDecimal avgprice;
	private Long dr;
	private Character endflag;
	private String forinvname;
	private String invclasscode;
	private BigDecimal invclasslev;
	private String invclassname;
	private Character iselectrans;
	private String pkCorp;
	private String sealdate;
	private String ts;

	public BdInvcl() {
	}

	public BdInvcl(String pkInvcl, String invclasscode, BigDecimal invclasslev, String invclassname) {
		this.pkInvcl = pkInvcl;
		this.invclasscode = invclasscode;
		this.invclasslev = invclasslev;
		this.invclassname = invclassname;
	}

	public BdInvcl(String pkInvcl, BigDecimal averagecost, BigDecimal averagemmahead, BigDecimal averagepurahead,
			BigDecimal avgprice, Long dr, Character endflag, String forinvname, String invclasscode,
			BigDecimal invclasslev, String invclassname, Character iselectrans, String pkCorp, String sealdate,
			String ts) {
		this.pkInvcl = pkInvcl;
		this.averagecost = averagecost;
		this.averagemmahead = averagemmahead;
		this.averagepurahead = averagepurahead;
		this.avgprice = avgprice;
		this.dr = dr;
		this.endflag = endflag;
		this.forinvname = forinvname;
		this.invclasscode = invclasscode;
		this.invclasslev = invclasslev;
		this.invclassname = invclassname;
		this.iselectrans = iselectrans;
		this.pkCorp = pkCorp;
		this.sealdate = sealdate;
		this.ts = ts;
	}

	@Id

	@Column(name = "PK_INVCL", unique = true, nullable = false, length = 20)
	public String getPkInvcl() {
		return this.pkInvcl;
	}

	public void setPkInvcl(String pkInvcl) {
		this.pkInvcl = pkInvcl;
	}

	@Column(name = "AVERAGECOST", precision = 20, scale = 8)
	public BigDecimal getAveragecost() {
		return this.averagecost;
	}

	public void setAveragecost(BigDecimal averagecost) {
		this.averagecost = averagecost;
	}

	@Column(name = "AVERAGEMMAHEAD", precision = 38, scale = 0)
	public BigDecimal getAveragemmahead() {
		return this.averagemmahead;
	}

	public void setAveragemmahead(BigDecimal averagemmahead) {
		this.averagemmahead = averagemmahead;
	}

	@Column(name = "AVERAGEPURAHEAD", precision = 38, scale = 0)
	public BigDecimal getAveragepurahead() {
		return this.averagepurahead;
	}

	public void setAveragepurahead(BigDecimal averagepurahead) {
		this.averagepurahead = averagepurahead;
	}

	@Column(name = "AVGPRICE", precision = 20, scale = 8)
	public BigDecimal getAvgprice() {
		return this.avgprice;
	}

	public void setAvgprice(BigDecimal avgprice) {
		this.avgprice = avgprice;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "ENDFLAG", length = 1)
	public Character getEndflag() {
		return this.endflag;
	}

	public void setEndflag(Character endflag) {
		this.endflag = endflag;
	}

	@Column(name = "FORINVNAME", length = 240)
	public String getForinvname() {
		return this.forinvname;
	}

	public void setForinvname(String forinvname) {
		this.forinvname = forinvname;
	}

	@Column(name = "INVCLASSCODE", nullable = false, length = 50)
	public String getInvclasscode() {
		return this.invclasscode;
	}

	public void setInvclasscode(String invclasscode) {
		this.invclasscode = invclasscode;
	}

	@Column(name = "INVCLASSLEV", nullable = false, precision = 38, scale = 0)
	public BigDecimal getInvclasslev() {
		return this.invclasslev;
	}

	public void setInvclasslev(BigDecimal invclasslev) {
		this.invclasslev = invclasslev;
	}

	@Column(name = "INVCLASSNAME", nullable = false, length = 240)
	public String getInvclassname() {
		return this.invclassname;
	}

	public void setInvclassname(String invclassname) {
		this.invclassname = invclassname;
	}

	@Column(name = "ISELECTRANS", length = 1)
	public Character getIselectrans() {
		return this.iselectrans;
	}

	public void setIselectrans(Character iselectrans) {
		this.iselectrans = iselectrans;
	}

	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "SEALDATE", length = 10)
	public String getSealdate() {
		return this.sealdate;
	}

	public void setSealdate(String sealdate) {
		this.sealdate = sealdate;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

}
