package com.nts.teststruts.model;
// Generated 2015-7-24 10:07:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BdInvmandoc generated by hbm2java
 */
@Entity
@Table(name = "BD_INVMANDOC", schema = "NC58", uniqueConstraints = @UniqueConstraint(columnNames = { "PK_CORP",
		"PK_INVBASDOC" }) )
public class BdInvmandoc implements java.io.Serializable {

	private String pkInvmandoc;
	private BdInvbasdoc bdInvbasdoc;
	private Character abctype;
	private char accflag;
	private String cinvmnecode;
	private Character consumesettleflag;
	private String coopdayfrom;
	private String coopdayto;
	private BigDecimal costprice;
	private String createtime;
	private String creator;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private Long dr;
	private BigDecimal expaybacktax;
	private String free1;
	private String free2;
	private String free3;
	private String free4;
	private String free5;
	private BigDecimal grade;
	private BigDecimal invlifeperiod;
	private char isappendant;
	private Character isautoatpcheck;
	private Character iscancalculatedinvcost;
	private Character iscanpurchased;
	private Character iscansaleinvoice;
	private Character iscansold;
	private Character isconfigable;
	private String isctlprodplanprice;
	private Character isfatherofbom;
	private char isinvretfreeofchk;
	private char isinvretinstobychk;
	private Character isinvreturned;
	private Character isnoconallowed;
	private Character isprimarybarcode;
	private char isrecurrentcheck;
	private Character issalable;
	private Character issecondarybarcode;
	private Character isselfapprsupplier;
	private Character isspecialty;
	private Character issupplierstock;
	private Character isused;
	private Character isvirtual;
	private BigDecimal keepwasterate;
	private BigDecimal lowestprice;
	private String mantaxitem;
	private BigDecimal maxprice;
	private String memo;
	private String modifier;
	private String modifytime;
	private Character negallowed;
	private BigDecimal outpriority;
	private Character outtrackin;
	private String pebegin;
	private String peend;
	private String pkCorp;
	private String pkCumandoc;
	private String pkDftfactory;
	private String pkSealuser;
	private BigDecimal planprice;
	private String prodarea;
	private Character purchasestge;
	private BigDecimal purwasterate;
	private BigDecimal qualitydaynum;
	private Character qualitymanflag;
	private BigDecimal qualityperiodunit;
	private BigDecimal recurrentchkcyc;
	private BigDecimal refsaleprice;
	private String sealdate;
	private Character sealflag;
	private Character sellproxyflag;
	private Character serialmanaflag;
	private String ts;
	private Character wholemanaflag;

	public BdInvmandoc() {
	}

	public BdInvmandoc(String pkInvmandoc, BdInvbasdoc bdInvbasdoc, char accflag, BigDecimal invlifeperiod,
			char isappendant, char isinvretfreeofchk, char isinvretinstobychk, char isrecurrentcheck, String pkCorp) {
		this.pkInvmandoc = pkInvmandoc;
		this.bdInvbasdoc = bdInvbasdoc;
		this.accflag = accflag;
		this.invlifeperiod = invlifeperiod;
		this.isappendant = isappendant;
		this.isinvretfreeofchk = isinvretfreeofchk;
		this.isinvretinstobychk = isinvretinstobychk;
		this.isrecurrentcheck = isrecurrentcheck;
		this.pkCorp = pkCorp;
	}

	public BdInvmandoc(String pkInvmandoc, BdInvbasdoc bdInvbasdoc, Character abctype, char accflag, String cinvmnecode,
			Character consumesettleflag, String coopdayfrom, String coopdayto, BigDecimal costprice, String createtime,
			String creator, String def1, String def10, String def11, String def12, String def13, String def14,
			String def15, String def16, String def17, String def18, String def19, String def2, String def20,
			String def3, String def4, String def5, String def6, String def7, String def8, String def9, Long dr,
			BigDecimal expaybacktax, String free1, String free2, String free3, String free4, String free5,
			BigDecimal grade, BigDecimal invlifeperiod, char isappendant, Character isautoatpcheck,
			Character iscancalculatedinvcost, Character iscanpurchased, Character iscansaleinvoice, Character iscansold,
			Character isconfigable, String isctlprodplanprice, Character isfatherofbom, char isinvretfreeofchk,
			char isinvretinstobychk, Character isinvreturned, Character isnoconallowed, Character isprimarybarcode,
			char isrecurrentcheck, Character issalable, Character issecondarybarcode, Character isselfapprsupplier,
			Character isspecialty, Character issupplierstock, Character isused, Character isvirtual,
			BigDecimal keepwasterate, BigDecimal lowestprice, String mantaxitem, BigDecimal maxprice, String memo,
			String modifier, String modifytime, Character negallowed, BigDecimal outpriority, Character outtrackin,
			String pebegin, String peend, String pkCorp, String pkCumandoc, String pkDftfactory, String pkSealuser,
			BigDecimal planprice, String prodarea, Character purchasestge, BigDecimal purwasterate,
			BigDecimal qualitydaynum, Character qualitymanflag, BigDecimal qualityperiodunit,
			BigDecimal recurrentchkcyc, BigDecimal refsaleprice, String sealdate, Character sealflag,
			Character sellproxyflag, Character serialmanaflag, String ts, Character wholemanaflag) {
		this.pkInvmandoc = pkInvmandoc;
		this.bdInvbasdoc = bdInvbasdoc;
		this.abctype = abctype;
		this.accflag = accflag;
		this.cinvmnecode = cinvmnecode;
		this.consumesettleflag = consumesettleflag;
		this.coopdayfrom = coopdayfrom;
		this.coopdayto = coopdayto;
		this.costprice = costprice;
		this.createtime = createtime;
		this.creator = creator;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def3 = def3;
		this.def4 = def4;
		this.def5 = def5;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.dr = dr;
		this.expaybacktax = expaybacktax;
		this.free1 = free1;
		this.free2 = free2;
		this.free3 = free3;
		this.free4 = free4;
		this.free5 = free5;
		this.grade = grade;
		this.invlifeperiod = invlifeperiod;
		this.isappendant = isappendant;
		this.isautoatpcheck = isautoatpcheck;
		this.iscancalculatedinvcost = iscancalculatedinvcost;
		this.iscanpurchased = iscanpurchased;
		this.iscansaleinvoice = iscansaleinvoice;
		this.iscansold = iscansold;
		this.isconfigable = isconfigable;
		this.isctlprodplanprice = isctlprodplanprice;
		this.isfatherofbom = isfatherofbom;
		this.isinvretfreeofchk = isinvretfreeofchk;
		this.isinvretinstobychk = isinvretinstobychk;
		this.isinvreturned = isinvreturned;
		this.isnoconallowed = isnoconallowed;
		this.isprimarybarcode = isprimarybarcode;
		this.isrecurrentcheck = isrecurrentcheck;
		this.issalable = issalable;
		this.issecondarybarcode = issecondarybarcode;
		this.isselfapprsupplier = isselfapprsupplier;
		this.isspecialty = isspecialty;
		this.issupplierstock = issupplierstock;
		this.isused = isused;
		this.isvirtual = isvirtual;
		this.keepwasterate = keepwasterate;
		this.lowestprice = lowestprice;
		this.mantaxitem = mantaxitem;
		this.maxprice = maxprice;
		this.memo = memo;
		this.modifier = modifier;
		this.modifytime = modifytime;
		this.negallowed = negallowed;
		this.outpriority = outpriority;
		this.outtrackin = outtrackin;
		this.pebegin = pebegin;
		this.peend = peend;
		this.pkCorp = pkCorp;
		this.pkCumandoc = pkCumandoc;
		this.pkDftfactory = pkDftfactory;
		this.pkSealuser = pkSealuser;
		this.planprice = planprice;
		this.prodarea = prodarea;
		this.purchasestge = purchasestge;
		this.purwasterate = purwasterate;
		this.qualitydaynum = qualitydaynum;
		this.qualitymanflag = qualitymanflag;
		this.qualityperiodunit = qualityperiodunit;
		this.recurrentchkcyc = recurrentchkcyc;
		this.refsaleprice = refsaleprice;
		this.sealdate = sealdate;
		this.sealflag = sealflag;
		this.sellproxyflag = sellproxyflag;
		this.serialmanaflag = serialmanaflag;
		this.ts = ts;
		this.wholemanaflag = wholemanaflag;
	}

	@Id

	@Column(name = "PK_INVMANDOC", unique = true, nullable = false, length = 20)
	public String getPkInvmandoc() {
		return this.pkInvmandoc;
	}

	public void setPkInvmandoc(String pkInvmandoc) {
		this.pkInvmandoc = pkInvmandoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PK_INVBASDOC", nullable = false)
	public BdInvbasdoc getBdInvbasdoc() {
		return this.bdInvbasdoc;
	}

	public void setBdInvbasdoc(BdInvbasdoc bdInvbasdoc) {
		this.bdInvbasdoc = bdInvbasdoc;
	}

	@Column(name = "ABCTYPE", length = 1)
	public Character getAbctype() {
		return this.abctype;
	}

	public void setAbctype(Character abctype) {
		this.abctype = abctype;
	}

	@Column(name = "ACCFLAG", nullable = false, length = 1)
	public char getAccflag() {
		return this.accflag;
	}

	public void setAccflag(char accflag) {
		this.accflag = accflag;
	}

	@Column(name = "CINVMNECODE", length = 8)
	public String getCinvmnecode() {
		return this.cinvmnecode;
	}

	public void setCinvmnecode(String cinvmnecode) {
		this.cinvmnecode = cinvmnecode;
	}

	@Column(name = "CONSUMESETTLEFLAG", length = 1)
	public Character getConsumesettleflag() {
		return this.consumesettleflag;
	}

	public void setConsumesettleflag(Character consumesettleflag) {
		this.consumesettleflag = consumesettleflag;
	}

	@Column(name = "COOPDAYFROM", length = 10)
	public String getCoopdayfrom() {
		return this.coopdayfrom;
	}

	public void setCoopdayfrom(String coopdayfrom) {
		this.coopdayfrom = coopdayfrom;
	}

	@Column(name = "COOPDAYTO", length = 10)
	public String getCoopdayto() {
		return this.coopdayto;
	}

	public void setCoopdayto(String coopdayto) {
		this.coopdayto = coopdayto;
	}

	@Column(name = "COSTPRICE", precision = 20, scale = 8)
	public BigDecimal getCostprice() {
		return this.costprice;
	}

	public void setCostprice(BigDecimal costprice) {
		this.costprice = costprice;
	}

	@Column(name = "CREATETIME", length = 19)
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "DEF1", length = 100)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 100)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 100)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 100)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 100)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 100)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 100)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 100)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 100)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 100)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 100)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 100)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 100)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF3", length = 100)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF4", length = 100)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF5", length = 100)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF6", length = 100)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 100)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 100)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 100)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "EXPAYBACKTAX", precision = 15, scale = 8)
	public BigDecimal getExpaybacktax() {
		return this.expaybacktax;
	}

	public void setExpaybacktax(BigDecimal expaybacktax) {
		this.expaybacktax = expaybacktax;
	}

	@Column(name = "FREE1", length = 20)
	public String getFree1() {
		return this.free1;
	}

	public void setFree1(String free1) {
		this.free1 = free1;
	}

	@Column(name = "FREE2", length = 20)
	public String getFree2() {
		return this.free2;
	}

	public void setFree2(String free2) {
		this.free2 = free2;
	}

	@Column(name = "FREE3", length = 20)
	public String getFree3() {
		return this.free3;
	}

	public void setFree3(String free3) {
		this.free3 = free3;
	}

	@Column(name = "FREE4", length = 20)
	public String getFree4() {
		return this.free4;
	}

	public void setFree4(String free4) {
		this.free4 = free4;
	}

	@Column(name = "FREE5", length = 20)
	public String getFree5() {
		return this.free5;
	}

	public void setFree5(String free5) {
		this.free5 = free5;
	}

	@Column(name = "GRADE", precision = 38, scale = 0)
	public BigDecimal getGrade() {
		return this.grade;
	}

	public void setGrade(BigDecimal grade) {
		this.grade = grade;
	}

	@Column(name = "INVLIFEPERIOD", nullable = false, precision = 38, scale = 0)
	public BigDecimal getInvlifeperiod() {
		return this.invlifeperiod;
	}

	public void setInvlifeperiod(BigDecimal invlifeperiod) {
		this.invlifeperiod = invlifeperiod;
	}

	@Column(name = "ISAPPENDANT", nullable = false, length = 1)
	public char getIsappendant() {
		return this.isappendant;
	}

	public void setIsappendant(char isappendant) {
		this.isappendant = isappendant;
	}

	@Column(name = "ISAUTOATPCHECK", length = 1)
	public Character getIsautoatpcheck() {
		return this.isautoatpcheck;
	}

	public void setIsautoatpcheck(Character isautoatpcheck) {
		this.isautoatpcheck = isautoatpcheck;
	}

	@Column(name = "ISCANCALCULATEDINVCOST", length = 1)
	public Character getIscancalculatedinvcost() {
		return this.iscancalculatedinvcost;
	}

	public void setIscancalculatedinvcost(Character iscancalculatedinvcost) {
		this.iscancalculatedinvcost = iscancalculatedinvcost;
	}

	@Column(name = "ISCANPURCHASED", length = 1)
	public Character getIscanpurchased() {
		return this.iscanpurchased;
	}

	public void setIscanpurchased(Character iscanpurchased) {
		this.iscanpurchased = iscanpurchased;
	}

	@Column(name = "ISCANSALEINVOICE", length = 1)
	public Character getIscansaleinvoice() {
		return this.iscansaleinvoice;
	}

	public void setIscansaleinvoice(Character iscansaleinvoice) {
		this.iscansaleinvoice = iscansaleinvoice;
	}

	@Column(name = "ISCANSOLD", length = 1)
	public Character getIscansold() {
		return this.iscansold;
	}

	public void setIscansold(Character iscansold) {
		this.iscansold = iscansold;
	}

	@Column(name = "ISCONFIGABLE", length = 1)
	public Character getIsconfigable() {
		return this.isconfigable;
	}

	public void setIsconfigable(Character isconfigable) {
		this.isconfigable = isconfigable;
	}

	@Column(name = "ISCTLPRODPLANPRICE", length = 1)
	public String getIsctlprodplanprice() {
		return this.isctlprodplanprice;
	}

	public void setIsctlprodplanprice(String isctlprodplanprice) {
		this.isctlprodplanprice = isctlprodplanprice;
	}

	@Column(name = "ISFATHEROFBOM", length = 1)
	public Character getIsfatherofbom() {
		return this.isfatherofbom;
	}

	public void setIsfatherofbom(Character isfatherofbom) {
		this.isfatherofbom = isfatherofbom;
	}

	@Column(name = "ISINVRETFREEOFCHK", nullable = false, length = 1)
	public char getIsinvretfreeofchk() {
		return this.isinvretfreeofchk;
	}

	public void setIsinvretfreeofchk(char isinvretfreeofchk) {
		this.isinvretfreeofchk = isinvretfreeofchk;
	}

	@Column(name = "ISINVRETINSTOBYCHK", nullable = false, length = 1)
	public char getIsinvretinstobychk() {
		return this.isinvretinstobychk;
	}

	public void setIsinvretinstobychk(char isinvretinstobychk) {
		this.isinvretinstobychk = isinvretinstobychk;
	}

	@Column(name = "ISINVRETURNED", length = 1)
	public Character getIsinvreturned() {
		return this.isinvreturned;
	}

	public void setIsinvreturned(Character isinvreturned) {
		this.isinvreturned = isinvreturned;
	}

	@Column(name = "ISNOCONALLOWED", length = 1)
	public Character getIsnoconallowed() {
		return this.isnoconallowed;
	}

	public void setIsnoconallowed(Character isnoconallowed) {
		this.isnoconallowed = isnoconallowed;
	}

	@Column(name = "ISPRIMARYBARCODE", length = 1)
	public Character getIsprimarybarcode() {
		return this.isprimarybarcode;
	}

	public void setIsprimarybarcode(Character isprimarybarcode) {
		this.isprimarybarcode = isprimarybarcode;
	}

	@Column(name = "ISRECURRENTCHECK", nullable = false, length = 1)
	public char getIsrecurrentcheck() {
		return this.isrecurrentcheck;
	}

	public void setIsrecurrentcheck(char isrecurrentcheck) {
		this.isrecurrentcheck = isrecurrentcheck;
	}

	@Column(name = "ISSALABLE", length = 1)
	public Character getIssalable() {
		return this.issalable;
	}

	public void setIssalable(Character issalable) {
		this.issalable = issalable;
	}

	@Column(name = "ISSECONDARYBARCODE", length = 1)
	public Character getIssecondarybarcode() {
		return this.issecondarybarcode;
	}

	public void setIssecondarybarcode(Character issecondarybarcode) {
		this.issecondarybarcode = issecondarybarcode;
	}

	@Column(name = "ISSELFAPPRSUPPLIER", length = 1)
	public Character getIsselfapprsupplier() {
		return this.isselfapprsupplier;
	}

	public void setIsselfapprsupplier(Character isselfapprsupplier) {
		this.isselfapprsupplier = isselfapprsupplier;
	}

	@Column(name = "ISSPECIALTY", length = 1)
	public Character getIsspecialty() {
		return this.isspecialty;
	}

	public void setIsspecialty(Character isspecialty) {
		this.isspecialty = isspecialty;
	}

	@Column(name = "ISSUPPLIERSTOCK", length = 1)
	public Character getIssupplierstock() {
		return this.issupplierstock;
	}

	public void setIssupplierstock(Character issupplierstock) {
		this.issupplierstock = issupplierstock;
	}

	@Column(name = "ISUSED", length = 1)
	public Character getIsused() {
		return this.isused;
	}

	public void setIsused(Character isused) {
		this.isused = isused;
	}

	@Column(name = "ISVIRTUAL", length = 1)
	public Character getIsvirtual() {
		return this.isvirtual;
	}

	public void setIsvirtual(Character isvirtual) {
		this.isvirtual = isvirtual;
	}

	@Column(name = "KEEPWASTERATE", precision = 20, scale = 8)
	public BigDecimal getKeepwasterate() {
		return this.keepwasterate;
	}

	public void setKeepwasterate(BigDecimal keepwasterate) {
		this.keepwasterate = keepwasterate;
	}

	@Column(name = "LOWESTPRICE", precision = 20, scale = 8)
	public BigDecimal getLowestprice() {
		return this.lowestprice;
	}

	public void setLowestprice(BigDecimal lowestprice) {
		this.lowestprice = lowestprice;
	}

	@Column(name = "MANTAXITEM", length = 20)
	public String getMantaxitem() {
		return this.mantaxitem;
	}

	public void setMantaxitem(String mantaxitem) {
		this.mantaxitem = mantaxitem;
	}

	@Column(name = "MAXPRICE", precision = 20, scale = 8)
	public BigDecimal getMaxprice() {
		return this.maxprice;
	}

	public void setMaxprice(BigDecimal maxprice) {
		this.maxprice = maxprice;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Column(name = "MODIFYTIME", length = 19)
	public String getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(String modifytime) {
		this.modifytime = modifytime;
	}

	@Column(name = "NEGALLOWED", length = 1)
	public Character getNegallowed() {
		return this.negallowed;
	}

	public void setNegallowed(Character negallowed) {
		this.negallowed = negallowed;
	}

	@Column(name = "OUTPRIORITY", precision = 38, scale = 0)
	public BigDecimal getOutpriority() {
		return this.outpriority;
	}

	public void setOutpriority(BigDecimal outpriority) {
		this.outpriority = outpriority;
	}

	@Column(name = "OUTTRACKIN", length = 1)
	public Character getOuttrackin() {
		return this.outtrackin;
	}

	public void setOuttrackin(Character outtrackin) {
		this.outtrackin = outtrackin;
	}

	@Column(name = "PEBEGIN", length = 10)
	public String getPebegin() {
		return this.pebegin;
	}

	public void setPebegin(String pebegin) {
		this.pebegin = pebegin;
	}

	@Column(name = "PEEND", length = 10)
	public String getPeend() {
		return this.peend;
	}

	public void setPeend(String peend) {
		this.peend = peend;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_CUMANDOC", length = 20)
	public String getPkCumandoc() {
		return this.pkCumandoc;
	}

	public void setPkCumandoc(String pkCumandoc) {
		this.pkCumandoc = pkCumandoc;
	}

	@Column(name = "PK_DFTFACTORY", length = 20)
	public String getPkDftfactory() {
		return this.pkDftfactory;
	}

	public void setPkDftfactory(String pkDftfactory) {
		this.pkDftfactory = pkDftfactory;
	}

	@Column(name = "PK_SEALUSER", length = 20)
	public String getPkSealuser() {
		return this.pkSealuser;
	}

	public void setPkSealuser(String pkSealuser) {
		this.pkSealuser = pkSealuser;
	}

	@Column(name = "PLANPRICE", precision = 20, scale = 8)
	public BigDecimal getPlanprice() {
		return this.planprice;
	}

	public void setPlanprice(BigDecimal planprice) {
		this.planprice = planprice;
	}

	@Column(name = "PRODAREA", length = 30)
	public String getProdarea() {
		return this.prodarea;
	}

	public void setProdarea(String prodarea) {
		this.prodarea = prodarea;
	}

	@Column(name = "PURCHASESTGE", length = 1)
	public Character getPurchasestge() {
		return this.purchasestge;
	}

	public void setPurchasestge(Character purchasestge) {
		this.purchasestge = purchasestge;
	}

	@Column(name = "PURWASTERATE", precision = 20, scale = 8)
	public BigDecimal getPurwasterate() {
		return this.purwasterate;
	}

	public void setPurwasterate(BigDecimal purwasterate) {
		this.purwasterate = purwasterate;
	}

	@Column(name = "QUALITYDAYNUM", precision = 38, scale = 0)
	public BigDecimal getQualitydaynum() {
		return this.qualitydaynum;
	}

	public void setQualitydaynum(BigDecimal qualitydaynum) {
		this.qualitydaynum = qualitydaynum;
	}

	@Column(name = "QUALITYMANFLAG", length = 1)
	public Character getQualitymanflag() {
		return this.qualitymanflag;
	}

	public void setQualitymanflag(Character qualitymanflag) {
		this.qualitymanflag = qualitymanflag;
	}

	@Column(name = "QUALITYPERIODUNIT", precision = 38, scale = 0)
	public BigDecimal getQualityperiodunit() {
		return this.qualityperiodunit;
	}

	public void setQualityperiodunit(BigDecimal qualityperiodunit) {
		this.qualityperiodunit = qualityperiodunit;
	}

	@Column(name = "RECURRENTCHKCYC", precision = 38, scale = 0)
	public BigDecimal getRecurrentchkcyc() {
		return this.recurrentchkcyc;
	}

	public void setRecurrentchkcyc(BigDecimal recurrentchkcyc) {
		this.recurrentchkcyc = recurrentchkcyc;
	}

	@Column(name = "REFSALEPRICE", precision = 20, scale = 8)
	public BigDecimal getRefsaleprice() {
		return this.refsaleprice;
	}

	public void setRefsaleprice(BigDecimal refsaleprice) {
		this.refsaleprice = refsaleprice;
	}

	@Column(name = "SEALDATE", length = 10)
	public String getSealdate() {
		return this.sealdate;
	}

	public void setSealdate(String sealdate) {
		this.sealdate = sealdate;
	}

	@Column(name = "SEALFLAG", length = 1)
	public Character getSealflag() {
		return this.sealflag;
	}

	public void setSealflag(Character sealflag) {
		this.sealflag = sealflag;
	}

	@Column(name = "SELLPROXYFLAG", length = 1)
	public Character getSellproxyflag() {
		return this.sellproxyflag;
	}

	public void setSellproxyflag(Character sellproxyflag) {
		this.sellproxyflag = sellproxyflag;
	}

	@Column(name = "SERIALMANAFLAG", length = 1)
	public Character getSerialmanaflag() {
		return this.serialmanaflag;
	}

	public void setSerialmanaflag(Character serialmanaflag) {
		this.serialmanaflag = serialmanaflag;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "WHOLEMANAFLAG", length = 1)
	public Character getWholemanaflag() {
		return this.wholemanaflag;
	}

	public void setWholemanaflag(Character wholemanaflag) {
		this.wholemanaflag = wholemanaflag;
	}

}
