package com.nts.teststruts.model;
// Generated 2015-7-24 10:07:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BdInvbasdoc generated by hbm2java
 */
@Entity
@Table(name = "BD_INVBASDOC", schema = "NC58", uniqueConstraints = @UniqueConstraint(columnNames = { "INVCODE",
		"PK_CORP" }) )
public class BdInvbasdoc implements java.io.Serializable {

	private String pkInvbasdoc;
	private Character asset;
	private char assistunit;
	private Character autobalancemeas;
	private String createtime;
	private String creator;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private Character discountflag;
	private Long dr;
	private String forinvname;
	private String free1;
	private String free2;
	private String free3;
	private String free4;
	private String free5;
	private String graphid;
	private String height;
	private String invbarcode;
	private String invcode;
	private String invmnecode;
	private String invname;
	private String invpinpai;
	private String invshortname;
	private String invspec;
	private String invtype;
	private Character iselectrans;
	private Character ismngstockbygrswt;
	private Character isretail;
	private Character isstorebyconvert;
	private Character laborflag;
	private String length;
	private String memo;
	private String modifier;
	private String modifytime;
	private String pkAssetcategory;
	private String pkCorp;
	private String pkInvcl;
	private String pkMeasdoc;
	private String pkMeasdoc1;
	private String pkMeasdoc2;
	private String pkMeasdoc3;
	private String pkMeasdoc5;
	private String pkMeasdoc6;
	private String pkProdline;
	private String pkTaxitems;
	private String sealflag;
	private Character setpartsflag;
	private BigDecimal shipunitnum;
	private BigDecimal storeunitnum;
	private String ts;
	private BigDecimal unitvolume;
	private BigDecimal unitweight;
	private BigDecimal weitunitnum;
	private String width;
	private String def21;
	private String def22;
	private String def23;
	private String def24;
	private String def25;
	private String def26;
	private String def27;
	private String def28;
	private String def29;
	private String def30;
	private Set bdInvmandocs = new HashSet(0);

	public BdInvbasdoc() {
	}

	public BdInvbasdoc(String pkInvbasdoc, char assistunit, String invcode, String invname, String pkCorp,
			String pkInvcl, String pkMeasdoc) {
		this.pkInvbasdoc = pkInvbasdoc;
		this.assistunit = assistunit;
		this.invcode = invcode;
		this.invname = invname;
		this.pkCorp = pkCorp;
		this.pkInvcl = pkInvcl;
		this.pkMeasdoc = pkMeasdoc;
	}

	public BdInvbasdoc(String pkInvbasdoc, Character asset, char assistunit, Character autobalancemeas,
			String createtime, String creator, String def1, String def10, String def11, String def12, String def13,
			String def14, String def15, String def16, String def17, String def18, String def19, String def2,
			String def20, String def3, String def4, String def5, String def6, String def7, String def8, String def9,
			Character discountflag, Long dr, String forinvname, String free1, String free2, String free3, String free4,
			String free5, String graphid, String height, String invbarcode, String invcode, String invmnecode,
			String invname, String invpinpai, String invshortname, String invspec, String invtype,
			Character iselectrans, Character ismngstockbygrswt, Character isretail, Character isstorebyconvert,
			Character laborflag, String length, String memo, String modifier, String modifytime, String pkAssetcategory,
			String pkCorp, String pkInvcl, String pkMeasdoc, String pkMeasdoc1, String pkMeasdoc2, String pkMeasdoc3,
			String pkMeasdoc5, String pkMeasdoc6, String pkProdline, String pkTaxitems, String sealflag,
			Character setpartsflag, BigDecimal shipunitnum, BigDecimal storeunitnum, String ts, BigDecimal unitvolume,
			BigDecimal unitweight, BigDecimal weitunitnum, String width, String def21, String def22, String def23,
			String def24, String def25, String def26, String def27, String def28, String def29, String def30,
			Set bdInvmandocs) {
		this.pkInvbasdoc = pkInvbasdoc;
		this.asset = asset;
		this.assistunit = assistunit;
		this.autobalancemeas = autobalancemeas;
		this.createtime = createtime;
		this.creator = creator;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def3 = def3;
		this.def4 = def4;
		this.def5 = def5;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.discountflag = discountflag;
		this.dr = dr;
		this.forinvname = forinvname;
		this.free1 = free1;
		this.free2 = free2;
		this.free3 = free3;
		this.free4 = free4;
		this.free5 = free5;
		this.graphid = graphid;
		this.height = height;
		this.invbarcode = invbarcode;
		this.invcode = invcode;
		this.invmnecode = invmnecode;
		this.invname = invname;
		this.invpinpai = invpinpai;
		this.invshortname = invshortname;
		this.invspec = invspec;
		this.invtype = invtype;
		this.iselectrans = iselectrans;
		this.ismngstockbygrswt = ismngstockbygrswt;
		this.isretail = isretail;
		this.isstorebyconvert = isstorebyconvert;
		this.laborflag = laborflag;
		this.length = length;
		this.memo = memo;
		this.modifier = modifier;
		this.modifytime = modifytime;
		this.pkAssetcategory = pkAssetcategory;
		this.pkCorp = pkCorp;
		this.pkInvcl = pkInvcl;
		this.pkMeasdoc = pkMeasdoc;
		this.pkMeasdoc1 = pkMeasdoc1;
		this.pkMeasdoc2 = pkMeasdoc2;
		this.pkMeasdoc3 = pkMeasdoc3;
		this.pkMeasdoc5 = pkMeasdoc5;
		this.pkMeasdoc6 = pkMeasdoc6;
		this.pkProdline = pkProdline;
		this.pkTaxitems = pkTaxitems;
		this.sealflag = sealflag;
		this.setpartsflag = setpartsflag;
		this.shipunitnum = shipunitnum;
		this.storeunitnum = storeunitnum;
		this.ts = ts;
		this.unitvolume = unitvolume;
		this.unitweight = unitweight;
		this.weitunitnum = weitunitnum;
		this.width = width;
		this.def21 = def21;
		this.def22 = def22;
		this.def23 = def23;
		this.def24 = def24;
		this.def25 = def25;
		this.def26 = def26;
		this.def27 = def27;
		this.def28 = def28;
		this.def29 = def29;
		this.def30 = def30;
		this.bdInvmandocs = bdInvmandocs;
	}

	@Id

	@Column(name = "PK_INVBASDOC", unique = true, nullable = false, length = 20)
	public String getPkInvbasdoc() {
		return this.pkInvbasdoc;
	}

	public void setPkInvbasdoc(String pkInvbasdoc) {
		this.pkInvbasdoc = pkInvbasdoc;
	}

	@Column(name = "ASSET", length = 1)
	public Character getAsset() {
		return this.asset;
	}

	public void setAsset(Character asset) {
		this.asset = asset;
	}

	@Column(name = "ASSISTUNIT", nullable = false, length = 1)
	public char getAssistunit() {
		return this.assistunit;
	}

	public void setAssistunit(char assistunit) {
		this.assistunit = assistunit;
	}

	@Column(name = "AUTOBALANCEMEAS", length = 1)
	public Character getAutobalancemeas() {
		return this.autobalancemeas;
	}

	public void setAutobalancemeas(Character autobalancemeas) {
		this.autobalancemeas = autobalancemeas;
	}

	@Column(name = "CREATETIME", length = 19)
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "DEF1", length = 100)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 100)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 100)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 100)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 100)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 100)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 100)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 100)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 100)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 100)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 100)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 100)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 100)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF3", length = 100)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF4", length = 100)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF5", length = 100)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF6", length = 100)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 100)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 100)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 100)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DISCOUNTFLAG", length = 1)
	public Character getDiscountflag() {
		return this.discountflag;
	}

	public void setDiscountflag(Character discountflag) {
		this.discountflag = discountflag;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "FORINVNAME", length = 200)
	public String getForinvname() {
		return this.forinvname;
	}

	public void setForinvname(String forinvname) {
		this.forinvname = forinvname;
	}

	@Column(name = "FREE1", length = 20)
	public String getFree1() {
		return this.free1;
	}

	public void setFree1(String free1) {
		this.free1 = free1;
	}

	@Column(name = "FREE2", length = 20)
	public String getFree2() {
		return this.free2;
	}

	public void setFree2(String free2) {
		this.free2 = free2;
	}

	@Column(name = "FREE3", length = 20)
	public String getFree3() {
		return this.free3;
	}

	public void setFree3(String free3) {
		this.free3 = free3;
	}

	@Column(name = "FREE4", length = 20)
	public String getFree4() {
		return this.free4;
	}

	public void setFree4(String free4) {
		this.free4 = free4;
	}

	@Column(name = "FREE5", length = 20)
	public String getFree5() {
		return this.free5;
	}

	public void setFree5(String free5) {
		this.free5 = free5;
	}

	@Column(name = "GRAPHID", length = 50)
	public String getGraphid() {
		return this.graphid;
	}

	public void setGraphid(String graphid) {
		this.graphid = graphid;
	}

	@Column(name = "HEIGHT", length = 20)
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "INVBARCODE", length = 30)
	public String getInvbarcode() {
		return this.invbarcode;
	}

	public void setInvbarcode(String invbarcode) {
		this.invbarcode = invbarcode;
	}

	@Column(name = "INVCODE", nullable = false, length = 40)
	public String getInvcode() {
		return this.invcode;
	}

	public void setInvcode(String invcode) {
		this.invcode = invcode;
	}

	@Column(name = "INVMNECODE", length = 50)
	public String getInvmnecode() {
		return this.invmnecode;
	}

	public void setInvmnecode(String invmnecode) {
		this.invmnecode = invmnecode;
	}

	@Column(name = "INVNAME", nullable = false, length = 200)
	public String getInvname() {
		return this.invname;
	}

	public void setInvname(String invname) {
		this.invname = invname;
	}

	@Column(name = "INVPINPAI", length = 100)
	public String getInvpinpai() {
		return this.invpinpai;
	}

	public void setInvpinpai(String invpinpai) {
		this.invpinpai = invpinpai;
	}

	@Column(name = "INVSHORTNAME", length = 200)
	public String getInvshortname() {
		return this.invshortname;
	}

	public void setInvshortname(String invshortname) {
		this.invshortname = invshortname;
	}

	@Column(name = "INVSPEC", length = 50)
	public String getInvspec() {
		return this.invspec;
	}

	public void setInvspec(String invspec) {
		this.invspec = invspec;
	}

	@Column(name = "INVTYPE", length = 50)
	public String getInvtype() {
		return this.invtype;
	}

	public void setInvtype(String invtype) {
		this.invtype = invtype;
	}

	@Column(name = "ISELECTRANS", length = 1)
	public Character getIselectrans() {
		return this.iselectrans;
	}

	public void setIselectrans(Character iselectrans) {
		this.iselectrans = iselectrans;
	}

	@Column(name = "ISMNGSTOCKBYGRSWT", length = 1)
	public Character getIsmngstockbygrswt() {
		return this.ismngstockbygrswt;
	}

	public void setIsmngstockbygrswt(Character ismngstockbygrswt) {
		this.ismngstockbygrswt = ismngstockbygrswt;
	}

	@Column(name = "ISRETAIL", length = 1)
	public Character getIsretail() {
		return this.isretail;
	}

	public void setIsretail(Character isretail) {
		this.isretail = isretail;
	}

	@Column(name = "ISSTOREBYCONVERT", length = 1)
	public Character getIsstorebyconvert() {
		return this.isstorebyconvert;
	}

	public void setIsstorebyconvert(Character isstorebyconvert) {
		this.isstorebyconvert = isstorebyconvert;
	}

	@Column(name = "LABORFLAG", length = 1)
	public Character getLaborflag() {
		return this.laborflag;
	}

	public void setLaborflag(Character laborflag) {
		this.laborflag = laborflag;
	}

	@Column(name = "LENGTH", length = 20)
	public String getLength() {
		return this.length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	@Column(name = "MEMO", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Column(name = "MODIFYTIME", length = 19)
	public String getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(String modifytime) {
		this.modifytime = modifytime;
	}

	@Column(name = "PK_ASSETCATEGORY", length = 20)
	public String getPkAssetcategory() {
		return this.pkAssetcategory;
	}

	public void setPkAssetcategory(String pkAssetcategory) {
		this.pkAssetcategory = pkAssetcategory;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_INVCL", nullable = false, length = 20)
	public String getPkInvcl() {
		return this.pkInvcl;
	}

	public void setPkInvcl(String pkInvcl) {
		this.pkInvcl = pkInvcl;
	}

	@Column(name = "PK_MEASDOC", nullable = false, length = 20)
	public String getPkMeasdoc() {
		return this.pkMeasdoc;
	}

	public void setPkMeasdoc(String pkMeasdoc) {
		this.pkMeasdoc = pkMeasdoc;
	}

	@Column(name = "PK_MEASDOC1", length = 20)
	public String getPkMeasdoc1() {
		return this.pkMeasdoc1;
	}

	public void setPkMeasdoc1(String pkMeasdoc1) {
		this.pkMeasdoc1 = pkMeasdoc1;
	}

	@Column(name = "PK_MEASDOC2", length = 20)
	public String getPkMeasdoc2() {
		return this.pkMeasdoc2;
	}

	public void setPkMeasdoc2(String pkMeasdoc2) {
		this.pkMeasdoc2 = pkMeasdoc2;
	}

	@Column(name = "PK_MEASDOC3", length = 20)
	public String getPkMeasdoc3() {
		return this.pkMeasdoc3;
	}

	public void setPkMeasdoc3(String pkMeasdoc3) {
		this.pkMeasdoc3 = pkMeasdoc3;
	}

	@Column(name = "PK_MEASDOC5", length = 20)
	public String getPkMeasdoc5() {
		return this.pkMeasdoc5;
	}

	public void setPkMeasdoc5(String pkMeasdoc5) {
		this.pkMeasdoc5 = pkMeasdoc5;
	}

	@Column(name = "PK_MEASDOC6", length = 20)
	public String getPkMeasdoc6() {
		return this.pkMeasdoc6;
	}

	public void setPkMeasdoc6(String pkMeasdoc6) {
		this.pkMeasdoc6 = pkMeasdoc6;
	}

	@Column(name = "PK_PRODLINE", length = 20)
	public String getPkProdline() {
		return this.pkProdline;
	}

	public void setPkProdline(String pkProdline) {
		this.pkProdline = pkProdline;
	}

	@Column(name = "PK_TAXITEMS", length = 20)
	public String getPkTaxitems() {
		return this.pkTaxitems;
	}

	public void setPkTaxitems(String pkTaxitems) {
		this.pkTaxitems = pkTaxitems;
	}

	@Column(name = "SEALFLAG", length = 10)
	public String getSealflag() {
		return this.sealflag;
	}

	public void setSealflag(String sealflag) {
		this.sealflag = sealflag;
	}

	@Column(name = "SETPARTSFLAG", length = 1)
	public Character getSetpartsflag() {
		return this.setpartsflag;
	}

	public void setSetpartsflag(Character setpartsflag) {
		this.setpartsflag = setpartsflag;
	}

	@Column(name = "SHIPUNITNUM", precision = 20, scale = 8)
	public BigDecimal getShipunitnum() {
		return this.shipunitnum;
	}

	public void setShipunitnum(BigDecimal shipunitnum) {
		this.shipunitnum = shipunitnum;
	}

	@Column(name = "STOREUNITNUM", precision = 20, scale = 8)
	public BigDecimal getStoreunitnum() {
		return this.storeunitnum;
	}

	public void setStoreunitnum(BigDecimal storeunitnum) {
		this.storeunitnum = storeunitnum;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "UNITVOLUME", precision = 20, scale = 8)
	public BigDecimal getUnitvolume() {
		return this.unitvolume;
	}

	public void setUnitvolume(BigDecimal unitvolume) {
		this.unitvolume = unitvolume;
	}

	@Column(name = "UNITWEIGHT", precision = 20, scale = 8)
	public BigDecimal getUnitweight() {
		return this.unitweight;
	}

	public void setUnitweight(BigDecimal unitweight) {
		this.unitweight = unitweight;
	}

	@Column(name = "WEITUNITNUM", precision = 20, scale = 8)
	public BigDecimal getWeitunitnum() {
		return this.weitunitnum;
	}

	public void setWeitunitnum(BigDecimal weitunitnum) {
		this.weitunitnum = weitunitnum;
	}

	@Column(name = "WIDTH", length = 20)
	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	@Column(name = "DEF21", length = 100)
	public String getDef21() {
		return this.def21;
	}

	public void setDef21(String def21) {
		this.def21 = def21;
	}

	@Column(name = "DEF22", length = 100)
	public String getDef22() {
		return this.def22;
	}

	public void setDef22(String def22) {
		this.def22 = def22;
	}

	@Column(name = "DEF23", length = 100)
	public String getDef23() {
		return this.def23;
	}

	public void setDef23(String def23) {
		this.def23 = def23;
	}

	@Column(name = "DEF24", length = 100)
	public String getDef24() {
		return this.def24;
	}

	public void setDef24(String def24) {
		this.def24 = def24;
	}

	@Column(name = "DEF25", length = 100)
	public String getDef25() {
		return this.def25;
	}

	public void setDef25(String def25) {
		this.def25 = def25;
	}

	@Column(name = "DEF26", length = 100)
	public String getDef26() {
		return this.def26;
	}

	public void setDef26(String def26) {
		this.def26 = def26;
	}

	@Column(name = "DEF27", length = 100)
	public String getDef27() {
		return this.def27;
	}

	public void setDef27(String def27) {
		this.def27 = def27;
	}

	@Column(name = "DEF28", length = 100)
	public String getDef28() {
		return this.def28;
	}

	public void setDef28(String def28) {
		this.def28 = def28;
	}

	@Column(name = "DEF29", length = 100)
	public String getDef29() {
		return this.def29;
	}

	public void setDef29(String def29) {
		this.def29 = def29;
	}

	@Column(name = "DEF30", length = 100)
	public String getDef30() {
		return this.def30;
	}

	public void setDef30(String def30) {
		this.def30 = def30;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bdInvbasdoc")
	public Set getBdInvmandocs() {
		return this.bdInvmandocs;
	}

	public void setBdInvmandocs(Set bdInvmandocs) {
		this.bdInvmandocs = bdInvmandocs;
	}

}
