package com.nts.teststruts.model;
// Generated 2015-7-24 10:07:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BdJobbasfil generated by hbm2java
 */
@Entity
@Table(name = "BD_JOBBASFIL", schema = "NC58")
public class BdJobbasfil implements java.io.Serializable {

	private String pkJobbasfil;
	private String begindate;
	private String cremcode;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private Long dr;
	private String enddate;
	private Character finishedflag;
	private String forecastenddate;
	private String jobcode;
	private String jobname;
	private String pkCorp;
	private String pkJobcl;
	private String pkJobtype;
	private Character sealflag;
	private String ts;
	private String pkMtusage;
	private BigDecimal yflb;

	public BdJobbasfil() {
	}

	public BdJobbasfil(String pkJobbasfil, String jobcode, String jobname, String pkCorp, String pkJobtype) {
		this.pkJobbasfil = pkJobbasfil;
		this.jobcode = jobcode;
		this.jobname = jobname;
		this.pkCorp = pkCorp;
		this.pkJobtype = pkJobtype;
	}

	public BdJobbasfil(String pkJobbasfil, String begindate, String cremcode, String def1, String def10, String def11,
			String def12, String def13, String def14, String def15, String def16, String def17, String def18,
			String def19, String def2, String def20, String def3, String def4, String def5, String def6, String def7,
			String def8, String def9, Long dr, String enddate, Character finishedflag, String forecastenddate,
			String jobcode, String jobname, String pkCorp, String pkJobcl, String pkJobtype, Character sealflag,
			String ts, String pkMtusage, BigDecimal yflb) {
		this.pkJobbasfil = pkJobbasfil;
		this.begindate = begindate;
		this.cremcode = cremcode;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def3 = def3;
		this.def4 = def4;
		this.def5 = def5;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.dr = dr;
		this.enddate = enddate;
		this.finishedflag = finishedflag;
		this.forecastenddate = forecastenddate;
		this.jobcode = jobcode;
		this.jobname = jobname;
		this.pkCorp = pkCorp;
		this.pkJobcl = pkJobcl;
		this.pkJobtype = pkJobtype;
		this.sealflag = sealflag;
		this.ts = ts;
		this.pkMtusage = pkMtusage;
		this.yflb = yflb;
	}

	@Id

	@Column(name = "PK_JOBBASFIL", unique = true, nullable = false, length = 20)
	public String getPkJobbasfil() {
		return this.pkJobbasfil;
	}

	public void setPkJobbasfil(String pkJobbasfil) {
		this.pkJobbasfil = pkJobbasfil;
	}

	@Column(name = "BEGINDATE", length = 10)
	public String getBegindate() {
		return this.begindate;
	}

	public void setBegindate(String begindate) {
		this.begindate = begindate;
	}

	@Column(name = "CREMCODE", length = 50)
	public String getCremcode() {
		return this.cremcode;
	}

	public void setCremcode(String cremcode) {
		this.cremcode = cremcode;
	}

	@Column(name = "DEF1", length = 100)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 100)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 100)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 100)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 100)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 100)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 100)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 100)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 100)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 100)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 100)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 100)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 100)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF3", length = 100)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF4", length = 100)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF5", length = 100)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF6", length = 100)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 100)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 100)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 100)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "ENDDATE", length = 10)
	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	@Column(name = "FINISHEDFLAG", length = 1)
	public Character getFinishedflag() {
		return this.finishedflag;
	}

	public void setFinishedflag(Character finishedflag) {
		this.finishedflag = finishedflag;
	}

	@Column(name = "FORECASTENDDATE", length = 10)
	public String getForecastenddate() {
		return this.forecastenddate;
	}

	public void setForecastenddate(String forecastenddate) {
		this.forecastenddate = forecastenddate;
	}

	@Column(name = "JOBCODE", nullable = false, length = 40)
	public String getJobcode() {
		return this.jobcode;
	}

	public void setJobcode(String jobcode) {
		this.jobcode = jobcode;
	}

	@Column(name = "JOBNAME", nullable = false, length = 200)
	public String getJobname() {
		return this.jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_JOBCL", length = 20)
	public String getPkJobcl() {
		return this.pkJobcl;
	}

	public void setPkJobcl(String pkJobcl) {
		this.pkJobcl = pkJobcl;
	}

	@Column(name = "PK_JOBTYPE", nullable = false, length = 20)
	public String getPkJobtype() {
		return this.pkJobtype;
	}

	public void setPkJobtype(String pkJobtype) {
		this.pkJobtype = pkJobtype;
	}

	@Column(name = "SEALFLAG", length = 1)
	public Character getSealflag() {
		return this.sealflag;
	}

	public void setSealflag(Character sealflag) {
		this.sealflag = sealflag;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "PK_MTUSAGE", length = 20)
	public String getPkMtusage() {
		return this.pkMtusage;
	}

	public void setPkMtusage(String pkMtusage) {
		this.pkMtusage = pkMtusage;
	}

	@Column(name = "YFLB", precision = 38, scale = 0)
	public BigDecimal getYflb() {
		return this.yflb;
	}

	public void setYflb(BigDecimal yflb) {
		this.yflb = yflb;
	}

}
