package com.nts.teststruts.model;
// Generated 2015-12-11 13:14:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CollectReport generated by hbm2java
 */
@Entity
@Table(name = "COLLECT_REPORT", schema = "NC58", uniqueConstraints = @UniqueConstraint(columnNames = "ONE_PK_CODE") )
public class CollectReport implements java.io.Serializable {

	private String pkCollect;
	private String mark;
	private String onePkCode;
	private String shipCode;
	private String sectionCode;
	private String pipeCode;
	private String pipeStandard;
	private String texture;
	private String processMode;
	private String starttime;
	private String collecttime;
	private String receivetime;
	private String importtime;
	private String vnote;
	private String pkCorp;
	private BigDecimal dr;
	private String ts;
	private String vdef1;
	private String vdef2;
	private String vdef3;
	private String vdef4;
	private String vdef5;
	private String vdef6;
	private String vdef7;
	private String vdef8;
	private String vdef9;
	private String vdef10;
	private String vdef11;
	private String vdef12;
	private String vdef13;
	private String vdef14;
	private String vdef15;
	private String vdef16;
	private String vdef17;
	private String vdef18;
	private String vdef19;
	private String vdef20;
	private String pkDefdoc1;
	private String pkDefdoc2;
	private String pkDefdoc3;
	private String pkDefdoc4;
	private String pkDefdoc5;
	private String pkDefdoc6;
	private String pkDefdoc7;
	private String pkDefdoc8;
	private String pkDefdoc9;
	private String pkDefdoc10;
	private String pkDefdoc11;
	private String pkDefdoc12;
	private String pkDefdoc13;
	private String pkDefdoc14;
	private String pkDefdoc15;
	private String pkDefdoc16;
	private String pkDefdoc17;
	private String pkDefdoc18;
	private String pkDefdoc19;
	private String pkDefdoc20;
	private String vfree1;
	private String vfree2;
	private String vfree3;
	private String vfree4;
	private String vfree5;

	public CollectReport() {
	}

	public CollectReport(String pkCollect, String mark, String onePkCode) {
		this.pkCollect = pkCollect;
		this.mark = mark;
		this.onePkCode = onePkCode;
	}

	public CollectReport(String pkCollect, String mark, String onePkCode, String shipCode, String sectionCode,
			String pipeCode, String pipeStandard, String texture, String processMode, String starttime,
			String collecttime, String receivetime, String importtime, String vnote, String pkCorp, BigDecimal dr,
			String ts, String vdef1, String vdef2, String vdef3, String vdef4, String vdef5, String vdef6, String vdef7,
			String vdef8, String vdef9, String vdef10, String vdef11, String vdef12, String vdef13, String vdef14,
			String vdef15, String vdef16, String vdef17, String vdef18, String vdef19, String vdef20, String pkDefdoc1,
			String pkDefdoc2, String pkDefdoc3, String pkDefdoc4, String pkDefdoc5, String pkDefdoc6, String pkDefdoc7,
			String pkDefdoc8, String pkDefdoc9, String pkDefdoc10, String pkDefdoc11, String pkDefdoc12,
			String pkDefdoc13, String pkDefdoc14, String pkDefdoc15, String pkDefdoc16, String pkDefdoc17,
			String pkDefdoc18, String pkDefdoc19, String pkDefdoc20, String vfree1, String vfree2, String vfree3,
			String vfree4, String vfree5) {
		this.pkCollect = pkCollect;
		this.mark = mark;
		this.onePkCode = onePkCode;
		this.shipCode = shipCode;
		this.sectionCode = sectionCode;
		this.pipeCode = pipeCode;
		this.pipeStandard = pipeStandard;
		this.texture = texture;
		this.processMode = processMode;
		this.starttime = starttime;
		this.collecttime = collecttime;
		this.receivetime = receivetime;
		this.importtime = importtime;
		this.vnote = vnote;
		this.pkCorp = pkCorp;
		this.dr = dr;
		this.ts = ts;
		this.vdef1 = vdef1;
		this.vdef2 = vdef2;
		this.vdef3 = vdef3;
		this.vdef4 = vdef4;
		this.vdef5 = vdef5;
		this.vdef6 = vdef6;
		this.vdef7 = vdef7;
		this.vdef8 = vdef8;
		this.vdef9 = vdef9;
		this.vdef10 = vdef10;
		this.vdef11 = vdef11;
		this.vdef12 = vdef12;
		this.vdef13 = vdef13;
		this.vdef14 = vdef14;
		this.vdef15 = vdef15;
		this.vdef16 = vdef16;
		this.vdef17 = vdef17;
		this.vdef18 = vdef18;
		this.vdef19 = vdef19;
		this.vdef20 = vdef20;
		this.pkDefdoc1 = pkDefdoc1;
		this.pkDefdoc2 = pkDefdoc2;
		this.pkDefdoc3 = pkDefdoc3;
		this.pkDefdoc4 = pkDefdoc4;
		this.pkDefdoc5 = pkDefdoc5;
		this.pkDefdoc6 = pkDefdoc6;
		this.pkDefdoc7 = pkDefdoc7;
		this.pkDefdoc8 = pkDefdoc8;
		this.pkDefdoc9 = pkDefdoc9;
		this.pkDefdoc10 = pkDefdoc10;
		this.pkDefdoc11 = pkDefdoc11;
		this.pkDefdoc12 = pkDefdoc12;
		this.pkDefdoc13 = pkDefdoc13;
		this.pkDefdoc14 = pkDefdoc14;
		this.pkDefdoc15 = pkDefdoc15;
		this.pkDefdoc16 = pkDefdoc16;
		this.pkDefdoc17 = pkDefdoc17;
		this.pkDefdoc18 = pkDefdoc18;
		this.pkDefdoc19 = pkDefdoc19;
		this.pkDefdoc20 = pkDefdoc20;
		this.vfree1 = vfree1;
		this.vfree2 = vfree2;
		this.vfree3 = vfree3;
		this.vfree4 = vfree4;
		this.vfree5 = vfree5;
	}

	@Id

	@Column(name = "PK_COLLECT", unique = true, nullable = false, length = 20)
	public String getPkCollect() {
		return this.pkCollect;
	}

	public void setPkCollect(String pkCollect) {
		this.pkCollect = pkCollect;
	}

	@Column(name = "MARK", nullable = false, length = 100)
	public String getMark() {
		return this.mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	@Column(name = "ONE_PK_CODE", unique = true, nullable = false, length = 100)
	public String getOnePkCode() {
		return this.onePkCode;
	}

	public void setOnePkCode(String onePkCode) {
		this.onePkCode = onePkCode;
	}

	@Column(name = "SHIP_CODE", length = 100)
	public String getShipCode() {
		return this.shipCode;
	}

	public void setShipCode(String shipCode) {
		this.shipCode = shipCode;
	}

	@Column(name = "SECTION_CODE", length = 100)
	public String getSectionCode() {
		return this.sectionCode;
	}

	public void setSectionCode(String sectionCode) {
		this.sectionCode = sectionCode;
	}

	@Column(name = "PIPE_CODE", length = 100)
	public String getPipeCode() {
		return this.pipeCode;
	}

	public void setPipeCode(String pipeCode) {
		this.pipeCode = pipeCode;
	}

	@Column(name = "PIPE_STANDARD", length = 100)
	public String getPipeStandard() {
		return this.pipeStandard;
	}

	public void setPipeStandard(String pipeStandard) {
		this.pipeStandard = pipeStandard;
	}

	@Column(name = "TEXTURE", length = 100)
	public String getTexture() {
		return this.texture;
	}

	public void setTexture(String texture) {
		this.texture = texture;
	}

	@Column(name = "PROCESS_MODE", length = 100)
	public String getProcessMode() {
		return this.processMode;
	}

	public void setProcessMode(String processMode) {
		this.processMode = processMode;
	}

	@Column(name = "STARTTIME", length = 100)
	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	@Column(name = "COLLECTTIME", length = 100)
	public String getCollecttime() {
		return this.collecttime;
	}

	public void setCollecttime(String collecttime) {
		this.collecttime = collecttime;
	}

	@Column(name = "RECEIVETIME", length = 100)
	public String getReceivetime() {
		return this.receivetime;
	}

	public void setReceivetime(String receivetime) {
		this.receivetime = receivetime;
	}

	@Column(name = "IMPORTTIME", length = 100)
	public String getImporttime() {
		return this.importtime;
	}

	public void setImporttime(String importtime) {
		this.importtime = importtime;
	}

	@Column(name = "VNOTE", length = 500)
	public String getVnote() {
		return this.vnote;
	}

	public void setVnote(String vnote) {
		this.vnote = vnote;
	}

	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "DR", precision = 22, scale = 0)
	public BigDecimal getDr() {
		return this.dr;
	}

	public void setDr(BigDecimal dr) {
		this.dr = dr;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "VDEF1", length = 100)
	public String getVdef1() {
		return this.vdef1;
	}

	public void setVdef1(String vdef1) {
		this.vdef1 = vdef1;
	}

	@Column(name = "VDEF2", length = 100)
	public String getVdef2() {
		return this.vdef2;
	}

	public void setVdef2(String vdef2) {
		this.vdef2 = vdef2;
	}

	@Column(name = "VDEF3", length = 100)
	public String getVdef3() {
		return this.vdef3;
	}

	public void setVdef3(String vdef3) {
		this.vdef3 = vdef3;
	}

	@Column(name = "VDEF4", length = 100)
	public String getVdef4() {
		return this.vdef4;
	}

	public void setVdef4(String vdef4) {
		this.vdef4 = vdef4;
	}

	@Column(name = "VDEF5", length = 100)
	public String getVdef5() {
		return this.vdef5;
	}

	public void setVdef5(String vdef5) {
		this.vdef5 = vdef5;
	}

	@Column(name = "VDEF6", length = 100)
	public String getVdef6() {
		return this.vdef6;
	}

	public void setVdef6(String vdef6) {
		this.vdef6 = vdef6;
	}

	@Column(name = "VDEF7", length = 100)
	public String getVdef7() {
		return this.vdef7;
	}

	public void setVdef7(String vdef7) {
		this.vdef7 = vdef7;
	}

	@Column(name = "VDEF8", length = 100)
	public String getVdef8() {
		return this.vdef8;
	}

	public void setVdef8(String vdef8) {
		this.vdef8 = vdef8;
	}

	@Column(name = "VDEF9", length = 100)
	public String getVdef9() {
		return this.vdef9;
	}

	public void setVdef9(String vdef9) {
		this.vdef9 = vdef9;
	}

	@Column(name = "VDEF10", length = 100)
	public String getVdef10() {
		return this.vdef10;
	}

	public void setVdef10(String vdef10) {
		this.vdef10 = vdef10;
	}

	@Column(name = "VDEF11", length = 100)
	public String getVdef11() {
		return this.vdef11;
	}

	public void setVdef11(String vdef11) {
		this.vdef11 = vdef11;
	}

	@Column(name = "VDEF12", length = 100)
	public String getVdef12() {
		return this.vdef12;
	}

	public void setVdef12(String vdef12) {
		this.vdef12 = vdef12;
	}

	@Column(name = "VDEF13", length = 100)
	public String getVdef13() {
		return this.vdef13;
	}

	public void setVdef13(String vdef13) {
		this.vdef13 = vdef13;
	}

	@Column(name = "VDEF14", length = 100)
	public String getVdef14() {
		return this.vdef14;
	}

	public void setVdef14(String vdef14) {
		this.vdef14 = vdef14;
	}

	@Column(name = "VDEF15", length = 100)
	public String getVdef15() {
		return this.vdef15;
	}

	public void setVdef15(String vdef15) {
		this.vdef15 = vdef15;
	}

	@Column(name = "VDEF16", length = 100)
	public String getVdef16() {
		return this.vdef16;
	}

	public void setVdef16(String vdef16) {
		this.vdef16 = vdef16;
	}

	@Column(name = "VDEF17", length = 100)
	public String getVdef17() {
		return this.vdef17;
	}

	public void setVdef17(String vdef17) {
		this.vdef17 = vdef17;
	}

	@Column(name = "VDEF18", length = 100)
	public String getVdef18() {
		return this.vdef18;
	}

	public void setVdef18(String vdef18) {
		this.vdef18 = vdef18;
	}

	@Column(name = "VDEF19", length = 100)
	public String getVdef19() {
		return this.vdef19;
	}

	public void setVdef19(String vdef19) {
		this.vdef19 = vdef19;
	}

	@Column(name = "VDEF20", length = 100)
	public String getVdef20() {
		return this.vdef20;
	}

	public void setVdef20(String vdef20) {
		this.vdef20 = vdef20;
	}

	@Column(name = "PK_DEFDOC1", length = 20)
	public String getPkDefdoc1() {
		return this.pkDefdoc1;
	}

	public void setPkDefdoc1(String pkDefdoc1) {
		this.pkDefdoc1 = pkDefdoc1;
	}

	@Column(name = "PK_DEFDOC2", length = 20)
	public String getPkDefdoc2() {
		return this.pkDefdoc2;
	}

	public void setPkDefdoc2(String pkDefdoc2) {
		this.pkDefdoc2 = pkDefdoc2;
	}

	@Column(name = "PK_DEFDOC3", length = 20)
	public String getPkDefdoc3() {
		return this.pkDefdoc3;
	}

	public void setPkDefdoc3(String pkDefdoc3) {
		this.pkDefdoc3 = pkDefdoc3;
	}

	@Column(name = "PK_DEFDOC4", length = 20)
	public String getPkDefdoc4() {
		return this.pkDefdoc4;
	}

	public void setPkDefdoc4(String pkDefdoc4) {
		this.pkDefdoc4 = pkDefdoc4;
	}

	@Column(name = "PK_DEFDOC5", length = 20)
	public String getPkDefdoc5() {
		return this.pkDefdoc5;
	}

	public void setPkDefdoc5(String pkDefdoc5) {
		this.pkDefdoc5 = pkDefdoc5;
	}

	@Column(name = "PK_DEFDOC6", length = 20)
	public String getPkDefdoc6() {
		return this.pkDefdoc6;
	}

	public void setPkDefdoc6(String pkDefdoc6) {
		this.pkDefdoc6 = pkDefdoc6;
	}

	@Column(name = "PK_DEFDOC7", length = 20)
	public String getPkDefdoc7() {
		return this.pkDefdoc7;
	}

	public void setPkDefdoc7(String pkDefdoc7) {
		this.pkDefdoc7 = pkDefdoc7;
	}

	@Column(name = "PK_DEFDOC8", length = 20)
	public String getPkDefdoc8() {
		return this.pkDefdoc8;
	}

	public void setPkDefdoc8(String pkDefdoc8) {
		this.pkDefdoc8 = pkDefdoc8;
	}

	@Column(name = "PK_DEFDOC9", length = 20)
	public String getPkDefdoc9() {
		return this.pkDefdoc9;
	}

	public void setPkDefdoc9(String pkDefdoc9) {
		this.pkDefdoc9 = pkDefdoc9;
	}

	@Column(name = "PK_DEFDOC10", length = 20)
	public String getPkDefdoc10() {
		return this.pkDefdoc10;
	}

	public void setPkDefdoc10(String pkDefdoc10) {
		this.pkDefdoc10 = pkDefdoc10;
	}

	@Column(name = "PK_DEFDOC11", length = 20)
	public String getPkDefdoc11() {
		return this.pkDefdoc11;
	}

	public void setPkDefdoc11(String pkDefdoc11) {
		this.pkDefdoc11 = pkDefdoc11;
	}

	@Column(name = "PK_DEFDOC12", length = 20)
	public String getPkDefdoc12() {
		return this.pkDefdoc12;
	}

	public void setPkDefdoc12(String pkDefdoc12) {
		this.pkDefdoc12 = pkDefdoc12;
	}

	@Column(name = "PK_DEFDOC13", length = 20)
	public String getPkDefdoc13() {
		return this.pkDefdoc13;
	}

	public void setPkDefdoc13(String pkDefdoc13) {
		this.pkDefdoc13 = pkDefdoc13;
	}

	@Column(name = "PK_DEFDOC14", length = 20)
	public String getPkDefdoc14() {
		return this.pkDefdoc14;
	}

	public void setPkDefdoc14(String pkDefdoc14) {
		this.pkDefdoc14 = pkDefdoc14;
	}

	@Column(name = "PK_DEFDOC15", length = 20)
	public String getPkDefdoc15() {
		return this.pkDefdoc15;
	}

	public void setPkDefdoc15(String pkDefdoc15) {
		this.pkDefdoc15 = pkDefdoc15;
	}

	@Column(name = "PK_DEFDOC16", length = 20)
	public String getPkDefdoc16() {
		return this.pkDefdoc16;
	}

	public void setPkDefdoc16(String pkDefdoc16) {
		this.pkDefdoc16 = pkDefdoc16;
	}

	@Column(name = "PK_DEFDOC17", length = 20)
	public String getPkDefdoc17() {
		return this.pkDefdoc17;
	}

	public void setPkDefdoc17(String pkDefdoc17) {
		this.pkDefdoc17 = pkDefdoc17;
	}

	@Column(name = "PK_DEFDOC18", length = 20)
	public String getPkDefdoc18() {
		return this.pkDefdoc18;
	}

	public void setPkDefdoc18(String pkDefdoc18) {
		this.pkDefdoc18 = pkDefdoc18;
	}

	@Column(name = "PK_DEFDOC19", length = 20)
	public String getPkDefdoc19() {
		return this.pkDefdoc19;
	}

	public void setPkDefdoc19(String pkDefdoc19) {
		this.pkDefdoc19 = pkDefdoc19;
	}

	@Column(name = "PK_DEFDOC20", length = 20)
	public String getPkDefdoc20() {
		return this.pkDefdoc20;
	}

	public void setPkDefdoc20(String pkDefdoc20) {
		this.pkDefdoc20 = pkDefdoc20;
	}

	@Column(name = "VFREE1", length = 100)
	public String getVfree1() {
		return this.vfree1;
	}

	public void setVfree1(String vfree1) {
		this.vfree1 = vfree1;
	}

	@Column(name = "VFREE2", length = 100)
	public String getVfree2() {
		return this.vfree2;
	}

	public void setVfree2(String vfree2) {
		this.vfree2 = vfree2;
	}

	@Column(name = "VFREE3", length = 100)
	public String getVfree3() {
		return this.vfree3;
	}

	public void setVfree3(String vfree3) {
		this.vfree3 = vfree3;
	}

	@Column(name = "VFREE4", length = 100)
	public String getVfree4() {
		return this.vfree4;
	}

	public void setVfree4(String vfree4) {
		this.vfree4 = vfree4;
	}

	@Column(name = "VFREE5", length = 100)
	public String getVfree5() {
		return this.vfree5;
	}

	public void setVfree5(String vfree5) {
		this.vfree5 = vfree5;
	}

}
