package com.nts.teststruts.model;
// Generated 2016-9-26 9:04:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE", schema = "NC58")
public class Employee implements java.io.Serializable {

	private String employeeuuid;
	private String psnname;
	private BigDecimal sex;
	private BigDecimal health;
	private BigDecimal status;
	private String birthdate;
	private String id;
	private String province;
	private String city;
	private String country;
	private String addr;
	private String mobile;
	private String createtime;
	private String job;
	private String dept;
	private String usedept;
	private String applytime;
	private String checktime;
	private String creator;
	private String bankname;
	private String bankcode;
	private String teamname;
	private String inscompany;
	private String inscode;
	private String insbegindate;
	private String insenddate;
	private String injuryinscode;
	private String dispatchcode;
	private String dispatchtime;
	private String feedbacktime;
	private String yktcode;
	private String pkcorp;

	public Employee() {
	}

	public Employee(String employeeuuid) {
		this.employeeuuid = employeeuuid;
	}

	public Employee(String employeeuuid, String psnname, BigDecimal sex, BigDecimal health, BigDecimal status,
			String birthdate, String id, String province, String city, String country, String addr, String mobile,
			String createtime, String job, String dept, String usedept, String applytime, String checktime,
			String creator, String bankname, String bankcode, String teamname, String inscompany, String inscode,
			String insbegindate, String insenddate, String injuryinscode, String dispatchcode, String dispatchtime,
			String feedbacktime, String yktcode, String pkcorp) {
		this.employeeuuid = employeeuuid;
		this.psnname = psnname;
		this.sex = sex;
		this.health = health;
		this.status = status;
		this.birthdate = birthdate;
		this.id = id;
		this.province = province;
		this.city = city;
		this.country = country;
		this.addr = addr;
		this.mobile = mobile;
		this.createtime = createtime;
		this.job = job;
		this.dept = dept;
		this.usedept = usedept;
		this.applytime = applytime;
		this.checktime = checktime;
		this.creator = creator;
		this.bankname = bankname;
		this.bankcode = bankcode;
		this.teamname = teamname;
		this.inscompany = inscompany;
		this.inscode = inscode;
		this.insbegindate = insbegindate;
		this.insenddate = insenddate;
		this.injuryinscode = injuryinscode;
		this.dispatchcode = dispatchcode;
		this.dispatchtime = dispatchtime;
		this.feedbacktime = feedbacktime;
		this.yktcode = yktcode;
		this.pkcorp = pkcorp;
	}

	@Id
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "EMPLOYEEUUID", unique = true, nullable = false, length = 32)
	public String getEmployeeuuid() {
		return this.employeeuuid;
	}

	public void setEmployeeuuid(String employeeuuid) {
		this.employeeuuid = employeeuuid;
	}

	@Column(name = "PSNNAME", length = 15)
	public String getPsnname() {
		return this.psnname;
	}

	public void setPsnname(String psnname) {
		this.psnname = psnname;
	}

	@Column(name = "SEX", precision = 22, scale = 0)
	public BigDecimal getSex() {
		return this.sex;
	}

	public void setSex(BigDecimal sex) {
		this.sex = sex;
	}

	@Column(name = "HEALTH", precision = 22, scale = 0)
	public BigDecimal getHealth() {
		return this.health;
	}

	public void setHealth(BigDecimal health) {
		this.health = health;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "BIRTHDATE", length = 10)
	public String getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "ID", length = 18)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PROVINCE", length = 10)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "CITY", length = 10)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "COUNTRY", length = 10)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ADDR", length = 50)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "MOBILE", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "CREATETIME", length = 20)
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "JOB", length = 20)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "DEPT", length = 20)
	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@Column(name = "USEDEPT", length = 20)
	public String getUsedept() {
		return this.usedept;
	}

	public void setUsedept(String usedept) {
		this.usedept = usedept;
	}

	@Column(name = "APPLYTIME", length = 20)
	public String getApplytime() {
		return this.applytime;
	}

	public void setApplytime(String applytime) {
		this.applytime = applytime;
	}

	@Column(name = "CHECKTIME", length = 20)
	public String getChecktime() {
		return this.checktime;
	}

	public void setChecktime(String checktime) {
		this.checktime = checktime;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "BANKNAME", length = 20)
	public String getBankname() {
		return this.bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	@Column(name = "BANKCODE", length = 20)
	public String getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "TEAMNAME", length = 10)
	public String getTeamname() {
		return this.teamname;
	}

	public void setTeamname(String teamname) {
		this.teamname = teamname;
	}

	@Column(name = "INSCOMPANY", length = 40)
	public String getInscompany() {
		return this.inscompany;
	}

	public void setInscompany(String inscompany) {
		this.inscompany = inscompany;
	}

	@Column(name = "INSCODE", length = 40)
	public String getInscode() {
		return this.inscode;
	}

	public void setInscode(String inscode) {
		this.inscode = inscode;
	}

	@Column(name = "INSBEGINDATE", length = 20)
	public String getInsbegindate() {
		return this.insbegindate;
	}

	public void setInsbegindate(String insbegindate) {
		this.insbegindate = insbegindate;
	}

	@Column(name = "INSENDDATE", length = 20)
	public String getInsenddate() {
		return this.insenddate;
	}

	public void setInsenddate(String insenddate) {
		this.insenddate = insenddate;
	}

	@Column(name = "INJURYINSCODE", length = 40)
	public String getInjuryinscode() {
		return this.injuryinscode;
	}

	public void setInjuryinscode(String injuryinscode) {
		this.injuryinscode = injuryinscode;
	}

	@Column(name = "DISPATCHCODE", length = 10)
	public String getDispatchcode() {
		return this.dispatchcode;
	}

	public void setDispatchcode(String dispatchcode) {
		this.dispatchcode = dispatchcode;
	}

	@Column(name = "DISPATCHTIME", length = 20)
	public String getDispatchtime() {
		return this.dispatchtime;
	}

	public void setDispatchtime(String dispatchtime) {
		this.dispatchtime = dispatchtime;
	}

	@Column(name = "FEEDBACKTIME", length = 20)
	public String getFeedbacktime() {
		return this.feedbacktime;
	}

	public void setFeedbacktime(String feedbacktime) {
		this.feedbacktime = feedbacktime;
	}

	@Column(name = "YKTCODE", length = 10)
	public String getYktcode() {
		return this.yktcode;
	}

	public void setYktcode(String yktcode) {
		this.yktcode = yktcode;
	}

	@Column(name = "PKCORP", length = 4)
	public String getPkcorp() {
		return this.pkcorp;
	}

	public void setPkcorp(String pkcorp) {
		this.pkcorp = pkcorp;
	}

}
