package com.nts.teststruts.model;
// Generated 2016-4-27 10:12:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HiPsndocGrpdef4 generated by hbm2java
 */
@Entity
@Table(name = "HI_PSNDOC_GRPDEF4", schema = "NC58")
public class HiPsndocGrpdef4 implements java.io.Serializable {

	private String pkPsndocSub;
	private BigDecimal approveflag;
	private String begindate;
	private Long dr;
	private String enddate;
	private String groupdef1;
	private String groupdef10;
	private String groupdef2;
	private String groupdef3;
	private String groupdef4;
	private String groupdef5;
	private String groupdef6;
	private String groupdef7;
	private String groupdef8;
	private String groupdef9;
	private String hroperator;
	private Character lastflag;
	private String period;
	private String pkPsnbasdoc;
	private String pkPsndoc;
	private BigDecimal recordnum;
	private String ts;

	public HiPsndocGrpdef4() {
	}

	public HiPsndocGrpdef4(String pkPsndocSub) {
		this.pkPsndocSub = pkPsndocSub;
	}

	public HiPsndocGrpdef4(String pkPsndocSub, BigDecimal approveflag, String begindate, Long dr, String enddate,
			String groupdef1, String groupdef10, String groupdef2, String groupdef3, String groupdef4, String groupdef5,
			String groupdef6, String groupdef7, String groupdef8, String groupdef9, String hroperator,
			Character lastflag, String period, String pkPsnbasdoc, String pkPsndoc, BigDecimal recordnum, String ts) {
		this.pkPsndocSub = pkPsndocSub;
		this.approveflag = approveflag;
		this.begindate = begindate;
		this.dr = dr;
		this.enddate = enddate;
		this.groupdef1 = groupdef1;
		this.groupdef10 = groupdef10;
		this.groupdef2 = groupdef2;
		this.groupdef3 = groupdef3;
		this.groupdef4 = groupdef4;
		this.groupdef5 = groupdef5;
		this.groupdef6 = groupdef6;
		this.groupdef7 = groupdef7;
		this.groupdef8 = groupdef8;
		this.groupdef9 = groupdef9;
		this.hroperator = hroperator;
		this.lastflag = lastflag;
		this.period = period;
		this.pkPsnbasdoc = pkPsnbasdoc;
		this.pkPsndoc = pkPsndoc;
		this.recordnum = recordnum;
		this.ts = ts;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "PK_PSNDOC_SUB", unique = true, nullable = false, length = 20)
	public String getPkPsndocSub() {
		return this.pkPsndocSub;
	}

	public void setPkPsndocSub(String pkPsndocSub) {
		this.pkPsndocSub = pkPsndocSub;
	}

	@Column(name = "APPROVEFLAG", precision = 38, scale = 0)
	public BigDecimal getApproveflag() {
		return this.approveflag;
	}

	public void setApproveflag(BigDecimal approveflag) {
		this.approveflag = approveflag;
	}

	@Column(name = "BEGINDATE", length = 10)
	public String getBegindate() {
		return this.begindate;
	}

	public void setBegindate(String begindate) {
		this.begindate = begindate;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "ENDDATE", length = 10)
	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	@Column(name = "GROUPDEF1", length = 128)
	public String getGroupdef1() {
		return this.groupdef1;
	}

	public void setGroupdef1(String groupdef1) {
		this.groupdef1 = groupdef1;
	}

	@Column(name = "GROUPDEF10", length = 128)
	public String getGroupdef10() {
		return this.groupdef10;
	}

	public void setGroupdef10(String groupdef10) {
		this.groupdef10 = groupdef10;
	}

	@Column(name = "GROUPDEF2", length = 128)
	public String getGroupdef2() {
		return this.groupdef2;
	}

	public void setGroupdef2(String groupdef2) {
		this.groupdef2 = groupdef2;
	}

	@Column(name = "GROUPDEF3", length = 128)
	public String getGroupdef3() {
		return this.groupdef3;
	}

	public void setGroupdef3(String groupdef3) {
		this.groupdef3 = groupdef3;
	}

	@Column(name = "GROUPDEF4", length = 128)
	public String getGroupdef4() {
		return this.groupdef4;
	}

	public void setGroupdef4(String groupdef4) {
		this.groupdef4 = groupdef4;
	}

	@Column(name = "GROUPDEF5", length = 128)
	public String getGroupdef5() {
		return this.groupdef5;
	}

	public void setGroupdef5(String groupdef5) {
		this.groupdef5 = groupdef5;
	}

	@Column(name = "GROUPDEF6", length = 128)
	public String getGroupdef6() {
		return this.groupdef6;
	}

	public void setGroupdef6(String groupdef6) {
		this.groupdef6 = groupdef6;
	}

	@Column(name = "GROUPDEF7", length = 128)
	public String getGroupdef7() {
		return this.groupdef7;
	}

	public void setGroupdef7(String groupdef7) {
		this.groupdef7 = groupdef7;
	}

	@Column(name = "GROUPDEF8", length = 128)
	public String getGroupdef8() {
		return this.groupdef8;
	}

	public void setGroupdef8(String groupdef8) {
		this.groupdef8 = groupdef8;
	}

	@Column(name = "GROUPDEF9", length = 128)
	public String getGroupdef9() {
		return this.groupdef9;
	}

	public void setGroupdef9(String groupdef9) {
		this.groupdef9 = groupdef9;
	}

	@Column(name = "HROPERATOR", length = 20)
	public String getHroperator() {
		return this.hroperator;
	}

	public void setHroperator(String hroperator) {
		this.hroperator = hroperator;
	}

	@Column(name = "LASTFLAG", length = 1)
	public Character getLastflag() {
		return this.lastflag;
	}

	public void setLastflag(Character lastflag) {
		this.lastflag = lastflag;
	}

	@Column(name = "PERIOD", length = 10)
	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	@Column(name = "PK_PSNBASDOC", length = 20)
	public String getPkPsnbasdoc() {
		return this.pkPsnbasdoc;
	}

	public void setPkPsnbasdoc(String pkPsnbasdoc) {
		this.pkPsnbasdoc = pkPsnbasdoc;
	}

	@Column(name = "PK_PSNDOC", length = 20)
	public String getPkPsndoc() {
		return this.pkPsndoc;
	}

	public void setPkPsndoc(String pkPsndoc) {
		this.pkPsndoc = pkPsndoc;
	}

	@Column(name = "RECORDNUM", precision = 38, scale = 0)
	public BigDecimal getRecordnum() {
		return this.recordnum;
	}

	public void setRecordnum(BigDecimal recordnum) {
		this.recordnum = recordnum;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

}
