package com.nts.teststruts.model;
// Generated 2015-7-24 10:07:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IcSapplyH generated by hbm2java
 */
@Entity
@Table(name = "IC_SAPPLY_H", schema = "NC58")
public class IcSapplyH implements java.io.Serializable {

	private String sapplyHid;
	private String approver;
	private String cbizid;
	private String cdptid;
	private String dapprovedate;
	private String dbilldate;
	private Long dr;
	private BigDecimal fstatusflag;
	private BigDecimal iprintcount;
	private String modifiedtime;
	private String modifier;
	private String operator;
	private String pkCorp;
	private String pkDefdoc1;
	private String pkDefdoc10;
	private String pkDefdoc11;
	private String pkDefdoc12;
	private String pkDefdoc13;
	private String pkDefdoc14;
	private String pkDefdoc15;
	private String pkDefdoc16;
	private String pkDefdoc17;
	private String pkDefdoc18;
	private String pkDefdoc19;
	private String pkDefdoc2;
	private String pkDefdoc20;
	private String pkDefdoc3;
	private String pkDefdoc4;
	private String pkDefdoc5;
	private String pkDefdoc6;
	private String pkDefdoc7;
	private String pkDefdoc8;
	private String pkDefdoc9;
	private String pkOrgId;
	private String sapplydbilldate;
	private String taudittime;
	private String tmaketime;
	private BigDecimal totalnum;
	private String ts;
	private String vbillcode;
	private String vnote;
	private String vuserdef1;
	private String vuserdef10;
	private String vuserdef11;
	private String vuserdef12;
	private String vuserdef13;
	private String vuserdef14;
	private String vuserdef15;
	private String vuserdef16;
	private String vuserdef17;
	private String vuserdef18;
	private String vuserdef19;
	private String vuserdef2;
	private String vuserdef20;
	private String vuserdef3;
	private String vuserdef4;
	private String vuserdef5;
	private String vuserdef6;
	private String vuserdef7;
	private String vuserdef8;
	private String vuserdef9;

	public IcSapplyH() {
	}

	public IcSapplyH(String sapplyHid, String dbilldate, String pkOrgId, String sapplydbilldate, String vbillcode) {
		this.sapplyHid = sapplyHid;
		this.dbilldate = dbilldate;
		this.pkOrgId = pkOrgId;
		this.sapplydbilldate = sapplydbilldate;
		this.vbillcode = vbillcode;
	}

	public IcSapplyH(String sapplyHid, String approver, String cbizid, String cdptid, String dapprovedate,
			String dbilldate, Long dr, BigDecimal fstatusflag, BigDecimal iprintcount, String modifiedtime,
			String modifier, String operator, String pkCorp, String pkDefdoc1, String pkDefdoc10, String pkDefdoc11,
			String pkDefdoc12, String pkDefdoc13, String pkDefdoc14, String pkDefdoc15, String pkDefdoc16,
			String pkDefdoc17, String pkDefdoc18, String pkDefdoc19, String pkDefdoc2, String pkDefdoc20,
			String pkDefdoc3, String pkDefdoc4, String pkDefdoc5, String pkDefdoc6, String pkDefdoc7, String pkDefdoc8,
			String pkDefdoc9, String pkOrgId, String sapplydbilldate, String taudittime, String tmaketime,
			BigDecimal totalnum, String ts, String vbillcode, String vnote, String vuserdef1, String vuserdef10,
			String vuserdef11, String vuserdef12, String vuserdef13, String vuserdef14, String vuserdef15,
			String vuserdef16, String vuserdef17, String vuserdef18, String vuserdef19, String vuserdef2,
			String vuserdef20, String vuserdef3, String vuserdef4, String vuserdef5, String vuserdef6, String vuserdef7,
			String vuserdef8, String vuserdef9) {
		this.sapplyHid = sapplyHid;
		this.approver = approver;
		this.cbizid = cbizid;
		this.cdptid = cdptid;
		this.dapprovedate = dapprovedate;
		this.dbilldate = dbilldate;
		this.dr = dr;
		this.fstatusflag = fstatusflag;
		this.iprintcount = iprintcount;
		this.modifiedtime = modifiedtime;
		this.modifier = modifier;
		this.operator = operator;
		this.pkCorp = pkCorp;
		this.pkDefdoc1 = pkDefdoc1;
		this.pkDefdoc10 = pkDefdoc10;
		this.pkDefdoc11 = pkDefdoc11;
		this.pkDefdoc12 = pkDefdoc12;
		this.pkDefdoc13 = pkDefdoc13;
		this.pkDefdoc14 = pkDefdoc14;
		this.pkDefdoc15 = pkDefdoc15;
		this.pkDefdoc16 = pkDefdoc16;
		this.pkDefdoc17 = pkDefdoc17;
		this.pkDefdoc18 = pkDefdoc18;
		this.pkDefdoc19 = pkDefdoc19;
		this.pkDefdoc2 = pkDefdoc2;
		this.pkDefdoc20 = pkDefdoc20;
		this.pkDefdoc3 = pkDefdoc3;
		this.pkDefdoc4 = pkDefdoc4;
		this.pkDefdoc5 = pkDefdoc5;
		this.pkDefdoc6 = pkDefdoc6;
		this.pkDefdoc7 = pkDefdoc7;
		this.pkDefdoc8 = pkDefdoc8;
		this.pkDefdoc9 = pkDefdoc9;
		this.pkOrgId = pkOrgId;
		this.sapplydbilldate = sapplydbilldate;
		this.taudittime = taudittime;
		this.tmaketime = tmaketime;
		this.totalnum = totalnum;
		this.ts = ts;
		this.vbillcode = vbillcode;
		this.vnote = vnote;
		this.vuserdef1 = vuserdef1;
		this.vuserdef10 = vuserdef10;
		this.vuserdef11 = vuserdef11;
		this.vuserdef12 = vuserdef12;
		this.vuserdef13 = vuserdef13;
		this.vuserdef14 = vuserdef14;
		this.vuserdef15 = vuserdef15;
		this.vuserdef16 = vuserdef16;
		this.vuserdef17 = vuserdef17;
		this.vuserdef18 = vuserdef18;
		this.vuserdef19 = vuserdef19;
		this.vuserdef2 = vuserdef2;
		this.vuserdef20 = vuserdef20;
		this.vuserdef3 = vuserdef3;
		this.vuserdef4 = vuserdef4;
		this.vuserdef5 = vuserdef5;
		this.vuserdef6 = vuserdef6;
		this.vuserdef7 = vuserdef7;
		this.vuserdef8 = vuserdef8;
		this.vuserdef9 = vuserdef9;
	}

	@Id

	@Column(name = "SAPPLY_HID", unique = true, nullable = false, length = 20)
	public String getSapplyHid() {
		return this.sapplyHid;
	}

	public void setSapplyHid(String sapplyHid) {
		this.sapplyHid = sapplyHid;
	}

	@Column(name = "APPROVER", length = 20)
	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	@Column(name = "CBIZID", length = 20)
	public String getCbizid() {
		return this.cbizid;
	}

	public void setCbizid(String cbizid) {
		this.cbizid = cbizid;
	}

	@Column(name = "CDPTID", length = 20)
	public String getCdptid() {
		return this.cdptid;
	}

	public void setCdptid(String cdptid) {
		this.cdptid = cdptid;
	}

	@Column(name = "DAPPROVEDATE", length = 10)
	public String getDapprovedate() {
		return this.dapprovedate;
	}

	public void setDapprovedate(String dapprovedate) {
		this.dapprovedate = dapprovedate;
	}

	@Column(name = "DBILLDATE", nullable = false, length = 10)
	public String getDbilldate() {
		return this.dbilldate;
	}

	public void setDbilldate(String dbilldate) {
		this.dbilldate = dbilldate;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "FSTATUSFLAG", precision = 38, scale = 0)
	public BigDecimal getFstatusflag() {
		return this.fstatusflag;
	}

	public void setFstatusflag(BigDecimal fstatusflag) {
		this.fstatusflag = fstatusflag;
	}

	@Column(name = "IPRINTCOUNT", precision = 38, scale = 0)
	public BigDecimal getIprintcount() {
		return this.iprintcount;
	}

	public void setIprintcount(BigDecimal iprintcount) {
		this.iprintcount = iprintcount;
	}

	@Column(name = "MODIFIEDTIME", length = 19)
	public String getModifiedtime() {
		return this.modifiedtime;
	}

	public void setModifiedtime(String modifiedtime) {
		this.modifiedtime = modifiedtime;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Column(name = "OPERATOR", length = 20)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_DEFDOC1", length = 20)
	public String getPkDefdoc1() {
		return this.pkDefdoc1;
	}

	public void setPkDefdoc1(String pkDefdoc1) {
		this.pkDefdoc1 = pkDefdoc1;
	}

	@Column(name = "PK_DEFDOC10", length = 20)
	public String getPkDefdoc10() {
		return this.pkDefdoc10;
	}

	public void setPkDefdoc10(String pkDefdoc10) {
		this.pkDefdoc10 = pkDefdoc10;
	}

	@Column(name = "PK_DEFDOC11", length = 20)
	public String getPkDefdoc11() {
		return this.pkDefdoc11;
	}

	public void setPkDefdoc11(String pkDefdoc11) {
		this.pkDefdoc11 = pkDefdoc11;
	}

	@Column(name = "PK_DEFDOC12", length = 20)
	public String getPkDefdoc12() {
		return this.pkDefdoc12;
	}

	public void setPkDefdoc12(String pkDefdoc12) {
		this.pkDefdoc12 = pkDefdoc12;
	}

	@Column(name = "PK_DEFDOC13", length = 20)
	public String getPkDefdoc13() {
		return this.pkDefdoc13;
	}

	public void setPkDefdoc13(String pkDefdoc13) {
		this.pkDefdoc13 = pkDefdoc13;
	}

	@Column(name = "PK_DEFDOC14", length = 20)
	public String getPkDefdoc14() {
		return this.pkDefdoc14;
	}

	public void setPkDefdoc14(String pkDefdoc14) {
		this.pkDefdoc14 = pkDefdoc14;
	}

	@Column(name = "PK_DEFDOC15", length = 20)
	public String getPkDefdoc15() {
		return this.pkDefdoc15;
	}

	public void setPkDefdoc15(String pkDefdoc15) {
		this.pkDefdoc15 = pkDefdoc15;
	}

	@Column(name = "PK_DEFDOC16", length = 20)
	public String getPkDefdoc16() {
		return this.pkDefdoc16;
	}

	public void setPkDefdoc16(String pkDefdoc16) {
		this.pkDefdoc16 = pkDefdoc16;
	}

	@Column(name = "PK_DEFDOC17", length = 20)
	public String getPkDefdoc17() {
		return this.pkDefdoc17;
	}

	public void setPkDefdoc17(String pkDefdoc17) {
		this.pkDefdoc17 = pkDefdoc17;
	}

	@Column(name = "PK_DEFDOC18", length = 20)
	public String getPkDefdoc18() {
		return this.pkDefdoc18;
	}

	public void setPkDefdoc18(String pkDefdoc18) {
		this.pkDefdoc18 = pkDefdoc18;
	}

	@Column(name = "PK_DEFDOC19", length = 20)
	public String getPkDefdoc19() {
		return this.pkDefdoc19;
	}

	public void setPkDefdoc19(String pkDefdoc19) {
		this.pkDefdoc19 = pkDefdoc19;
	}

	@Column(name = "PK_DEFDOC2", length = 20)
	public String getPkDefdoc2() {
		return this.pkDefdoc2;
	}

	public void setPkDefdoc2(String pkDefdoc2) {
		this.pkDefdoc2 = pkDefdoc2;
	}

	@Column(name = "PK_DEFDOC20", length = 20)
	public String getPkDefdoc20() {
		return this.pkDefdoc20;
	}

	public void setPkDefdoc20(String pkDefdoc20) {
		this.pkDefdoc20 = pkDefdoc20;
	}

	@Column(name = "PK_DEFDOC3", length = 20)
	public String getPkDefdoc3() {
		return this.pkDefdoc3;
	}

	public void setPkDefdoc3(String pkDefdoc3) {
		this.pkDefdoc3 = pkDefdoc3;
	}

	@Column(name = "PK_DEFDOC4", length = 20)
	public String getPkDefdoc4() {
		return this.pkDefdoc4;
	}

	public void setPkDefdoc4(String pkDefdoc4) {
		this.pkDefdoc4 = pkDefdoc4;
	}

	@Column(name = "PK_DEFDOC5", length = 20)
	public String getPkDefdoc5() {
		return this.pkDefdoc5;
	}

	public void setPkDefdoc5(String pkDefdoc5) {
		this.pkDefdoc5 = pkDefdoc5;
	}

	@Column(name = "PK_DEFDOC6", length = 20)
	public String getPkDefdoc6() {
		return this.pkDefdoc6;
	}

	public void setPkDefdoc6(String pkDefdoc6) {
		this.pkDefdoc6 = pkDefdoc6;
	}

	@Column(name = "PK_DEFDOC7", length = 20)
	public String getPkDefdoc7() {
		return this.pkDefdoc7;
	}

	public void setPkDefdoc7(String pkDefdoc7) {
		this.pkDefdoc7 = pkDefdoc7;
	}

	@Column(name = "PK_DEFDOC8", length = 20)
	public String getPkDefdoc8() {
		return this.pkDefdoc8;
	}

	public void setPkDefdoc8(String pkDefdoc8) {
		this.pkDefdoc8 = pkDefdoc8;
	}

	@Column(name = "PK_DEFDOC9", length = 20)
	public String getPkDefdoc9() {
		return this.pkDefdoc9;
	}

	public void setPkDefdoc9(String pkDefdoc9) {
		this.pkDefdoc9 = pkDefdoc9;
	}

	@Column(name = "PK_ORG_ID", nullable = false, length = 20)
	public String getPkOrgId() {
		return this.pkOrgId;
	}

	public void setPkOrgId(String pkOrgId) {
		this.pkOrgId = pkOrgId;
	}

	@Column(name = "SAPPLYDBILLDATE", nullable = false, length = 10)
	public String getSapplydbilldate() {
		return this.sapplydbilldate;
	}

	public void setSapplydbilldate(String sapplydbilldate) {
		this.sapplydbilldate = sapplydbilldate;
	}

	@Column(name = "TAUDITTIME", length = 19)
	public String getTaudittime() {
		return this.taudittime;
	}

	public void setTaudittime(String taudittime) {
		this.taudittime = taudittime;
	}

	@Column(name = "TMAKETIME", length = 19)
	public String getTmaketime() {
		return this.tmaketime;
	}

	public void setTmaketime(String tmaketime) {
		this.tmaketime = tmaketime;
	}

	@Column(name = "TOTALNUM", precision = 20, scale = 8)
	public BigDecimal getTotalnum() {
		return this.totalnum;
	}

	public void setTotalnum(BigDecimal totalnum) {
		this.totalnum = totalnum;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "VBILLCODE", nullable = false, length = 30)
	public String getVbillcode() {
		return this.vbillcode;
	}

	public void setVbillcode(String vbillcode) {
		this.vbillcode = vbillcode;
	}

	@Column(name = "VNOTE", length = 181)
	public String getVnote() {
		return this.vnote;
	}

	public void setVnote(String vnote) {
		this.vnote = vnote;
	}

	@Column(name = "VUSERDEF1", length = 100)
	public String getVuserdef1() {
		return this.vuserdef1;
	}

	public void setVuserdef1(String vuserdef1) {
		this.vuserdef1 = vuserdef1;
	}

	@Column(name = "VUSERDEF10", length = 100)
	public String getVuserdef10() {
		return this.vuserdef10;
	}

	public void setVuserdef10(String vuserdef10) {
		this.vuserdef10 = vuserdef10;
	}

	@Column(name = "VUSERDEF11", length = 100)
	public String getVuserdef11() {
		return this.vuserdef11;
	}

	public void setVuserdef11(String vuserdef11) {
		this.vuserdef11 = vuserdef11;
	}

	@Column(name = "VUSERDEF12", length = 100)
	public String getVuserdef12() {
		return this.vuserdef12;
	}

	public void setVuserdef12(String vuserdef12) {
		this.vuserdef12 = vuserdef12;
	}

	@Column(name = "VUSERDEF13", length = 100)
	public String getVuserdef13() {
		return this.vuserdef13;
	}

	public void setVuserdef13(String vuserdef13) {
		this.vuserdef13 = vuserdef13;
	}

	@Column(name = "VUSERDEF14", length = 100)
	public String getVuserdef14() {
		return this.vuserdef14;
	}

	public void setVuserdef14(String vuserdef14) {
		this.vuserdef14 = vuserdef14;
	}

	@Column(name = "VUSERDEF15", length = 100)
	public String getVuserdef15() {
		return this.vuserdef15;
	}

	public void setVuserdef15(String vuserdef15) {
		this.vuserdef15 = vuserdef15;
	}

	@Column(name = "VUSERDEF16", length = 100)
	public String getVuserdef16() {
		return this.vuserdef16;
	}

	public void setVuserdef16(String vuserdef16) {
		this.vuserdef16 = vuserdef16;
	}

	@Column(name = "VUSERDEF17", length = 100)
	public String getVuserdef17() {
		return this.vuserdef17;
	}

	public void setVuserdef17(String vuserdef17) {
		this.vuserdef17 = vuserdef17;
	}

	@Column(name = "VUSERDEF18", length = 100)
	public String getVuserdef18() {
		return this.vuserdef18;
	}

	public void setVuserdef18(String vuserdef18) {
		this.vuserdef18 = vuserdef18;
	}

	@Column(name = "VUSERDEF19", length = 100)
	public String getVuserdef19() {
		return this.vuserdef19;
	}

	public void setVuserdef19(String vuserdef19) {
		this.vuserdef19 = vuserdef19;
	}

	@Column(name = "VUSERDEF2", length = 100)
	public String getVuserdef2() {
		return this.vuserdef2;
	}

	public void setVuserdef2(String vuserdef2) {
		this.vuserdef2 = vuserdef2;
	}

	@Column(name = "VUSERDEF20", length = 100)
	public String getVuserdef20() {
		return this.vuserdef20;
	}

	public void setVuserdef20(String vuserdef20) {
		this.vuserdef20 = vuserdef20;
	}

	@Column(name = "VUSERDEF3", length = 100)
	public String getVuserdef3() {
		return this.vuserdef3;
	}

	public void setVuserdef3(String vuserdef3) {
		this.vuserdef3 = vuserdef3;
	}

	@Column(name = "VUSERDEF4", length = 100)
	public String getVuserdef4() {
		return this.vuserdef4;
	}

	public void setVuserdef4(String vuserdef4) {
		this.vuserdef4 = vuserdef4;
	}

	@Column(name = "VUSERDEF5", length = 100)
	public String getVuserdef5() {
		return this.vuserdef5;
	}

	public void setVuserdef5(String vuserdef5) {
		this.vuserdef5 = vuserdef5;
	}

	@Column(name = "VUSERDEF6", length = 100)
	public String getVuserdef6() {
		return this.vuserdef6;
	}

	public void setVuserdef6(String vuserdef6) {
		this.vuserdef6 = vuserdef6;
	}

	@Column(name = "VUSERDEF7", length = 100)
	public String getVuserdef7() {
		return this.vuserdef7;
	}

	public void setVuserdef7(String vuserdef7) {
		this.vuserdef7 = vuserdef7;
	}

	@Column(name = "VUSERDEF8", length = 100)
	public String getVuserdef8() {
		return this.vuserdef8;
	}

	public void setVuserdef8(String vuserdef8) {
		this.vuserdef8 = vuserdef8;
	}

	@Column(name = "VUSERDEF9", length = 100)
	public String getVuserdef9() {
		return this.vuserdef9;
	}

	public void setVuserdef9(String vuserdef9) {
		this.vuserdef9 = vuserdef9;
	}

}
