package com.nts.teststruts.model;
// Generated 2015-8-4 15:18:46 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PamCategory generated by hbm2java
 */
@Entity
@Table(name = "PAM_CATEGORY", schema = "NC58")
public class PamCategory implements java.io.Serializable {

	private String pkCategory;
	private Character associateFaFlag;
	private String categoryCode;
	private String categoryName;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private Long dr;
	private String fkParent;
	private String freeitem1;
	private String freeitem10;
	private String freeitem11;
	private String freeitem12;
	private String freeitem13;
	private String freeitem14;
	private String freeitem15;
	private String freeitem16;
	private String freeitem17;
	private String freeitem18;
	private String freeitem19;
	private String freeitem2;
	private String freeitem20;
	private String freeitem3;
	private String freeitem4;
	private String freeitem5;
	private String freeitem6;
	private String freeitem7;
	private String freeitem8;
	private String freeitem9;
	private String innerCode;
	private Character invFlag;
	private Character lockFlag;
	private String maxInnerCode;
	private String memo;
	private Character namePreFlag;
	private String pkAmorg;
	private String pkCorp;
	private Character specialFlag;
	private String ts;

	public PamCategory() {
	}

	public PamCategory(String pkCategory) {
		this.pkCategory = pkCategory;
	}

	public PamCategory(String pkCategory, Character associateFaFlag, String categoryCode, String categoryName,
			String def1, String def10, String def11, String def12, String def13, String def14, String def15,
			String def16, String def17, String def18, String def19, String def2, String def20, String def3, String def4,
			String def5, String def6, String def7, String def8, String def9, Long dr, String fkParent, String freeitem1,
			String freeitem10, String freeitem11, String freeitem12, String freeitem13, String freeitem14,
			String freeitem15, String freeitem16, String freeitem17, String freeitem18, String freeitem19,
			String freeitem2, String freeitem20, String freeitem3, String freeitem4, String freeitem5, String freeitem6,
			String freeitem7, String freeitem8, String freeitem9, String innerCode, Character invFlag,
			Character lockFlag, String maxInnerCode, String memo, Character namePreFlag, String pkAmorg, String pkCorp,
			Character specialFlag, String ts) {
		this.pkCategory = pkCategory;
		this.associateFaFlag = associateFaFlag;
		this.categoryCode = categoryCode;
		this.categoryName = categoryName;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def3 = def3;
		this.def4 = def4;
		this.def5 = def5;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.dr = dr;
		this.fkParent = fkParent;
		this.freeitem1 = freeitem1;
		this.freeitem10 = freeitem10;
		this.freeitem11 = freeitem11;
		this.freeitem12 = freeitem12;
		this.freeitem13 = freeitem13;
		this.freeitem14 = freeitem14;
		this.freeitem15 = freeitem15;
		this.freeitem16 = freeitem16;
		this.freeitem17 = freeitem17;
		this.freeitem18 = freeitem18;
		this.freeitem19 = freeitem19;
		this.freeitem2 = freeitem2;
		this.freeitem20 = freeitem20;
		this.freeitem3 = freeitem3;
		this.freeitem4 = freeitem4;
		this.freeitem5 = freeitem5;
		this.freeitem6 = freeitem6;
		this.freeitem7 = freeitem7;
		this.freeitem8 = freeitem8;
		this.freeitem9 = freeitem9;
		this.innerCode = innerCode;
		this.invFlag = invFlag;
		this.lockFlag = lockFlag;
		this.maxInnerCode = maxInnerCode;
		this.memo = memo;
		this.namePreFlag = namePreFlag;
		this.pkAmorg = pkAmorg;
		this.pkCorp = pkCorp;
		this.specialFlag = specialFlag;
		this.ts = ts;
	}

	@Id

	@Column(name = "PK_CATEGORY", unique = true, nullable = false, length = 20)
	public String getPkCategory() {
		return this.pkCategory;
	}

	public void setPkCategory(String pkCategory) {
		this.pkCategory = pkCategory;
	}

	@Column(name = "ASSOCIATE_FA_FLAG", length = 1)
	public Character getAssociateFaFlag() {
		return this.associateFaFlag;
	}

	public void setAssociateFaFlag(Character associateFaFlag) {
		this.associateFaFlag = associateFaFlag;
	}

	@Column(name = "CATEGORY_CODE", length = 28)
	public String getCategoryCode() {
		return this.categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	@Column(name = "CATEGORY_NAME", length = 75)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "DEF1", length = 128)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 128)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 128)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 128)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 128)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 128)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 128)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 128)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 128)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 128)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 128)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 128)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 128)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF3", length = 128)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF4", length = 128)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF5", length = 128)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF6", length = 128)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 128)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 128)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 128)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "FK_PARENT", length = 20)
	public String getFkParent() {
		return this.fkParent;
	}

	public void setFkParent(String fkParent) {
		this.fkParent = fkParent;
	}

	@Column(name = "FREEITEM1", length = 45)
	public String getFreeitem1() {
		return this.freeitem1;
	}

	public void setFreeitem1(String freeitem1) {
		this.freeitem1 = freeitem1;
	}

	@Column(name = "FREEITEM10", length = 45)
	public String getFreeitem10() {
		return this.freeitem10;
	}

	public void setFreeitem10(String freeitem10) {
		this.freeitem10 = freeitem10;
	}

	@Column(name = "FREEITEM11", length = 45)
	public String getFreeitem11() {
		return this.freeitem11;
	}

	public void setFreeitem11(String freeitem11) {
		this.freeitem11 = freeitem11;
	}

	@Column(name = "FREEITEM12", length = 45)
	public String getFreeitem12() {
		return this.freeitem12;
	}

	public void setFreeitem12(String freeitem12) {
		this.freeitem12 = freeitem12;
	}

	@Column(name = "FREEITEM13", length = 45)
	public String getFreeitem13() {
		return this.freeitem13;
	}

	public void setFreeitem13(String freeitem13) {
		this.freeitem13 = freeitem13;
	}

	@Column(name = "FREEITEM14", length = 45)
	public String getFreeitem14() {
		return this.freeitem14;
	}

	public void setFreeitem14(String freeitem14) {
		this.freeitem14 = freeitem14;
	}

	@Column(name = "FREEITEM15", length = 45)
	public String getFreeitem15() {
		return this.freeitem15;
	}

	public void setFreeitem15(String freeitem15) {
		this.freeitem15 = freeitem15;
	}

	@Column(name = "FREEITEM16", length = 45)
	public String getFreeitem16() {
		return this.freeitem16;
	}

	public void setFreeitem16(String freeitem16) {
		this.freeitem16 = freeitem16;
	}

	@Column(name = "FREEITEM17", length = 45)
	public String getFreeitem17() {
		return this.freeitem17;
	}

	public void setFreeitem17(String freeitem17) {
		this.freeitem17 = freeitem17;
	}

	@Column(name = "FREEITEM18", length = 45)
	public String getFreeitem18() {
		return this.freeitem18;
	}

	public void setFreeitem18(String freeitem18) {
		this.freeitem18 = freeitem18;
	}

	@Column(name = "FREEITEM19", length = 45)
	public String getFreeitem19() {
		return this.freeitem19;
	}

	public void setFreeitem19(String freeitem19) {
		this.freeitem19 = freeitem19;
	}

	@Column(name = "FREEITEM2", length = 45)
	public String getFreeitem2() {
		return this.freeitem2;
	}

	public void setFreeitem2(String freeitem2) {
		this.freeitem2 = freeitem2;
	}

	@Column(name = "FREEITEM20", length = 45)
	public String getFreeitem20() {
		return this.freeitem20;
	}

	public void setFreeitem20(String freeitem20) {
		this.freeitem20 = freeitem20;
	}

	@Column(name = "FREEITEM3", length = 45)
	public String getFreeitem3() {
		return this.freeitem3;
	}

	public void setFreeitem3(String freeitem3) {
		this.freeitem3 = freeitem3;
	}

	@Column(name = "FREEITEM4", length = 45)
	public String getFreeitem4() {
		return this.freeitem4;
	}

	public void setFreeitem4(String freeitem4) {
		this.freeitem4 = freeitem4;
	}

	@Column(name = "FREEITEM5", length = 45)
	public String getFreeitem5() {
		return this.freeitem5;
	}

	public void setFreeitem5(String freeitem5) {
		this.freeitem5 = freeitem5;
	}

	@Column(name = "FREEITEM6", length = 45)
	public String getFreeitem6() {
		return this.freeitem6;
	}

	public void setFreeitem6(String freeitem6) {
		this.freeitem6 = freeitem6;
	}

	@Column(name = "FREEITEM7", length = 45)
	public String getFreeitem7() {
		return this.freeitem7;
	}

	public void setFreeitem7(String freeitem7) {
		this.freeitem7 = freeitem7;
	}

	@Column(name = "FREEITEM8", length = 45)
	public String getFreeitem8() {
		return this.freeitem8;
	}

	public void setFreeitem8(String freeitem8) {
		this.freeitem8 = freeitem8;
	}

	@Column(name = "FREEITEM9", length = 45)
	public String getFreeitem9() {
		return this.freeitem9;
	}

	public void setFreeitem9(String freeitem9) {
		this.freeitem9 = freeitem9;
	}

	@Column(name = "INNER_CODE", length = 60)
	public String getInnerCode() {
		return this.innerCode;
	}

	public void setInnerCode(String innerCode) {
		this.innerCode = innerCode;
	}

	@Column(name = "INV_FLAG", length = 1)
	public Character getInvFlag() {
		return this.invFlag;
	}

	public void setInvFlag(Character invFlag) {
		this.invFlag = invFlag;
	}

	@Column(name = "LOCK_FLAG", length = 1)
	public Character getLockFlag() {
		return this.lockFlag;
	}

	public void setLockFlag(Character lockFlag) {
		this.lockFlag = lockFlag;
	}

	@Column(name = "MAX_INNER_CODE", length = 60)
	public String getMaxInnerCode() {
		return this.maxInnerCode;
	}

	public void setMaxInnerCode(String maxInnerCode) {
		this.maxInnerCode = maxInnerCode;
	}

	@Column(name = "MEMO", length = 150)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "NAME_PRE_FLAG", length = 1)
	public Character getNamePreFlag() {
		return this.namePreFlag;
	}

	public void setNamePreFlag(Character namePreFlag) {
		this.namePreFlag = namePreFlag;
	}

	@Column(name = "PK_AMORG", length = 20)
	public String getPkAmorg() {
		return this.pkAmorg;
	}

	public void setPkAmorg(String pkAmorg) {
		this.pkAmorg = pkAmorg;
	}

	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "SPECIAL_FLAG", length = 1)
	public Character getSpecialFlag() {
		return this.specialFlag;
	}

	public void setSpecialFlag(Character specialFlag) {
		this.specialFlag = specialFlag;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

}
