package com.nts.teststruts.model;
// Generated 2015-8-4 15:18:46 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PamEquip generated by hbm2java
 */
@Entity
@Table(name = "PAM_EQUIP", schema = "NC58")
public class PamEquip implements java.io.Serializable {

	private String pkEquip;
	private BigDecimal accuDep;
	private Character assignFlag;
	private Character associateFlag;
	private String barCode;
	private String billCodeDist;
	private String billCodeSrc;
	private String billTypeDist;
	private String billTypeSrc;
	private Character borrowFlag;
	private String checkPeriod;
	private String checkPeriodName;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def21;
	private String def22;
	private String def23;
	private String def24;
	private String def25;
	private String def26;
	private String def27;
	private String def28;
	private String def29;
	private String def3;
	private String def30;
	private String def31;
	private String def32;
	private String def33;
	private String def34;
	private String def35;
	private String def36;
	private String def37;
	private String def38;
	private String def39;
	private String def4;
	private String def40;
	private String def41;
	private String def42;
	private String def43;
	private String def44;
	private String def45;
	private String def46;
	private String def47;
	private String def48;
	private String def49;
	private String def5;
	private String def50;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private BigDecimal depAmount;
	private Long dr;
	private String equipCode;
	private String equipName;
	private Character faFlag;
	private String facturerName;
	private String fkParent;
	private String freeitem1;
	private String freeitem10;
	private String freeitem11;
	private String freeitem12;
	private String freeitem13;
	private String freeitem14;
	private String freeitem15;
	private String freeitem16;
	private String freeitem17;
	private String freeitem18;
	private String freeitem19;
	private String freeitem2;
	private String freeitem20;
	private String freeitem3;
	private String freeitem4;
	private String freeitem5;
	private String freeitem6;
	private String freeitem7;
	private String freeitem8;
	private String freeitem9;
	private BigDecimal installFee;
	private String lastMroDate;
	private String latestCheckDate;
	private Character lockFlag;
	private String makeDate;
	private String model;
	private Character mortgageFlag;
	private BigDecimal mroFrequency;
	private String mroUnit;
	private BigDecimal netMoney;
	private BigDecimal newValue;
	private String nextCheckDate;
	private BigDecimal originValue;
	private Character outFlag;
	private String pkAmorg;
	private String pkAmorgDist;
	private String pkAmorgSrc;
	private String pkBillBDist;
	private String pkBillBSrc;
	private String pkBillDist;
	private String pkBillSrc;
	private String pkCalendar;
	private String pkCapitalSource;
	private String pkCard;
	private String pkCategory;
	private String pkCorp;
	private String pkCorpDist;
	private String pkCorpOwner;
	private String pkCorpSrc;
	private String pkCorpUsed;
	private String pkCusmandocOwner;
	private String pkCusmandocUsed;
	private String pkInvbasedoc;
	private String pkJobmngfil;
	private String pkLocation;
	private String pkMaker;
	private String pkManager;
	private String pkMandept;
	private String pkPriority;
	private String pkRack;
	private String pkSource;
	private String pkSrcDist;
	private String pkSupplier;
	private String pkUpdater;
	private String pkUsedStatus;
	private String pkUsedept;
	private String pkUsedeptDist;
	private String pkUsedeptSrc;
	private String pkUser;
	private String preCheckDate;
	private BigDecimal preDevaluate;
	private String preMroDate;
	private String preText1;
	private String preText10;
	private String preText2;
	private String preText3;
	private String preText4;
	private String preText5;
	private String preText6;
	private String preText7;
	private String preText8;
	private String preText9;
	private String precoding;
	private BigDecimal purcPrice;
	private BigDecimal purcPriceTax;
	private Character reduceFlag;
	private Character rentFlag;
	private BigDecimal salvageRate;
	private String serialNum;
	private BigDecimal serviceMonth;
	private Character snFlag;
	private String spec;
	private Character specialFlag;
	private String startUsedDate;
	private String statusDate;
	private BigDecimal tax;
	private String transiTypeDist;
	private String transiTypeSrc;
	private String ts;
	private String updateDate;
	private BigDecimal usedMonth;
	private String usedStatusDate;

	public PamEquip() {
	}

	public PamEquip(String pkEquip) {
		this.pkEquip = pkEquip;
	}

	public PamEquip(String pkEquip, BigDecimal accuDep, Character assignFlag, Character associateFlag, String barCode,
			String billCodeDist, String billCodeSrc, String billTypeDist, String billTypeSrc, Character borrowFlag,
			String checkPeriod, String checkPeriodName, String def1, String def10, String def11, String def12,
			String def13, String def14, String def15, String def16, String def17, String def18, String def19,
			String def2, String def20, String def21, String def22, String def23, String def24, String def25,
			String def26, String def27, String def28, String def29, String def3, String def30, String def31,
			String def32, String def33, String def34, String def35, String def36, String def37, String def38,
			String def39, String def4, String def40, String def41, String def42, String def43, String def44,
			String def45, String def46, String def47, String def48, String def49, String def5, String def50,
			String def6, String def7, String def8, String def9, BigDecimal depAmount, Long dr, String equipCode,
			String equipName, Character faFlag, String facturerName, String fkParent, String freeitem1,
			String freeitem10, String freeitem11, String freeitem12, String freeitem13, String freeitem14,
			String freeitem15, String freeitem16, String freeitem17, String freeitem18, String freeitem19,
			String freeitem2, String freeitem20, String freeitem3, String freeitem4, String freeitem5, String freeitem6,
			String freeitem7, String freeitem8, String freeitem9, BigDecimal installFee, String lastMroDate,
			String latestCheckDate, Character lockFlag, String makeDate, String model, Character mortgageFlag,
			BigDecimal mroFrequency, String mroUnit, BigDecimal netMoney, BigDecimal newValue, String nextCheckDate,
			BigDecimal originValue, Character outFlag, String pkAmorg, String pkAmorgDist, String pkAmorgSrc,
			String pkBillBDist, String pkBillBSrc, String pkBillDist, String pkBillSrc, String pkCalendar,
			String pkCapitalSource, String pkCard, String pkCategory, String pkCorp, String pkCorpDist,
			String pkCorpOwner, String pkCorpSrc, String pkCorpUsed, String pkCusmandocOwner, String pkCusmandocUsed,
			String pkInvbasedoc, String pkJobmngfil, String pkLocation, String pkMaker, String pkManager,
			String pkMandept, String pkPriority, String pkRack, String pkSource, String pkSrcDist, String pkSupplier,
			String pkUpdater, String pkUsedStatus, String pkUsedept, String pkUsedeptDist, String pkUsedeptSrc,
			String pkUser, String preCheckDate, BigDecimal preDevaluate, String preMroDate, String preText1,
			String preText10, String preText2, String preText3, String preText4, String preText5, String preText6,
			String preText7, String preText8, String preText9, String precoding, BigDecimal purcPrice,
			BigDecimal purcPriceTax, Character reduceFlag, Character rentFlag, BigDecimal salvageRate, String serialNum,
			BigDecimal serviceMonth, Character snFlag, String spec, Character specialFlag, String startUsedDate,
			String statusDate, BigDecimal tax, String transiTypeDist, String transiTypeSrc, String ts,
			String updateDate, BigDecimal usedMonth, String usedStatusDate) {
		this.pkEquip = pkEquip;
		this.accuDep = accuDep;
		this.assignFlag = assignFlag;
		this.associateFlag = associateFlag;
		this.barCode = barCode;
		this.billCodeDist = billCodeDist;
		this.billCodeSrc = billCodeSrc;
		this.billTypeDist = billTypeDist;
		this.billTypeSrc = billTypeSrc;
		this.borrowFlag = borrowFlag;
		this.checkPeriod = checkPeriod;
		this.checkPeriodName = checkPeriodName;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def21 = def21;
		this.def22 = def22;
		this.def23 = def23;
		this.def24 = def24;
		this.def25 = def25;
		this.def26 = def26;
		this.def27 = def27;
		this.def28 = def28;
		this.def29 = def29;
		this.def3 = def3;
		this.def30 = def30;
		this.def31 = def31;
		this.def32 = def32;
		this.def33 = def33;
		this.def34 = def34;
		this.def35 = def35;
		this.def36 = def36;
		this.def37 = def37;
		this.def38 = def38;
		this.def39 = def39;
		this.def4 = def4;
		this.def40 = def40;
		this.def41 = def41;
		this.def42 = def42;
		this.def43 = def43;
		this.def44 = def44;
		this.def45 = def45;
		this.def46 = def46;
		this.def47 = def47;
		this.def48 = def48;
		this.def49 = def49;
		this.def5 = def5;
		this.def50 = def50;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.depAmount = depAmount;
		this.dr = dr;
		this.equipCode = equipCode;
		this.equipName = equipName;
		this.faFlag = faFlag;
		this.facturerName = facturerName;
		this.fkParent = fkParent;
		this.freeitem1 = freeitem1;
		this.freeitem10 = freeitem10;
		this.freeitem11 = freeitem11;
		this.freeitem12 = freeitem12;
		this.freeitem13 = freeitem13;
		this.freeitem14 = freeitem14;
		this.freeitem15 = freeitem15;
		this.freeitem16 = freeitem16;
		this.freeitem17 = freeitem17;
		this.freeitem18 = freeitem18;
		this.freeitem19 = freeitem19;
		this.freeitem2 = freeitem2;
		this.freeitem20 = freeitem20;
		this.freeitem3 = freeitem3;
		this.freeitem4 = freeitem4;
		this.freeitem5 = freeitem5;
		this.freeitem6 = freeitem6;
		this.freeitem7 = freeitem7;
		this.freeitem8 = freeitem8;
		this.freeitem9 = freeitem9;
		this.installFee = installFee;
		this.lastMroDate = lastMroDate;
		this.latestCheckDate = latestCheckDate;
		this.lockFlag = lockFlag;
		this.makeDate = makeDate;
		this.model = model;
		this.mortgageFlag = mortgageFlag;
		this.mroFrequency = mroFrequency;
		this.mroUnit = mroUnit;
		this.netMoney = netMoney;
		this.newValue = newValue;
		this.nextCheckDate = nextCheckDate;
		this.originValue = originValue;
		this.outFlag = outFlag;
		this.pkAmorg = pkAmorg;
		this.pkAmorgDist = pkAmorgDist;
		this.pkAmorgSrc = pkAmorgSrc;
		this.pkBillBDist = pkBillBDist;
		this.pkBillBSrc = pkBillBSrc;
		this.pkBillDist = pkBillDist;
		this.pkBillSrc = pkBillSrc;
		this.pkCalendar = pkCalendar;
		this.pkCapitalSource = pkCapitalSource;
		this.pkCard = pkCard;
		this.pkCategory = pkCategory;
		this.pkCorp = pkCorp;
		this.pkCorpDist = pkCorpDist;
		this.pkCorpOwner = pkCorpOwner;
		this.pkCorpSrc = pkCorpSrc;
		this.pkCorpUsed = pkCorpUsed;
		this.pkCusmandocOwner = pkCusmandocOwner;
		this.pkCusmandocUsed = pkCusmandocUsed;
		this.pkInvbasedoc = pkInvbasedoc;
		this.pkJobmngfil = pkJobmngfil;
		this.pkLocation = pkLocation;
		this.pkMaker = pkMaker;
		this.pkManager = pkManager;
		this.pkMandept = pkMandept;
		this.pkPriority = pkPriority;
		this.pkRack = pkRack;
		this.pkSource = pkSource;
		this.pkSrcDist = pkSrcDist;
		this.pkSupplier = pkSupplier;
		this.pkUpdater = pkUpdater;
		this.pkUsedStatus = pkUsedStatus;
		this.pkUsedept = pkUsedept;
		this.pkUsedeptDist = pkUsedeptDist;
		this.pkUsedeptSrc = pkUsedeptSrc;
		this.pkUser = pkUser;
		this.preCheckDate = preCheckDate;
		this.preDevaluate = preDevaluate;
		this.preMroDate = preMroDate;
		this.preText1 = preText1;
		this.preText10 = preText10;
		this.preText2 = preText2;
		this.preText3 = preText3;
		this.preText4 = preText4;
		this.preText5 = preText5;
		this.preText6 = preText6;
		this.preText7 = preText7;
		this.preText8 = preText8;
		this.preText9 = preText9;
		this.precoding = precoding;
		this.purcPrice = purcPrice;
		this.purcPriceTax = purcPriceTax;
		this.reduceFlag = reduceFlag;
		this.rentFlag = rentFlag;
		this.salvageRate = salvageRate;
		this.serialNum = serialNum;
		this.serviceMonth = serviceMonth;
		this.snFlag = snFlag;
		this.spec = spec;
		this.specialFlag = specialFlag;
		this.startUsedDate = startUsedDate;
		this.statusDate = statusDate;
		this.tax = tax;
		this.transiTypeDist = transiTypeDist;
		this.transiTypeSrc = transiTypeSrc;
		this.ts = ts;
		this.updateDate = updateDate;
		this.usedMonth = usedMonth;
		this.usedStatusDate = usedStatusDate;
	}

	@Id

	@Column(name = "PK_EQUIP", unique = true, nullable = false, length = 20)
	public String getPkEquip() {
		return this.pkEquip;
	}

	public void setPkEquip(String pkEquip) {
		this.pkEquip = pkEquip;
	}

	@Column(name = "ACCU_DEP", precision = 20, scale = 8)
	public BigDecimal getAccuDep() {
		return this.accuDep;
	}

	public void setAccuDep(BigDecimal accuDep) {
		this.accuDep = accuDep;
	}

	@Column(name = "ASSIGN_FLAG", length = 1)
	public Character getAssignFlag() {
		return this.assignFlag;
	}

	public void setAssignFlag(Character assignFlag) {
		this.assignFlag = assignFlag;
	}

	@Column(name = "ASSOCIATE_FLAG", length = 1)
	public Character getAssociateFlag() {
		return this.associateFlag;
	}

	public void setAssociateFlag(Character associateFlag) {
		this.associateFlag = associateFlag;
	}

	@Column(name = "BAR_CODE", length = 200)
	public String getBarCode() {
		return this.barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	@Column(name = "BILL_CODE_DIST", length = 30)
	public String getBillCodeDist() {
		return this.billCodeDist;
	}

	public void setBillCodeDist(String billCodeDist) {
		this.billCodeDist = billCodeDist;
	}

	@Column(name = "BILL_CODE_SRC", length = 30)
	public String getBillCodeSrc() {
		return this.billCodeSrc;
	}

	public void setBillCodeSrc(String billCodeSrc) {
		this.billCodeSrc = billCodeSrc;
	}

	@Column(name = "BILL_TYPE_DIST", length = 10)
	public String getBillTypeDist() {
		return this.billTypeDist;
	}

	public void setBillTypeDist(String billTypeDist) {
		this.billTypeDist = billTypeDist;
	}

	@Column(name = "BILL_TYPE_SRC", length = 20)
	public String getBillTypeSrc() {
		return this.billTypeSrc;
	}

	public void setBillTypeSrc(String billTypeSrc) {
		this.billTypeSrc = billTypeSrc;
	}

	@Column(name = "BORROW_FLAG", length = 1)
	public Character getBorrowFlag() {
		return this.borrowFlag;
	}

	public void setBorrowFlag(Character borrowFlag) {
		this.borrowFlag = borrowFlag;
	}

	@Column(name = "CHECK_PERIOD", length = 128)
	public String getCheckPeriod() {
		return this.checkPeriod;
	}

	public void setCheckPeriod(String checkPeriod) {
		this.checkPeriod = checkPeriod;
	}

	@Column(name = "CHECK_PERIOD_NAME", length = 80)
	public String getCheckPeriodName() {
		return this.checkPeriodName;
	}

	public void setCheckPeriodName(String checkPeriodName) {
		this.checkPeriodName = checkPeriodName;
	}

	@Column(name = "DEF1", length = 128)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 128)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 128)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 128)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 128)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 128)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 128)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 128)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 128)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 128)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 128)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 128)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 128)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF21", length = 128)
	public String getDef21() {
		return this.def21;
	}

	public void setDef21(String def21) {
		this.def21 = def21;
	}

	@Column(name = "DEF22", length = 128)
	public String getDef22() {
		return this.def22;
	}

	public void setDef22(String def22) {
		this.def22 = def22;
	}

	@Column(name = "DEF23", length = 128)
	public String getDef23() {
		return this.def23;
	}

	public void setDef23(String def23) {
		this.def23 = def23;
	}

	@Column(name = "DEF24", length = 128)
	public String getDef24() {
		return this.def24;
	}

	public void setDef24(String def24) {
		this.def24 = def24;
	}

	@Column(name = "DEF25", length = 128)
	public String getDef25() {
		return this.def25;
	}

	public void setDef25(String def25) {
		this.def25 = def25;
	}

	@Column(name = "DEF26", length = 128)
	public String getDef26() {
		return this.def26;
	}

	public void setDef26(String def26) {
		this.def26 = def26;
	}

	@Column(name = "DEF27", length = 128)
	public String getDef27() {
		return this.def27;
	}

	public void setDef27(String def27) {
		this.def27 = def27;
	}

	@Column(name = "DEF28", length = 128)
	public String getDef28() {
		return this.def28;
	}

	public void setDef28(String def28) {
		this.def28 = def28;
	}

	@Column(name = "DEF29", length = 128)
	public String getDef29() {
		return this.def29;
	}

	public void setDef29(String def29) {
		this.def29 = def29;
	}

	@Column(name = "DEF3", length = 128)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF30", length = 128)
	public String getDef30() {
		return this.def30;
	}

	public void setDef30(String def30) {
		this.def30 = def30;
	}

	@Column(name = "DEF31", length = 128)
	public String getDef31() {
		return this.def31;
	}

	public void setDef31(String def31) {
		this.def31 = def31;
	}

	@Column(name = "DEF32", length = 128)
	public String getDef32() {
		return this.def32;
	}

	public void setDef32(String def32) {
		this.def32 = def32;
	}

	@Column(name = "DEF33", length = 128)
	public String getDef33() {
		return this.def33;
	}

	public void setDef33(String def33) {
		this.def33 = def33;
	}

	@Column(name = "DEF34", length = 128)
	public String getDef34() {
		return this.def34;
	}

	public void setDef34(String def34) {
		this.def34 = def34;
	}

	@Column(name = "DEF35", length = 128)
	public String getDef35() {
		return this.def35;
	}

	public void setDef35(String def35) {
		this.def35 = def35;
	}

	@Column(name = "DEF36", length = 128)
	public String getDef36() {
		return this.def36;
	}

	public void setDef36(String def36) {
		this.def36 = def36;
	}

	@Column(name = "DEF37", length = 128)
	public String getDef37() {
		return this.def37;
	}

	public void setDef37(String def37) {
		this.def37 = def37;
	}

	@Column(name = "DEF38", length = 128)
	public String getDef38() {
		return this.def38;
	}

	public void setDef38(String def38) {
		this.def38 = def38;
	}

	@Column(name = "DEF39", length = 128)
	public String getDef39() {
		return this.def39;
	}

	public void setDef39(String def39) {
		this.def39 = def39;
	}

	@Column(name = "DEF4", length = 128)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF40", length = 128)
	public String getDef40() {
		return this.def40;
	}

	public void setDef40(String def40) {
		this.def40 = def40;
	}

	@Column(name = "DEF41", length = 128)
	public String getDef41() {
		return this.def41;
	}

	public void setDef41(String def41) {
		this.def41 = def41;
	}

	@Column(name = "DEF42", length = 128)
	public String getDef42() {
		return this.def42;
	}

	public void setDef42(String def42) {
		this.def42 = def42;
	}

	@Column(name = "DEF43", length = 128)
	public String getDef43() {
		return this.def43;
	}

	public void setDef43(String def43) {
		this.def43 = def43;
	}

	@Column(name = "DEF44", length = 128)
	public String getDef44() {
		return this.def44;
	}

	public void setDef44(String def44) {
		this.def44 = def44;
	}

	@Column(name = "DEF45", length = 128)
	public String getDef45() {
		return this.def45;
	}

	public void setDef45(String def45) {
		this.def45 = def45;
	}

	@Column(name = "DEF46", length = 128)
	public String getDef46() {
		return this.def46;
	}

	public void setDef46(String def46) {
		this.def46 = def46;
	}

	@Column(name = "DEF47", length = 128)
	public String getDef47() {
		return this.def47;
	}

	public void setDef47(String def47) {
		this.def47 = def47;
	}

	@Column(name = "DEF48", length = 128)
	public String getDef48() {
		return this.def48;
	}

	public void setDef48(String def48) {
		this.def48 = def48;
	}

	@Column(name = "DEF49", length = 128)
	public String getDef49() {
		return this.def49;
	}

	public void setDef49(String def49) {
		this.def49 = def49;
	}

	@Column(name = "DEF5", length = 128)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF50", length = 128)
	public String getDef50() {
		return this.def50;
	}

	public void setDef50(String def50) {
		this.def50 = def50;
	}

	@Column(name = "DEF6", length = 128)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 128)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 128)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 128)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DEP_AMOUNT", precision = 20, scale = 8)
	public BigDecimal getDepAmount() {
		return this.depAmount;
	}

	public void setDepAmount(BigDecimal depAmount) {
		this.depAmount = depAmount;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "EQUIP_CODE", length = 28)
	public String getEquipCode() {
		return this.equipCode;
	}

	public void setEquipCode(String equipCode) {
		this.equipCode = equipCode;
	}

	@Column(name = "EQUIP_NAME", length = 75)
	public String getEquipName() {
		return this.equipName;
	}

	public void setEquipName(String equipName) {
		this.equipName = equipName;
	}

	@Column(name = "FA_FLAG", length = 1)
	public Character getFaFlag() {
		return this.faFlag;
	}

	public void setFaFlag(Character faFlag) {
		this.faFlag = faFlag;
	}

	@Column(name = "FACTURER_NAME", length = 75)
	public String getFacturerName() {
		return this.facturerName;
	}

	public void setFacturerName(String facturerName) {
		this.facturerName = facturerName;
	}

	@Column(name = "FK_PARENT", length = 20)
	public String getFkParent() {
		return this.fkParent;
	}

	public void setFkParent(String fkParent) {
		this.fkParent = fkParent;
	}

	@Column(name = "FREEITEM1", length = 100)
	public String getFreeitem1() {
		return this.freeitem1;
	}

	public void setFreeitem1(String freeitem1) {
		this.freeitem1 = freeitem1;
	}

	@Column(name = "FREEITEM10", length = 100)
	public String getFreeitem10() {
		return this.freeitem10;
	}

	public void setFreeitem10(String freeitem10) {
		this.freeitem10 = freeitem10;
	}

	@Column(name = "FREEITEM11", length = 100)
	public String getFreeitem11() {
		return this.freeitem11;
	}

	public void setFreeitem11(String freeitem11) {
		this.freeitem11 = freeitem11;
	}

	@Column(name = "FREEITEM12", length = 100)
	public String getFreeitem12() {
		return this.freeitem12;
	}

	public void setFreeitem12(String freeitem12) {
		this.freeitem12 = freeitem12;
	}

	@Column(name = "FREEITEM13", length = 100)
	public String getFreeitem13() {
		return this.freeitem13;
	}

	public void setFreeitem13(String freeitem13) {
		this.freeitem13 = freeitem13;
	}

	@Column(name = "FREEITEM14", length = 100)
	public String getFreeitem14() {
		return this.freeitem14;
	}

	public void setFreeitem14(String freeitem14) {
		this.freeitem14 = freeitem14;
	}

	@Column(name = "FREEITEM15", length = 100)
	public String getFreeitem15() {
		return this.freeitem15;
	}

	public void setFreeitem15(String freeitem15) {
		this.freeitem15 = freeitem15;
	}

	@Column(name = "FREEITEM16", length = 100)
	public String getFreeitem16() {
		return this.freeitem16;
	}

	public void setFreeitem16(String freeitem16) {
		this.freeitem16 = freeitem16;
	}

	@Column(name = "FREEITEM17", length = 100)
	public String getFreeitem17() {
		return this.freeitem17;
	}

	public void setFreeitem17(String freeitem17) {
		this.freeitem17 = freeitem17;
	}

	@Column(name = "FREEITEM18", length = 100)
	public String getFreeitem18() {
		return this.freeitem18;
	}

	public void setFreeitem18(String freeitem18) {
		this.freeitem18 = freeitem18;
	}

	@Column(name = "FREEITEM19", length = 100)
	public String getFreeitem19() {
		return this.freeitem19;
	}

	public void setFreeitem19(String freeitem19) {
		this.freeitem19 = freeitem19;
	}

	@Column(name = "FREEITEM2", length = 100)
	public String getFreeitem2() {
		return this.freeitem2;
	}

	public void setFreeitem2(String freeitem2) {
		this.freeitem2 = freeitem2;
	}

	@Column(name = "FREEITEM20", length = 100)
	public String getFreeitem20() {
		return this.freeitem20;
	}

	public void setFreeitem20(String freeitem20) {
		this.freeitem20 = freeitem20;
	}

	@Column(name = "FREEITEM3", length = 100)
	public String getFreeitem3() {
		return this.freeitem3;
	}

	public void setFreeitem3(String freeitem3) {
		this.freeitem3 = freeitem3;
	}

	@Column(name = "FREEITEM4", length = 100)
	public String getFreeitem4() {
		return this.freeitem4;
	}

	public void setFreeitem4(String freeitem4) {
		this.freeitem4 = freeitem4;
	}

	@Column(name = "FREEITEM5", length = 100)
	public String getFreeitem5() {
		return this.freeitem5;
	}

	public void setFreeitem5(String freeitem5) {
		this.freeitem5 = freeitem5;
	}

	@Column(name = "FREEITEM6", length = 100)
	public String getFreeitem6() {
		return this.freeitem6;
	}

	public void setFreeitem6(String freeitem6) {
		this.freeitem6 = freeitem6;
	}

	@Column(name = "FREEITEM7", length = 100)
	public String getFreeitem7() {
		return this.freeitem7;
	}

	public void setFreeitem7(String freeitem7) {
		this.freeitem7 = freeitem7;
	}

	@Column(name = "FREEITEM8", length = 100)
	public String getFreeitem8() {
		return this.freeitem8;
	}

	public void setFreeitem8(String freeitem8) {
		this.freeitem8 = freeitem8;
	}

	@Column(name = "FREEITEM9", length = 100)
	public String getFreeitem9() {
		return this.freeitem9;
	}

	public void setFreeitem9(String freeitem9) {
		this.freeitem9 = freeitem9;
	}

	@Column(name = "INSTALL_FEE", precision = 20, scale = 8)
	public BigDecimal getInstallFee() {
		return this.installFee;
	}

	public void setInstallFee(BigDecimal installFee) {
		this.installFee = installFee;
	}

	@Column(name = "LAST_MRO_DATE", length = 10)
	public String getLastMroDate() {
		return this.lastMroDate;
	}

	public void setLastMroDate(String lastMroDate) {
		this.lastMroDate = lastMroDate;
	}

	@Column(name = "LATEST_CHECK_DATE", length = 10)
	public String getLatestCheckDate() {
		return this.latestCheckDate;
	}

	public void setLatestCheckDate(String latestCheckDate) {
		this.latestCheckDate = latestCheckDate;
	}

	@Column(name = "LOCK_FLAG", length = 1)
	public Character getLockFlag() {
		return this.lockFlag;
	}

	public void setLockFlag(Character lockFlag) {
		this.lockFlag = lockFlag;
	}

	@Column(name = "MAKE_DATE", length = 10)
	public String getMakeDate() {
		return this.makeDate;
	}

	public void setMakeDate(String makeDate) {
		this.makeDate = makeDate;
	}

	@Column(name = "MODEL", length = 150)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "MORTGAGE_FLAG", length = 1)
	public Character getMortgageFlag() {
		return this.mortgageFlag;
	}

	public void setMortgageFlag(Character mortgageFlag) {
		this.mortgageFlag = mortgageFlag;
	}

	@Column(name = "MRO_FREQUENCY", precision = 38, scale = 0)
	public BigDecimal getMroFrequency() {
		return this.mroFrequency;
	}

	public void setMroFrequency(BigDecimal mroFrequency) {
		this.mroFrequency = mroFrequency;
	}

	@Column(name = "MRO_UNIT", length = 10)
	public String getMroUnit() {
		return this.mroUnit;
	}

	public void setMroUnit(String mroUnit) {
		this.mroUnit = mroUnit;
	}

	@Column(name = "NET_MONEY", precision = 20, scale = 8)
	public BigDecimal getNetMoney() {
		return this.netMoney;
	}

	public void setNetMoney(BigDecimal netMoney) {
		this.netMoney = netMoney;
	}

	@Column(name = "NEW_VALUE", precision = 20, scale = 8)
	public BigDecimal getNewValue() {
		return this.newValue;
	}

	public void setNewValue(BigDecimal newValue) {
		this.newValue = newValue;
	}

	@Column(name = "NEXT_CHECK_DATE", length = 10)
	public String getNextCheckDate() {
		return this.nextCheckDate;
	}

	public void setNextCheckDate(String nextCheckDate) {
		this.nextCheckDate = nextCheckDate;
	}

	@Column(name = "ORIGIN_VALUE", precision = 20, scale = 8)
	public BigDecimal getOriginValue() {
		return this.originValue;
	}

	public void setOriginValue(BigDecimal originValue) {
		this.originValue = originValue;
	}

	@Column(name = "OUT_FLAG", length = 1)
	public Character getOutFlag() {
		return this.outFlag;
	}

	public void setOutFlag(Character outFlag) {
		this.outFlag = outFlag;
	}

	@Column(name = "PK_AMORG", length = 20)
	public String getPkAmorg() {
		return this.pkAmorg;
	}

	public void setPkAmorg(String pkAmorg) {
		this.pkAmorg = pkAmorg;
	}

	@Column(name = "PK_AMORG_DIST", length = 20)
	public String getPkAmorgDist() {
		return this.pkAmorgDist;
	}

	public void setPkAmorgDist(String pkAmorgDist) {
		this.pkAmorgDist = pkAmorgDist;
	}

	@Column(name = "PK_AMORG_SRC", length = 20)
	public String getPkAmorgSrc() {
		return this.pkAmorgSrc;
	}

	public void setPkAmorgSrc(String pkAmorgSrc) {
		this.pkAmorgSrc = pkAmorgSrc;
	}

	@Column(name = "PK_BILL_B_DIST", length = 20)
	public String getPkBillBDist() {
		return this.pkBillBDist;
	}

	public void setPkBillBDist(String pkBillBDist) {
		this.pkBillBDist = pkBillBDist;
	}

	@Column(name = "PK_BILL_B_SRC", length = 20)
	public String getPkBillBSrc() {
		return this.pkBillBSrc;
	}

	public void setPkBillBSrc(String pkBillBSrc) {
		this.pkBillBSrc = pkBillBSrc;
	}

	@Column(name = "PK_BILL_DIST", length = 20)
	public String getPkBillDist() {
		return this.pkBillDist;
	}

	public void setPkBillDist(String pkBillDist) {
		this.pkBillDist = pkBillDist;
	}

	@Column(name = "PK_BILL_SRC", length = 20)
	public String getPkBillSrc() {
		return this.pkBillSrc;
	}

	public void setPkBillSrc(String pkBillSrc) {
		this.pkBillSrc = pkBillSrc;
	}

	@Column(name = "PK_CALENDAR", length = 20)
	public String getPkCalendar() {
		return this.pkCalendar;
	}

	public void setPkCalendar(String pkCalendar) {
		this.pkCalendar = pkCalendar;
	}

	@Column(name = "PK_CAPITAL_SOURCE", length = 20)
	public String getPkCapitalSource() {
		return this.pkCapitalSource;
	}

	public void setPkCapitalSource(String pkCapitalSource) {
		this.pkCapitalSource = pkCapitalSource;
	}

	@Column(name = "PK_CARD", length = 20)
	public String getPkCard() {
		return this.pkCard;
	}

	public void setPkCard(String pkCard) {
		this.pkCard = pkCard;
	}

	@Column(name = "PK_CATEGORY", length = 20)
	public String getPkCategory() {
		return this.pkCategory;
	}

	public void setPkCategory(String pkCategory) {
		this.pkCategory = pkCategory;
	}

	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_CORP_DIST", length = 4)
	public String getPkCorpDist() {
		return this.pkCorpDist;
	}

	public void setPkCorpDist(String pkCorpDist) {
		this.pkCorpDist = pkCorpDist;
	}

	@Column(name = "PK_CORP_OWNER", length = 4)
	public String getPkCorpOwner() {
		return this.pkCorpOwner;
	}

	public void setPkCorpOwner(String pkCorpOwner) {
		this.pkCorpOwner = pkCorpOwner;
	}

	@Column(name = "PK_CORP_SRC", length = 4)
	public String getPkCorpSrc() {
		return this.pkCorpSrc;
	}

	public void setPkCorpSrc(String pkCorpSrc) {
		this.pkCorpSrc = pkCorpSrc;
	}

	@Column(name = "PK_CORP_USED", length = 4)
	public String getPkCorpUsed() {
		return this.pkCorpUsed;
	}

	public void setPkCorpUsed(String pkCorpUsed) {
		this.pkCorpUsed = pkCorpUsed;
	}

	@Column(name = "PK_CUSMANDOC_OWNER", length = 20)
	public String getPkCusmandocOwner() {
		return this.pkCusmandocOwner;
	}

	public void setPkCusmandocOwner(String pkCusmandocOwner) {
		this.pkCusmandocOwner = pkCusmandocOwner;
	}

	@Column(name = "PK_CUSMANDOC_USED", length = 20)
	public String getPkCusmandocUsed() {
		return this.pkCusmandocUsed;
	}

	public void setPkCusmandocUsed(String pkCusmandocUsed) {
		this.pkCusmandocUsed = pkCusmandocUsed;
	}

	@Column(name = "PK_INVBASEDOC", length = 20)
	public String getPkInvbasedoc() {
		return this.pkInvbasedoc;
	}

	public void setPkInvbasedoc(String pkInvbasedoc) {
		this.pkInvbasedoc = pkInvbasedoc;
	}

	@Column(name = "PK_JOBMNGFIL", length = 20)
	public String getPkJobmngfil() {
		return this.pkJobmngfil;
	}

	public void setPkJobmngfil(String pkJobmngfil) {
		this.pkJobmngfil = pkJobmngfil;
	}

	@Column(name = "PK_LOCATION", length = 20)
	public String getPkLocation() {
		return this.pkLocation;
	}

	public void setPkLocation(String pkLocation) {
		this.pkLocation = pkLocation;
	}

	@Column(name = "PK_MAKER", length = 20)
	public String getPkMaker() {
		return this.pkMaker;
	}

	public void setPkMaker(String pkMaker) {
		this.pkMaker = pkMaker;
	}

	@Column(name = "PK_MANAGER", length = 20)
	public String getPkManager() {
		return this.pkManager;
	}

	public void setPkManager(String pkManager) {
		this.pkManager = pkManager;
	}

	@Column(name = "PK_MANDEPT", length = 20)
	public String getPkMandept() {
		return this.pkMandept;
	}

	public void setPkMandept(String pkMandept) {
		this.pkMandept = pkMandept;
	}

	@Column(name = "PK_PRIORITY", length = 20)
	public String getPkPriority() {
		return this.pkPriority;
	}

	public void setPkPriority(String pkPriority) {
		this.pkPriority = pkPriority;
	}

	@Column(name = "PK_RACK", length = 20)
	public String getPkRack() {
		return this.pkRack;
	}

	public void setPkRack(String pkRack) {
		this.pkRack = pkRack;
	}

	@Column(name = "PK_SOURCE", length = 20)
	public String getPkSource() {
		return this.pkSource;
	}

	public void setPkSource(String pkSource) {
		this.pkSource = pkSource;
	}

	@Column(name = "PK_SRC_DIST", length = 20)
	public String getPkSrcDist() {
		return this.pkSrcDist;
	}

	public void setPkSrcDist(String pkSrcDist) {
		this.pkSrcDist = pkSrcDist;
	}

	@Column(name = "PK_SUPPLIER", length = 20)
	public String getPkSupplier() {
		return this.pkSupplier;
	}

	public void setPkSupplier(String pkSupplier) {
		this.pkSupplier = pkSupplier;
	}

	@Column(name = "PK_UPDATER", length = 20)
	public String getPkUpdater() {
		return this.pkUpdater;
	}

	public void setPkUpdater(String pkUpdater) {
		this.pkUpdater = pkUpdater;
	}

	@Column(name = "PK_USED_STATUS", length = 20)
	public String getPkUsedStatus() {
		return this.pkUsedStatus;
	}

	public void setPkUsedStatus(String pkUsedStatus) {
		this.pkUsedStatus = pkUsedStatus;
	}

	@Column(name = "PK_USEDEPT", length = 20)
	public String getPkUsedept() {
		return this.pkUsedept;
	}

	public void setPkUsedept(String pkUsedept) {
		this.pkUsedept = pkUsedept;
	}

	@Column(name = "PK_USEDEPT_DIST", length = 20)
	public String getPkUsedeptDist() {
		return this.pkUsedeptDist;
	}

	public void setPkUsedeptDist(String pkUsedeptDist) {
		this.pkUsedeptDist = pkUsedeptDist;
	}

	@Column(name = "PK_USEDEPT_SRC", length = 20)
	public String getPkUsedeptSrc() {
		return this.pkUsedeptSrc;
	}

	public void setPkUsedeptSrc(String pkUsedeptSrc) {
		this.pkUsedeptSrc = pkUsedeptSrc;
	}

	@Column(name = "PK_USER", length = 20)
	public String getPkUser() {
		return this.pkUser;
	}

	public void setPkUser(String pkUser) {
		this.pkUser = pkUser;
	}

	@Column(name = "PRE_CHECK_DATE", length = 10)
	public String getPreCheckDate() {
		return this.preCheckDate;
	}

	public void setPreCheckDate(String preCheckDate) {
		this.preCheckDate = preCheckDate;
	}

	@Column(name = "PRE_DEVALUATE", precision = 20, scale = 8)
	public BigDecimal getPreDevaluate() {
		return this.preDevaluate;
	}

	public void setPreDevaluate(BigDecimal preDevaluate) {
		this.preDevaluate = preDevaluate;
	}

	@Column(name = "PRE_MRO_DATE", length = 10)
	public String getPreMroDate() {
		return this.preMroDate;
	}

	public void setPreMroDate(String preMroDate) {
		this.preMroDate = preMroDate;
	}

	@Column(name = "PRE_TEXT1", length = 128)
	public String getPreText1() {
		return this.preText1;
	}

	public void setPreText1(String preText1) {
		this.preText1 = preText1;
	}

	@Column(name = "PRE_TEXT10", length = 128)
	public String getPreText10() {
		return this.preText10;
	}

	public void setPreText10(String preText10) {
		this.preText10 = preText10;
	}

	@Column(name = "PRE_TEXT2", length = 128)
	public String getPreText2() {
		return this.preText2;
	}

	public void setPreText2(String preText2) {
		this.preText2 = preText2;
	}

	@Column(name = "PRE_TEXT3", length = 128)
	public String getPreText3() {
		return this.preText3;
	}

	public void setPreText3(String preText3) {
		this.preText3 = preText3;
	}

	@Column(name = "PRE_TEXT4", length = 128)
	public String getPreText4() {
		return this.preText4;
	}

	public void setPreText4(String preText4) {
		this.preText4 = preText4;
	}

	@Column(name = "PRE_TEXT5", length = 128)
	public String getPreText5() {
		return this.preText5;
	}

	public void setPreText5(String preText5) {
		this.preText5 = preText5;
	}

	@Column(name = "PRE_TEXT6", length = 128)
	public String getPreText6() {
		return this.preText6;
	}

	public void setPreText6(String preText6) {
		this.preText6 = preText6;
	}

	@Column(name = "PRE_TEXT7", length = 128)
	public String getPreText7() {
		return this.preText7;
	}

	public void setPreText7(String preText7) {
		this.preText7 = preText7;
	}

	@Column(name = "PRE_TEXT8", length = 128)
	public String getPreText8() {
		return this.preText8;
	}

	public void setPreText8(String preText8) {
		this.preText8 = preText8;
	}

	@Column(name = "PRE_TEXT9", length = 128)
	public String getPreText9() {
		return this.preText9;
	}

	public void setPreText9(String preText9) {
		this.preText9 = preText9;
	}

	@Column(name = "PRECODING", length = 28)
	public String getPrecoding() {
		return this.precoding;
	}

	public void setPrecoding(String precoding) {
		this.precoding = precoding;
	}

	@Column(name = "PURC_PRICE", precision = 20, scale = 8)
	public BigDecimal getPurcPrice() {
		return this.purcPrice;
	}

	public void setPurcPrice(BigDecimal purcPrice) {
		this.purcPrice = purcPrice;
	}

	@Column(name = "PURC_PRICE_TAX", precision = 20, scale = 8)
	public BigDecimal getPurcPriceTax() {
		return this.purcPriceTax;
	}

	public void setPurcPriceTax(BigDecimal purcPriceTax) {
		this.purcPriceTax = purcPriceTax;
	}

	@Column(name = "REDUCE_FLAG", length = 1)
	public Character getReduceFlag() {
		return this.reduceFlag;
	}

	public void setReduceFlag(Character reduceFlag) {
		this.reduceFlag = reduceFlag;
	}

	@Column(name = "RENT_FLAG", length = 1)
	public Character getRentFlag() {
		return this.rentFlag;
	}

	public void setRentFlag(Character rentFlag) {
		this.rentFlag = rentFlag;
	}

	@Column(name = "SALVAGE_RATE", precision = 20, scale = 8)
	public BigDecimal getSalvageRate() {
		return this.salvageRate;
	}

	public void setSalvageRate(BigDecimal salvageRate) {
		this.salvageRate = salvageRate;
	}

	@Column(name = "SERIAL_NUM", length = 150)
	public String getSerialNum() {
		return this.serialNum;
	}

	public void setSerialNum(String serialNum) {
		this.serialNum = serialNum;
	}

	@Column(name = "SERVICE_MONTH", precision = 38, scale = 0)
	public BigDecimal getServiceMonth() {
		return this.serviceMonth;
	}

	public void setServiceMonth(BigDecimal serviceMonth) {
		this.serviceMonth = serviceMonth;
	}

	@Column(name = "SN_FLAG", length = 1)
	public Character getSnFlag() {
		return this.snFlag;
	}

	public void setSnFlag(Character snFlag) {
		this.snFlag = snFlag;
	}

	@Column(name = "SPEC", length = 150)
	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	@Column(name = "SPECIAL_FLAG", length = 1)
	public Character getSpecialFlag() {
		return this.specialFlag;
	}

	public void setSpecialFlag(Character specialFlag) {
		this.specialFlag = specialFlag;
	}

	@Column(name = "START_USED_DATE", length = 10)
	public String getStartUsedDate() {
		return this.startUsedDate;
	}

	public void setStartUsedDate(String startUsedDate) {
		this.startUsedDate = startUsedDate;
	}

	@Column(name = "STATUS_DATE", length = 10)
	public String getStatusDate() {
		return this.statusDate;
	}

	public void setStatusDate(String statusDate) {
		this.statusDate = statusDate;
	}

	@Column(name = "TAX", precision = 20, scale = 8)
	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	@Column(name = "TRANSI_TYPE_DIST", length = 20)
	public String getTransiTypeDist() {
		return this.transiTypeDist;
	}

	public void setTransiTypeDist(String transiTypeDist) {
		this.transiTypeDist = transiTypeDist;
	}

	@Column(name = "TRANSI_TYPE_SRC", length = 20)
	public String getTransiTypeSrc() {
		return this.transiTypeSrc;
	}

	public void setTransiTypeSrc(String transiTypeSrc) {
		this.transiTypeSrc = transiTypeSrc;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "UPDATE_DATE", length = 10)
	public String getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "USED_MONTH", precision = 38, scale = 0)
	public BigDecimal getUsedMonth() {
		return this.usedMonth;
	}

	public void setUsedMonth(BigDecimal usedMonth) {
		this.usedMonth = usedMonth;
	}

	@Column(name = "USED_STATUS_DATE", length = 10)
	public String getUsedStatusDate() {
		return this.usedStatusDate;
	}

	public void setUsedStatusDate(String usedStatusDate) {
		this.usedStatusDate = usedStatusDate;
	}

}
