package com.nts.teststruts.model;
// Generated 2015-8-21 17:20:37 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PamLocation generated by hbm2java
 */
@Entity
@Table(name = "PAM_LOCATION", schema = "NC58")
public class PamLocation implements java.io.Serializable {

	private String pkLocation;
	private String def1;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def2;
	private String def20;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private Long dr;
	private String fkParent;
	private String innerCode;
	private String locationCode;
	private String locationName;
	private String locationType;
	private Character lockFlag;
	private String makeDate;
	private String maxInnerCode;
	private String memo;
	private String pkCorp;
	private String pkMaker;
	private String pkUpdater;
	private BigDecimal priorityRank;
	private String ts;
	private String updateDate;

	public PamLocation() {
	}

	public PamLocation(String pkLocation) {
		this.pkLocation = pkLocation;
	}

	public PamLocation(String pkLocation, String def1, String def10, String def11, String def12, String def13,
			String def14, String def15, String def16, String def17, String def18, String def19, String def2,
			String def20, String def3, String def4, String def5, String def6, String def7, String def8, String def9,
			Long dr, String fkParent, String innerCode, String locationCode, String locationName, String locationType,
			Character lockFlag, String makeDate, String maxInnerCode, String memo, String pkCorp, String pkMaker,
			String pkUpdater, BigDecimal priorityRank, String ts, String updateDate) {
		this.pkLocation = pkLocation;
		this.def1 = def1;
		this.def10 = def10;
		this.def11 = def11;
		this.def12 = def12;
		this.def13 = def13;
		this.def14 = def14;
		this.def15 = def15;
		this.def16 = def16;
		this.def17 = def17;
		this.def18 = def18;
		this.def19 = def19;
		this.def2 = def2;
		this.def20 = def20;
		this.def3 = def3;
		this.def4 = def4;
		this.def5 = def5;
		this.def6 = def6;
		this.def7 = def7;
		this.def8 = def8;
		this.def9 = def9;
		this.dr = dr;
		this.fkParent = fkParent;
		this.innerCode = innerCode;
		this.locationCode = locationCode;
		this.locationName = locationName;
		this.locationType = locationType;
		this.lockFlag = lockFlag;
		this.makeDate = makeDate;
		this.maxInnerCode = maxInnerCode;
		this.memo = memo;
		this.pkCorp = pkCorp;
		this.pkMaker = pkMaker;
		this.pkUpdater = pkUpdater;
		this.priorityRank = priorityRank;
		this.ts = ts;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "PK_LOCATION", unique = true, nullable = false, length = 20)
	public String getPkLocation() {
		return this.pkLocation;
	}

	public void setPkLocation(String pkLocation) {
		this.pkLocation = pkLocation;
	}

	@Column(name = "DEF1", length = 128)
	public String getDef1() {
		return this.def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	@Column(name = "DEF10", length = 128)
	public String getDef10() {
		return this.def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	@Column(name = "DEF11", length = 128)
	public String getDef11() {
		return this.def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	@Column(name = "DEF12", length = 128)
	public String getDef12() {
		return this.def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	@Column(name = "DEF13", length = 128)
	public String getDef13() {
		return this.def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	@Column(name = "DEF14", length = 128)
	public String getDef14() {
		return this.def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	@Column(name = "DEF15", length = 128)
	public String getDef15() {
		return this.def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	@Column(name = "DEF16", length = 128)
	public String getDef16() {
		return this.def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	@Column(name = "DEF17", length = 128)
	public String getDef17() {
		return this.def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	@Column(name = "DEF18", length = 128)
	public String getDef18() {
		return this.def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	@Column(name = "DEF19", length = 128)
	public String getDef19() {
		return this.def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	@Column(name = "DEF2", length = 128)
	public String getDef2() {
		return this.def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	@Column(name = "DEF20", length = 128)
	public String getDef20() {
		return this.def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}

	@Column(name = "DEF3", length = 128)
	public String getDef3() {
		return this.def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	@Column(name = "DEF4", length = 128)
	public String getDef4() {
		return this.def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	@Column(name = "DEF5", length = 128)
	public String getDef5() {
		return this.def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	@Column(name = "DEF6", length = 128)
	public String getDef6() {
		return this.def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	@Column(name = "DEF7", length = 128)
	public String getDef7() {
		return this.def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	@Column(name = "DEF8", length = 128)
	public String getDef8() {
		return this.def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	@Column(name = "DEF9", length = 128)
	public String getDef9() {
		return this.def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "FK_PARENT", length = 20)
	public String getFkParent() {
		return this.fkParent;
	}

	public void setFkParent(String fkParent) {
		this.fkParent = fkParent;
	}

	@Column(name = "INNER_CODE", length = 60)
	public String getInnerCode() {
		return this.innerCode;
	}

	public void setInnerCode(String innerCode) {
		this.innerCode = innerCode;
	}

	@Column(name = "LOCATION_CODE", length = 28)
	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	@Column(name = "LOCATION_NAME", length = 75)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "LOCATION_TYPE", length = 4)
	public String getLocationType() {
		return this.locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	@Column(name = "LOCK_FLAG", length = 1)
	public Character getLockFlag() {
		return this.lockFlag;
	}

	public void setLockFlag(Character lockFlag) {
		this.lockFlag = lockFlag;
	}

	@Column(name = "MAKE_DATE", length = 10)
	public String getMakeDate() {
		return this.makeDate;
	}

	public void setMakeDate(String makeDate) {
		this.makeDate = makeDate;
	}

	@Column(name = "MAX_INNER_CODE", length = 60)
	public String getMaxInnerCode() {
		return this.maxInnerCode;
	}

	public void setMaxInnerCode(String maxInnerCode) {
		this.maxInnerCode = maxInnerCode;
	}

	@Column(name = "MEMO", length = 150)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "PK_CORP", length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PK_MAKER", length = 20)
	public String getPkMaker() {
		return this.pkMaker;
	}

	public void setPkMaker(String pkMaker) {
		this.pkMaker = pkMaker;
	}

	@Column(name = "PK_UPDATER", length = 20)
	public String getPkUpdater() {
		return this.pkUpdater;
	}

	public void setPkUpdater(String pkUpdater) {
		this.pkUpdater = pkUpdater;
	}

	@Column(name = "PRIORITY_RANK", precision = 38, scale = 0)
	public BigDecimal getPriorityRank() {
		return this.priorityRank;
	}

	public void setPriorityRank(BigDecimal priorityRank) {
		this.priorityRank = priorityRank;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "UPDATE_DATE", length = 20)
	public String getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

}
