package com.nts.teststruts.model;
// Generated 2015-7-26 20:25:59 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmRole generated by hbm2java
 */
@Entity
@Table(name = "SM_ROLE", schema = "NC58")
public class SmRole implements java.io.Serializable {

	private String pkRole;
	private Long dr;
	private Character keyrole;
	private String pkCorp;
	private BigDecimal resourceType;
	private String roleCode;
	private String roleMemo;
	private String roleName;
	private String ts;
	private BigDecimal usercount;

	public SmRole() {
	}

	public SmRole(String pkRole, String pkCorp, BigDecimal resourceType, String roleCode, String roleName) {
		this.pkRole = pkRole;
		this.pkCorp = pkCorp;
		this.resourceType = resourceType;
		this.roleCode = roleCode;
		this.roleName = roleName;
	}

	public SmRole(String pkRole, Long dr, Character keyrole, String pkCorp, BigDecimal resourceType, String roleCode,
			String roleMemo, String roleName, String ts, BigDecimal usercount) {
		this.pkRole = pkRole;
		this.dr = dr;
		this.keyrole = keyrole;
		this.pkCorp = pkCorp;
		this.resourceType = resourceType;
		this.roleCode = roleCode;
		this.roleMemo = roleMemo;
		this.roleName = roleName;
		this.ts = ts;
		this.usercount = usercount;
	}

	@Id

	@Column(name = "PK_ROLE", unique = true, nullable = false, length = 20)
	public String getPkRole() {
		return this.pkRole;
	}

	public void setPkRole(String pkRole) {
		this.pkRole = pkRole;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "KEYROLE", length = 1)
	public Character getKeyrole() {
		return this.keyrole;
	}

	public void setKeyrole(Character keyrole) {
		this.keyrole = keyrole;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "RESOURCE_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(BigDecimal resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "ROLE_CODE", nullable = false, length = 30)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "ROLE_MEMO", length = 150)
	public String getRoleMemo() {
		return this.roleMemo;
	}

	public void setRoleMemo(String roleMemo) {
		this.roleMemo = roleMemo;
	}

	@Column(name = "ROLE_NAME", nullable = false, length = 75)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "USERCOUNT", precision = 38, scale = 0)
	public BigDecimal getUsercount() {
		return this.usercount;
	}

	public void setUsercount(BigDecimal usercount) {
		this.usercount = usercount;
	}

}
