package com.nts.teststruts.model;
// Generated 2015-7-26 20:25:59 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmUser generated by hbm2java
 */
@Entity
@Table(name = "SM_USER", schema = "NC58")
public class SmUser implements java.io.Serializable {

	private String cuserid;
	private String ableTime;
	private String authenType;
	private String disableTime;
	private Long dr;
	private Character isca;
	private Character keyuser;
	private String langcode;
	private Character lockedTag;
	private String pkCorp;
	private String pwdlevelcode;
	private String pwdparam;
	private BigDecimal pwdtype;
	private String ts;
	private String userCode;
	private String userName;
	private String userNote;
	private String userPassword;

	public SmUser() {
	}

	public SmUser(String cuserid, String pkCorp, String userCode, String userName) {
		this.cuserid = cuserid;
		this.pkCorp = pkCorp;
		this.userCode = userCode;
		this.userName = userName;
	}

	public SmUser(String cuserid, String ableTime, String authenType, String disableTime, Long dr, Character isca,
			Character keyuser, String langcode, Character lockedTag, String pkCorp, String pwdlevelcode,
			String pwdparam, BigDecimal pwdtype, String ts, String userCode, String userName, String userNote,
			String userPassword) {
		this.cuserid = cuserid;
		this.ableTime = ableTime;
		this.authenType = authenType;
		this.disableTime = disableTime;
		this.dr = dr;
		this.isca = isca;
		this.keyuser = keyuser;
		this.langcode = langcode;
		this.lockedTag = lockedTag;
		this.pkCorp = pkCorp;
		this.pwdlevelcode = pwdlevelcode;
		this.pwdparam = pwdparam;
		this.pwdtype = pwdtype;
		this.ts = ts;
		this.userCode = userCode;
		this.userName = userName;
		this.userNote = userNote;
		this.userPassword = userPassword;
	}

	@Id
	@Column(name = "CUSERID", unique = true, nullable = false, length = 20)
	public String getCuserid() {
		return this.cuserid;
	}

	public void setCuserid(String cuserid) {
		this.cuserid = cuserid;
	}

	@Column(name = "ABLE_TIME", length = 10)
	public String getAbleTime() {
		return this.ableTime;
	}

	public void setAbleTime(String ableTime) {
		this.ableTime = ableTime;
	}

	@Column(name = "AUTHEN_TYPE", length = 100)
	public String getAuthenType() {
		return this.authenType;
	}

	public void setAuthenType(String authenType) {
		this.authenType = authenType;
	}

	@Column(name = "DISABLE_TIME", length = 10)
	public String getDisableTime() {
		return this.disableTime;
	}

	public void setDisableTime(String disableTime) {
		this.disableTime = disableTime;
	}

	@Column(name = "DR", precision = 10, scale = 0)
	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}

	@Column(name = "ISCA", length = 1)
	public Character getIsca() {
		return this.isca;
	}

	public void setIsca(Character isca) {
		this.isca = isca;
	}

	@Column(name = "KEYUSER", length = 1)
	public Character getKeyuser() {
		return this.keyuser;
	}

	public void setKeyuser(Character keyuser) {
		this.keyuser = keyuser;
	}

	@Column(name = "LANGCODE", length = 20)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "LOCKED_TAG", length = 1)
	public Character getLockedTag() {
		return this.lockedTag;
	}

	public void setLockedTag(Character lockedTag) {
		this.lockedTag = lockedTag;
	}

	@Column(name = "PK_CORP", nullable = false, length = 4)
	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	@Column(name = "PWDLEVELCODE", length = 50)
	public String getPwdlevelcode() {
		return this.pwdlevelcode;
	}

	public void setPwdlevelcode(String pwdlevelcode) {
		this.pwdlevelcode = pwdlevelcode;
	}

	@Column(name = "PWDPARAM", length = 50)
	public String getPwdparam() {
		return this.pwdparam;
	}

	public void setPwdparam(String pwdparam) {
		this.pwdparam = pwdparam;
	}

	@Column(name = "PWDTYPE", precision = 38, scale = 0)
	public BigDecimal getPwdtype() {
		return this.pwdtype;
	}

	public void setPwdtype(BigDecimal pwdtype) {
		this.pwdtype = pwdtype;
	}

	@Column(name = "TS", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "USER_CODE", nullable = false, length = 30)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Column(name = "USER_NAME", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_NOTE", length = 75)
	public String getUserNote() {
		return this.userNote;
	}

	public void setUserNote(String userNote) {
		this.userNote = userNote;
	}

	@Column(name = "USER_PASSWORD", length = 50)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

}
